import { createServerFn } from "@tanstack/react-start";
import { getRequest } from "@tanstack/react-start/server";

async function requireGuildManager(guildId: string) {
  const { readSessionFromCookie } = await import("@/lib/session.server");
  const { getValidAccessToken, userManagesGuild } = await import("@/lib/discord.server");
  const req = getRequest();
  const userId = readSessionFromCookie(req?.headers.get("cookie") ?? null);
  if (!userId) throw new Error("Not signed in");
  const session = await getValidAccessToken(userId);
  if (!session) throw new Error("Session expired");
  const guild = await userManagesGuild(session.accessToken, guildId);
  if (!guild) throw new Error("You don't manage this server");
  return { guild, session, userId };
}

export type AnalyticsDay = { date:string; messages:number; reactions:number; voice_seconds:number; joins:number; leaves:number; commands:number };
export type AnalyticsRankRow = { id?:string; name:string; value:number; avatar_url?:string|null };
export type GuildAnalyticsPayload = {
  version?:number; guild_id:string; generated_at?:string; member_count?:number; days?:AnalyticsDay[];
  top_message_channels?:AnalyticsRankRow[]; top_voice_channels?:AnalyticsRankRow[]; top_message_members?:AnalyticsRankRow[]; top_voice_members?:AnalyticsRankRow[]; top_commands?:AnalyticsRankRow[];
  totals?:{messages?:number;reactions?:number;voice_seconds?:number;joins?:number;leaves?:number;commands?:number;active_users?:number};
};
export type AnalyticsMemberProfile = {
  id:string; username:string; displayName:string; avatarUrl:string|null; inGuild:boolean;
  joinedServerAt:string|null; joinedDiscordAt:string;
  roles:{id:string;name:string;color:number;iconUrl:string|null;unicodeEmoji:string|null;managed:boolean}[];
};

const DISCORD_API="https://discord.com/api/v10";
function getBotToken(){return(process.env.DISCORD_BOT_TOKEN||process.env.BOT_TOKEN||process.env.DISCORD_TOKEN||"").trim().replace(/^Bot\s+/i,"")}
function looksLikeSnowflake(v:string){return /^\d{15,22}$/.test(v.trim())}
function botHeaders(extra:Record<string,string>={}){return{Authorization:`Bot ${getBotToken()}`,"Content-Type":"application/json",...extra}}
function avatarUrl(user:{id:string;avatar?:string|null}){if(!user.avatar)return null;const ext=user.avatar.startsWith("a_")?"gif":"png";return `https://cdn.discordapp.com/avatars/${user.id}/${user.avatar}.${ext}?size=256`}
function snowflakeDate(id:string){try{return new Date(Number((BigInt(id)>>22n)+1420070400000n)).toISOString()}catch{return new Date(0).toISOString()}}
async function discordFetch(url:string,init:RequestInit={},attempts=4){let last:Response|null=null;for(let i=0;i<attempts;i++){try{const res=await fetch(url,{cache:"no-store",...init});last=res;if(res.status===429){let wait=400*(i+1);try{const data=await res.clone().json() as any;wait=Math.max(wait,Number(data.retry_after||0)*1000)}catch{}await new Promise(r=>setTimeout(r,Math.min(wait,2500)));continue}if(res.status>=500&&i<attempts-1){await new Promise(r=>setTimeout(r,250*(i+1)));continue}return res}catch{if(i<attempts-1)await new Promise(r=>setTimeout(r,250*(i+1)))}}return last}

async function fetchChannelMap(guildId:string,ids:string[]){const map=new Map<string,string>();if(!getBotToken()||!ids.length)return{map,authoritative:false};const headers={Authorization:`Bot ${getBotToken()}`};const res=await discordFetch(`${DISCORD_API}/guilds/${guildId}/channels`,{headers});if(!res?.ok)return{map,authoritative:false};const channels=await res.json() as any[];for(const c of channels)if(c?.id&&c?.name)map.set(String(c.id),String(c.name));return{map,authoritative:true}}
async function fetchMemberIdentityMap(guildId:string,ids:string[]){const map=new Map<string,{username:string;displayName:string;avatarUrl:string|null}>();if(!getBotToken())return map;await Promise.all([...new Set(ids)].slice(0,30).map(async id=>{const memberRes=await discordFetch(`${DISCORD_API}/guilds/${guildId}/members/${id}`,{headers:botHeaders()});if(memberRes?.ok){const member=await memberRes.json() as any;const user=member.user??{};map.set(id,{username:String(user.username||id),displayName:String(member.nick||user.global_name||user.username||id),avatarUrl:avatarUrl(user)});return}if(memberRes?.status===404){const userRes=await discordFetch(`${DISCORD_API}/users/${id}`,{headers:botHeaders()});if(userRes?.ok){const user=await userRes.json() as any;const username=String(user.username||id);map.set(id,{username,displayName:username,avatarUrl:avatarUrl(user)})}}}));return map}
function resolveChannelRows(rows:AnalyticsRankRow[]|undefined,result:{map:Map<string,string>;authoritative:boolean}){return(rows??[]).map(row=>{const snapshot=String(row.name||"").trim();const id=String(row.id||(looksLikeSnowflake(snapshot)?snapshot:"")||"");const live=id?result.map.get(id):undefined;const usable=snapshot&&!looksLikeSnowflake(snapshot)&&snapshot.toLowerCase()!=="unknown channel"&&snapshot.toLowerCase()!=="channel"&&!/^channel-\d+$/i.test(snapshot);let name=live||(usable?snapshot:"deleted-channel");if(id&&result.authoritative&&!live)name="deleted-channel";return{...row,id:id||row.id,name}})}
function resolveMemberRows(rows:AnalyticsRankRow[]|undefined,map:Map<string,{username:string;displayName:string;avatarUrl:string|null}>){return(rows??[]).map(row=>{const live=row.id?map.get(String(row.id)):undefined;return live?{...row,name:live.username,avatar_url:live.avatarUrl||row.avatar_url}:row})}

export const getGuildAnalytics=createServerFn({method:"GET"}).inputValidator((d:{guildId:string})=>d).handler(async({data})=>{await requireGuildManager(data.guildId);const{supabaseAdmin}=await import("@/integrations/supabase/client.server");const{data:row,error}=await(supabaseAdmin as any).from("guild_analytics_snapshots").select("payload,updated_at").eq("guild_id",data.guildId).maybeSingle();if(error||!row?.payload)return{connected:false as const,payload:null,updatedAt:null};const payload=row.payload as GuildAnalyticsPayload;const channelIds=[...(payload.top_message_channels??[]),...(payload.top_voice_channels??[])].map(e=>String(e.id||(looksLikeSnowflake(String(e.name||""))?e.name:"")||"")).filter(Boolean);const memberIds=[...(payload.top_message_members??[]),...(payload.top_voice_members??[])].map(e=>String(e.id||"")).filter(looksLikeSnowflake);const[channelResult,memberMap]=await Promise.all([fetchChannelMap(data.guildId,channelIds),fetchMemberIdentityMap(data.guildId,memberIds)]);return{connected:true as const,payload:{...payload,top_message_channels:resolveChannelRows(payload.top_message_channels,channelResult),top_voice_channels:resolveChannelRows(payload.top_voice_channels,channelResult),top_message_members:resolveMemberRows(payload.top_message_members,memberMap),top_voice_members:resolveMemberRows(payload.top_voice_members,memberMap)},updatedAt:String(row.updated_at||"")}});

export const getAnalyticsMemberProfile=createServerFn({method:"GET"}).inputValidator((d:{guildId:string;userId:string})=>d).handler(async({data}):Promise<AnalyticsMemberProfile>=>{await requireGuildManager(data.guildId);if(!looksLikeSnowflake(data.userId))throw new Error("Invalid member ID");if(!getBotToken())throw new Error("Ware's Discord connection is unavailable right now");const memberRes=await discordFetch(`${DISCORD_API}/guilds/${data.guildId}/members/${data.userId}`,{headers:botHeaders()},5);if(!memberRes)throw new Error("Discord did not respond. Try again.");const definitiveLeft=memberRes.status===404;if(!memberRes.ok&&!definitiveLeft)throw new Error(`Discord member lookup failed (${memberRes.status}). Try again.`);const member=memberRes.ok?await memberRes.json() as any:null;const[rolesRes,userRes]=await Promise.all([discordFetch(`${DISCORD_API}/guilds/${data.guildId}/roles`,{headers:botHeaders()},4),discordFetch(`${DISCORD_API}/users/${data.userId}`,{headers:botHeaders()},4)]);if(!userRes?.ok&&!member)throw new Error("Discord user could not be loaded");const user=member?.user??(userRes?.ok?await userRes.json() as any:{id:data.userId,username:data.userId});const allRoles=rolesRes?.ok?await rolesRes.json() as any[]:[];const memberRoleIds=new Set<string>(member?.roles??[]);const roles=allRoles.filter(r=>memberRoleIds.has(String(r.id))).sort((a,b)=>Number(b.position||0)-Number(a.position||0)).map(r=>({id:String(r.id),name:String(r.name),color:Number(r.color||0),managed:Boolean(r.managed),unicodeEmoji:r.unicode_emoji?String(r.unicode_emoji):null,iconUrl:r.icon?`https://cdn.discordapp.com/role-icons/${r.id}/${r.icon}.png?size=64`:null}));return{id:String(user.id),username:String(user.username||data.userId),displayName:String(member?.nick||user.global_name||user.username||data.userId),avatarUrl:avatarUrl(user),inGuild:Boolean(member),joinedServerAt:member?.joined_at?String(member.joined_at):null,joinedDiscordAt:snowflakeDate(String(user.id)),roles}});

export const removeAnalyticsMemberRole=createServerFn({method:"POST"}).inputValidator((d:{guildId:string;userId:string;roleId:string})=>d).handler(async({data})=>{const{session,userId:managerId}=await requireGuildManager(data.guildId);if(![data.userId,data.roleId].every(looksLikeSnowflake))throw new Error("Invalid Discord ID");let managerName=managerId;try{const meRes=await fetch(`${DISCORD_API}/users/@me`,{headers:{Authorization:`Bearer ${session.accessToken}`},cache:"no-store"});if(meRes.ok){const me=await meRes.json() as any;managerName=String(me.username||me.global_name||managerId)}}catch{}const reason=encodeURIComponent(`Removed from Ware Dashboard | By ${managerName} (${managerId})`);const res=await fetch(`${DISCORD_API}/guilds/${data.guildId}/members/${data.userId}/roles/${data.roleId}`,{method:"DELETE",headers:botHeaders({"X-Audit-Log-Reason":reason})});if(!res.ok)throw new Error(`Discord role removal failed: ${res.status} ${await res.text()}`);return{ok:true,managerName,managerId}});
