// Explicit root ownership keeps a command and its subcommands together.
export const commandCategoryDefinitions = [
  {
    slug: "information",
    name: "Information",
    description: "Bot, member, and server information.",
    roots: [
      "activities",
      "avatar",
      "badges",
      "banner",
      "bio",
      "birthday",
      "boostcount",
      "boosters",
      "botinfo",
      "cashapp",
      "channelinfo",
      "cleargnames",
      "clearnames",
      "cmds",
      "devices",
      "donate",
      "emojiinfo",
      "emojis",
      "getuser",
      "gnames",
      "help",
      "https://warebot.xyz",
      "inviteinfo",
      "invites",
      "joined",
      "membercount",
      "mutuals",
      "names",
      "newest",
      "newmembers",
      "oauth",
      "oldest",
      "perms",
      "ping",
      "profile",
      "roleinfo",
      "roles",
      "s?u",
      "serveravatar",
      "serverbanner",
      "servericon",
      "serverinfo",
      "snowflake",
      "splash",
      "stats",
      "status",
      "stickerinfo",
      "stickers",
      "support",
      "topcommands",
      "uptime",
      "vote",
      "who",
      "whois",
      "wrapped",
    ],
  },
  {
    slug: "moderation",
    name: "Moderation",
    description: "Cases, punishments, cleanup, and staff tools.",
    roots: [
      "audit",
      "ban",
      "bc",
      "c",
      "case",
      "caselog",
      "cases",
      "cleanup",
      "clear",
      "fn",
      "force",
      "forceavatar",
      "forcenickname",
      "forcetimeout",
      "hardban",
      "history",
      "imute",
      "invoke",
      "iunmute",
      "jail",
      "jaillist",
      "kick",
      "lastseen",
      "lockdown",
      "masskick",
      "massnick",
      "massrename",
      "massunmute",
      "massuntimeout",
      "moderationhistory",
      "modstats",
      "mute",
      "nick",
      "note",
      "notes",
      "nuke",
      "proof",
      "punishments",
      "purge",
      "purgeafter",
      "purgebefore",
      "purgebots",
      "purgeembeds",
      "purgefiles",
      "purgehumans",
      "purgeimages",
      "purgeinvites",
      "purgelinks",
      "purgenitro",
      "purgerange",
      "purgereactions",
      "purgeuser",
      "quarantine",
      "raidmode",
      "reason",
      "recentban",
      "resetnick",
      "restore",
      "revokefiles",
      "rmute",
      "runmute",
      "seen",
      "setup",
      "setupmute",
      "slowmode",
      "softban",
      "staffnote",
      "staffnotes",
      "stripstaff",
      "tempban",
      "timeout",
      "unban",
      "unbanall",
      "unimute",
      "unjail",
      "unlockdown",
      "unmute",
      "unrmute",
      "untimeout",
      "warn",
      "warnings",
    ],
  },
  {
    slug: "server",
    name: "Server",
    description: "Configure channels, messages, reactions, and server features.",
    roots: [
      "alias",
      "autoreact",
      "autoresponder",
      "backup",
      "boost",
      "boosts",
      "bumpreminder",
      "button",
      "buttonrole",
      "channel",
      "cloneuser",
      "clownboard",
      "copydisabled",
      "counter",
      "counting",
      "createembed",
      "customize",
      "dashboard",
      "disablecommand",
      "disableevent",
      "disablemodule",
      "dropdown",
      "embed",
      "embedcode",
      "enablecommand",
      "enableevent",
      "enablemodule",
      "fakepermissions",
      "goodbye",
      "hide",
      "ignore",
      "imgonly",
      "impersonate",
      "join",
      "lock",
      "lockall",
      "naughty",
      "nsfw",
      "pagination",
      "pin",
      "pins",
      "poll",
      "prefix",
      "quickpoll",
      "reactionrole",
      "restrictcommand",
      "selfrole",
      "sendmessage",
      "servervanity",
      "setbanner",
      "seticon",
      "setsplashbackground",
      "settings",
      "setupdashboard",
      "starboard",
      "stick",
      "stickymessage",
      "stickyrole",
      "sudo",
      "tags",
      "talk",
      "thread",
      "topic",
      "unhide",
      "unlock",
      "unlockall",
      "unpin",
      "vanity",
      "verify",
      "webhook",
      "welcome",
    ],
  },
  {
    slug: "roles",
    name: "Roles",
    description: "Role management, autoroles, and booster roles.",
    roots: [
      "autorole",
      "boosterrole",
      "bots",
      "dump",
      "force_role",
      "forcerole",
      "humans",
      "inrole",
      "massrole",
      "members",
      "role",
      "roleall",
      "rolebots",
      "rolehumans",
      "stealrole",
      "temprole",
      "unroleall",
    ],
  },
  {
    slug: "antinuke",
    name: "Antinuke",
    description: "Protect your server from destructive actions and abuse.",
    roots: ["anti", "antinuke", "automod", "filter", "honeypot", "scam", "security", "whitelist"],
  },
  {
    slug: "antiraid",
    name: "Antiraid",
    description: "Manage join protection and raid prevention.",
    roots: ["antiraid"],
  },
  {
    slug: "voicemaster",
    name: "VoiceMaster",
    description: "Create and manage voice channels.",
    roots: [
      "disconnectall",
      "drag",
      "massdisconnect",
      "massmove",
      "move",
      "moveall",
      "voiceban",
      "voicekick",
      "voicemaster",
      "voiceunban",
    ],
  },
  {
    slug: "logs",
    name: "Logs",
    description: "Configure server events and moderation logs.",
    roots: ["log", "modlog"],
  },
  {
    slug: "utility",
    name: "Utility",
    description: "Everyday tools, translation, reminders, and searches.",
    roots: [
      "addemote",
      "afk",
      "anime",
      "base64",
      "book",
      "boostmessage",
      "bot",
      "brainly",
      "calculator",
      "character",
      "charinfo",
      "color",
      "count",
      "countdown",
      "define",
      "duckduckgo",
      "emoji",
      "emotes",
      "extractemotes",
      "extractstickers",
      "firstmessage",
      "game",
      "google",
      "highlight",
      "jumbo",
      "manga",
      "memory",
      "movie",
      "ocr",
      "ocrtr",
      "qr",
      "randomhex",
      "reaction",
      "remind",
      "reminders",
      "rename",
      "run",
      "search",
      "sfw",
      "steal",
      "steal-sticker",
      "sticker",
      "suggest",
      "timediff",
      "timer",
      "timestamp",
      "timezone",
      "translate",
      "tvshow",
      "urban",
      "urbandictionary",
      "weather",
      "wiki",
      "wikihow",
      "wolfram",
    ],
  },
  {
    slug: "snipe",
    name: "Snipe",
    description: "View and clear deleted messages, edits, and reactions.",
    roots: ["clearreactionsnipe", "cs", "editsnipe", "reactionsnipe", "snipe"],
  },
  {
    slug: "tickets",
    name: "Tickets",
    description: "Support tickets, claims, and transcripts.",
    roots: ["claim", "close", "delete", "reopen", "tickets", "transcript", "unclaim"],
  },
  {
    slug: "lastfm",
    name: "Last.fm",
    description: "Listening history, music profiles, and Last.fm tools.",
    roots: ["discog", "fm", "lastfm", "nowplaying"],
  },
  {
    slug: "music",
    name: "Music",
    description: "Playback, queues, lyrics, and audio tools.",
    roots: [
      "itunes",
      "lyrics",
      "pause",
      "play",
      "preset",
      "queue",
      "repeat",
      "resume",
      "seek",
      "shazam",
      "skip",
      "stop",
      "tts",
      "volume",
    ],
  },
  {
    slug: "spotify",
    name: "Spotify",
    description: "Spotify profiles, tracks, and albums.",
    roots: ["spotify", "spotifyalbum", "spotifytrack"],
  },
  {
    slug: "twitch",
    name: "Twitch",
    description: "Twitch commands and integrations.",
    roots: ["twitch"],
  },
  {
    slug: "youtube",
    name: "YouTube",
    description: "YouTube commands and integrations.",
    roots: ["youtube"],
  },
  {
    slug: "roblox",
    name: "Roblox",
    description: "Roblox commands and integrations.",
    roots: ["roblox", "robloxid"],
  },
  {
    slug: "instagram",
    name: "Instagram",
    description: "Instagram commands and integrations.",
    roots: ["instagram"],
  },
  {
    slug: "tiktok",
    name: "TikTok",
    description: "TikTok commands and integrations.",
    roots: ["tiktok"],
  },
  {
    slug: "twitter",
    name: "X / Twitter",
    description: "X / Twitter commands and integrations.",
    roots: ["twitter"],
  },
  {
    slug: "fortnite",
    name: "Fortnite",
    description: "Fortnite commands and integrations.",
    roots: ["fortnite"],
  },
  {
    slug: "kick",
    name: "Kick",
    description: "Kick commands and integrations.",
    roots: [],
  },
  {
    slug: "social",
    name: "Social",
    description: "Creator notifications, social profiles, and game stats.",
    roots: [
      "github",
      "minecraft",
      "osu",
      "reposter",
      "snapchat",
      "snapchatstory",
      "steam",
      "telegram",
      "valorant",
      "xbox",
    ],
  },
  {
    slug: "media",
    name: "Media",
    description: "Images, video, GIFs, and editing tools.",
    roots: [
      "blur",
      "compress",
      "giphy",
      "imagerestore",
      "img",
      "invert",
      "lego",
      "makegif",
      "makemp3",
      "media",
      "pixelate",
      "quote",
      "removebg",
      "reverseimage",
      "rotate",
      "screenshot",
      "tenor",
      "transparent",
      "trash",
      "triggered",
      "upscale",
      "wanted",
    ],
  },
  {
    slug: "fun",
    name: "Fun",
    description: "Quick games, jokes, and fun with your server.",
    roots: [
      "8ball",
      "aura",
      "bitches",
      "braincells",
      "choose",
      "clih",
      "clown",
      "coin",
      "cook",
      "delulu",
      "dice",
      "dih",
      "freaky",
      "futbol",
      "gay",
      "height",
      "howgay",
      "howhot",
      "joke",
      "juul",
      "lesbian",
      "luck",
      "marry",
      "mlb",
      "nba",
      "nfl",
      "nhl",
      "npc",
      "pp",
      "rate",
      "reverse",
      "rizz",
      "roast",
      "rps",
      "ship",
      "sigma",
      "simp",
      "soccer",
      "touchgrass",
      "uwu",
      "virgin",
      "wouldyourather",
    ],
  },
  {
    slug: "games",
    name: "Games",
    description: "Play games and challenges with your friends.",
    roots: [
      "2048",
      "battleship",
      "blacktea",
      "challenge",
      "checkers",
      "chess",
      "connect4",
      "country",
      "end",
      "fasttype",
      "flag",
      "flags",
      "hangman",
      "higherlower",
      "math",
      "memorygame",
      "mines",
      "scramble",
      "tictactoe",
      "trivia",
      "unscramble",
    ],
  },
  {
    slug: "roleplay",
    name: "Roleplay",
    description: "Reactions and interactions with other members.",
    roots: [
      "airkiss",
      "angrystare",
      "bite",
      "bleh",
      "brofist",
      "celebrate",
      "cheers",
      "clap",
      "confused",
      "cool",
      "cry",
      "cuddle",
      "dance",
      "drool",
      "evillaugh",
      "facepalm",
      "handhold",
      "happy",
      "headbang",
      "hug",
      "kiss",
      "laugh",
      "lick",
      "love",
      "mad",
      "nervous",
      "nom",
      "nuzzle",
      "nyah",
      "pat",
      "peek",
      "pinch",
      "poke",
      "pout",
      "punch",
      "roleplay",
      "sad",
      "scared",
      "shout",
      "shrug",
      "shy",
      "sigh",
      "slap",
    ],
  },
  {
    slug: "economy",
    name: "Economy",
    description: "Balances, shops, trading, and casino games.",
    roots: [
      "balance",
      "bank",
      "beg",
      "blackjack",
      "btc",
      "buy",
      "casino",
      "coinflip",
      "crash",
      "crime",
      "crypto",
      "daily",
      "deposit",
      "duel",
      "economy",
      "fishing",
      "heist",
      "interest",
      "inventory",
      "leaderboards",
      "lottery",
      "ltc",
      "market",
      "monthly",
      "pay",
      "pets",
      "poker",
      "roulette",
      "sell",
      "shop",
      "slots",
      "sol",
      "stocks",
      "trade",
      "weekly",
      "withdraw",
      "work",
    ],
  },
  {
    slug: "leveling",
    name: "Leveling",
    description: "XP, ranks, and level rewards.",
    roots: ["levels", "rank", "setlevel", "setxp", "xp"],
  },
  {
    slug: "giveaways",
    name: "Giveaways",
    description: "Create, manage, and reroll giveaways.",
    roots: ["gedit", "gend", "giveaway", "glist", "greroll", "gstart"],
  },
  {
    slug: "ai",
    name: "AI",
    description: "Writing, questions, summaries, and AI tools.",
    roots: [
      "ai",
      "ai2",
      "aichat",
      "aicode",
      "aiexplain",
      "aigrammar",
      "aiimage",
      "aimod",
      "code",
      "continue",
      "essay",
      "execute",
      "explain",
      "gemini",
      "imagine",
      "review",
      "rewrite",
      "summarize",
      "tone",
    ],
  },
  {
    slug: "premium",
    name: "Premium",
    description: "Manage your Stained premium subscription.",
    roots: ["premium"],
  },
] as const;

export const legacyCommandCategories: Record<string, string> = {
  home: "information",
  "channels-roles": "roles",
  "config-logs": "server",
  images: "media",
  security: "information",
  welcome: "server",
  counters: "server",
  timers: "utility",
  "fake-permissions": "server",
  "bump-reminder": "server",
  manipulation: "media",
  user: "information",
  miscellaneous: "utility",
};
