export interface CommandDef {
  name: string;
  description: string;
  usage: string;
  example: string;
  aliases?: string[];
}

export interface CommandCategory {
  slug: string;
  name: string;
  description: string;
  commands: CommandDef[];
}

const cmd = (
  name: string,
  description: string,
  usage: string,
  example: string,
  aliases?: string[],
): CommandDef => ({ name, description, usage, example, aliases });

export const commandCategories: CommandCategory[] = [
  {
    slug: "moderation",
    name: "Moderation",
    description: "Ban, kick, mute, purge and everything else you need to keep order.",
    commands: [
      cmd("ban", "Permanently ban a member from the server.", ",ban [user]", ",ban @alex"),
      cmd("bc", "Quickly clear recent bot responses and command messages.", ",bc [amount]", ",bc 10"),
      cmd("c", "Shortcut to clear recent messages.", ",c [target]", ",c @alex"),
      cmd("case", "View a specific moderation case.", ",case [case id]", ",case value"),
      cmd("cases", "List moderation cases for a member.", ",cases [user]", ",cases @alex"),
      cmd("cleanup", "Clean up bot and command messages.", ",cleanup [amount]", ",cleanup 10"),
      cmd("clear", "Delete a number of recent messages.", ",clear [amount]", ",clear 10"),
      cmd("hardban", "Ban a user so they can't be unbanned normally.", ",hardban [user] [args]", ",hardban @alex value", ["hb"]),
      cmd("hide", "Hide a channel from members.", ",hide", ",hide"),
      cmd("history", "Show a member's moderation history.", ",history [user]", ",history @alex"),
      cmd("imute", "Mute a member from sending images.", ",imute [user]", ",imute @alex"),
      cmd("jail", "Move a member into jail.", ",jail [user]", ",jail @alex"),
      cmd("kick", "Kick a member from the server.", ",kick [user]", ",kick @alex"),
      cmd("lock", "Lock a channel.", ",lock [target]", ",lock @alex"),
      cmd("lockall", "Lock every channel in the server.", ",lockall", ",lockall"),
      cmd("lockdown", "Put the server into lockdown.", ",lockdown", ",lockdown"),
      cmd("modstats", "Show moderator activity stats.", ",modstats [member]", ",modstats @alex"),
      cmd("mute", "Mute a member so they can't chat.", ",mute [user]", ",mute @alex"),
      cmd("nick", "Change a member's nickname.", ",nick [user]", ",nick @alex"),
      cmd("note", "Add a staff note to a member.", ",note [member]", ",note @alex", ["n"]),
      cmd("note add", "Add a new entry to the note configuration.", ",note add [member]", ",note add @alex"),
      cmd("nsfw", "Manage NSFW channel settings.", ",nsfw", ",nsfw"),
      cmd("nsfw set", "Set the nsfw configuration.", ",nsfw set", ",nsfw set"),
      cmd("nuke", "Recreate a channel from scratch.", ",nuke", ",nuke"),
      cmd("purge", "Bulk delete messages.", ",purge [amount]", ",purge 10", ["pg"]),
      cmd("purge attachments", "Manage the attachments setting for purge.", ",purge attachments [amount]", ",purge attachments 10"),
      cmd("purge bots", "Manage the bots setting for purge.", ",purge bots [amount]", ",purge bots 10"),
      cmd("purge contains", "Manage the contains setting for purge.", ",purge contains", ",purge contains"),
      cmd("purge embeds", "Manage the embeds setting for purge.", ",purge embeds [amount]", ",purge embeds 10"),
      cmd("purge humans", "Manage the humans setting for purge.", ",purge humans [amount]", ",purge humans 10"),
      cmd("purge images", "Manage the images setting for purge.", ",purge images [amount]", ",purge images 10"),
      cmd("purge invites", "Manage the invites setting for purge.", ",purge invites [amount]", ",purge invites 10"),
      cmd("purge links", "Manage the links setting for purge.", ",purge links [amount]", ",purge links 10"),
      cmd("purge user", "Manage the user setting for purge.", ",purge user [member] [amount]", ",purge user @alex 10"),
      cmd("restore", "Restore a member's previous roles.", ",restore [user]", ",restore @alex"),
      cmd("rmute", "Run the rmute command.", ",rmute [user]", ",rmute @alex"),
      cmd("scam", "Manage scam link protection.", ",scam", ",scam", ["antiscam"]),
      cmd("scam action", "Manage the action setting for scam.", ",scam action [action]", ",scam action value"),
      cmd("scam off", "Manage the off setting for scam.", ",scam off", ",scam off"),
      cmd("scam on", "Manage the on setting for scam.", ",scam on", ",scam on"),
      cmd("scam status", "Manage the status setting for scam.", ",scam status", ",scam status"),
      cmd("scam timeout", "Manage the timeout setting for scam.", ",scam timeout [minutes]", ",scam timeout value"),
      cmd("scam whitelist", "Manage the whitelist setting for scam.", ",scam whitelist", ",scam whitelist"),
      cmd("sfw", "Mark a channel as safe for work.", ",sfw", ",sfw"),
      cmd("sfw set", "Set the sfw configuration.", ",sfw set", ",sfw set"),
      cmd("slowmode", "Set channel slowmode.", ",slowmode [seconds]", ",slowmode value"),
      cmd("softban", "Ban and unban to purge a member's messages.", ",softban [user]", ",softban @alex"),
      cmd("staffnote", "Add a private staff note.", ",staffnote", ",staffnote"),
      cmd("staffnote add", "Add a new entry to the staffnote configuration.", ",staffnote add [member]", ",staffnote add @alex"),
      cmd("staffnote clear", "Clear the staffnote configuration.", ",staffnote clear [member]", ",staffnote clear @alex"),
      cmd("staffnote remove", "Remove an entry from the staffnote configuration.", ",staffnote remove [member] [note id]", ",staffnote remove @alex value"),
      cmd("staffnotes", "View private staff notes.", ",staffnotes [member]", ",staffnotes @alex"),
      cmd("stripstaff", "Remove manageable roles that grant staff or dangerous permissions.", ",stripstaff [user]", ",stripstaff @alex", ["staffstrip"]),
      cmd("timeout", "Time a member out with Discord timeouts.", ",timeout [user] [duration]", ",timeout @alex 30m", ["to"]),
      cmd("unban", "Unban a user.", ",unban [user id]", ",unban value"),
      cmd("unhide", "Unhide a channel.", ",unhide", ",unhide"),
      cmd("unjail", "Release a member from jail.", ",unjail [user]", ",unjail @alex"),
      cmd("unlock", "Unlock a channel.", ",unlock", ",unlock"),
      cmd("unlockall", "Unlock every channel.", ",unlockall", ",unlockall"),
      cmd("unlockdown", "End the server lockdown.", ",unlockdown", ",unlockdown"),
      cmd("unmute", "Unmute a member.", ",unmute [user]", ",unmute @alex"),
      cmd("untimeout", "Remove a member's timeout.", ",untimeout [user]", ",untimeout @alex", ["unto", "uto"]),
      cmd("warn", "Warn a member.", ",warn [user]", ",warn @alex"),
      cmd("warnings", "List a member's warnings.", ",warnings [user]", ",warnings @alex"),
    ],
  },
  {
    slug: "security",
    name: "Security",
    description: "Verification, raid protection, quarantine and hardening tools.",
    commands: [
      cmd("backup", "Create or restore a server backup.", ",backup", ",backup", ["bk"]),
      cmd("backup create", "Create the backup configuration.", ",backup create", ",backup create"),
      cmd("backup delete", "Delete an entry from the backup configuration.", ",backup delete", ",backup delete"),
      cmd("backup list", "List all entries for the backup configuration.", ",backup list", ",backup list"),
      cmd("backup load", "Manage the load setting for backup.", ",backup load", ",backup load"),
      cmd("quarantine", "Quarantine a member instantly.", ",quarantine [member]", ",quarantine @alex", ["qtine", "qtn"]),
      cmd("raidmode", "Toggle raid mode protection.", ",raidmode", ",raidmode", ["raid", "rm"]),
      cmd("raidmode off", "Manage the off setting for raidmode.", ",raidmode off", ",raidmode off"),
      cmd("raidmode on", "Manage the on setting for raidmode.", ",raidmode on", ",raidmode on"),
      cmd("raidmode strict", "Manage the strict setting for raidmode.", ",raidmode strict", ",raidmode strict"),
      cmd("raidmode verify", "Manage the verify setting for raidmode.", ",raidmode verify", ",raidmode verify"),
      cmd("security", "Configure ware's security suite.", ",security", ",security", ["sec", "protection"]),
      cmd("security backup", "Manage the backup setting for security.", ",security backup [action]", ",security backup value"),
      cmd("security heat", "Manage the heat setting for security.", ",security heat [action]", ",security heat value"),
      cmd("security joingate", "Manage the joingate setting for security.", ",security joingate [action] [minimum hours] [punishment]", ",security joingate value value value"),
      cmd("security logs", "Manage the logs setting for security.", ",security logs [channel]", ",security logs #general"),
      cmd("security off", "Manage the off setting for security.", ",security off", ",security off"),
      cmd("security on", "Manage the on setting for security.", ",security on", ",security on"),
      cmd("security panic", "Manage the panic setting for security.", ",security panic", ",security panic"),
      cmd("security permit", "Manage the permit setting for security.", ",security permit [level] [member]", ",security permit value @alex"),
      cmd("security quarantine", "Manage the quarantine setting for security.", ",security quarantine [member]", ",security quarantine @alex"),
      cmd("security raid", "Manage the raid setting for security.", ",security raid [action] [joins] [seconds]", ",security raid value value value"),
      cmd("security recover", "Manage the recover setting for security.", ",security recover", ",security recover"),
      cmd("security release", "Manage the release setting for security.", ",security release [member]", ",security release @alex"),
      cmd("security score", "Manage the score setting for security.", ",security score", ",security score"),
      cmd("security setup", "Install and repair the complete Ware security configuration in one command.", ",security setup", ",security setup"),
      cmd("security status", "Manage the status setting for security.", ",security status", ",security status"),
      cmd("security whitelist", "Manage the whitelist setting for security.", ",security whitelist [target]", ",security whitelist @alex"),
      cmd("verify", "Configure member verification.", ",verify", ",verify", ["v"]),
      cmd("verify button", "Manage the button setting for verify.", ",verify button", ",verify button"),
      cmd("verify captcha", "Manage the captcha setting for verify.", ",verify captcha", ",verify captcha"),
      cmd("verify setup", "Set up the verify configuration.", ",verify setup [role]", ",verify setup @Staff"),
      cmd("whitelist", "Manage the security whitelist.", ",whitelist", ",whitelist", ["wl"]),
      cmd("whitelist add", "Add a new entry to the whitelist configuration.", ",whitelist add [member]", ",whitelist add @alex"),
      cmd("whitelist list", "List all entries for the whitelist configuration.", ",whitelist list", ",whitelist list"),
      cmd("whitelist remove", "Remove an entry from the whitelist configuration.", ",whitelist remove [member]", ",whitelist remove @alex"),
    ],
  },
  {
    slug: "anti",
    name: "Anti-Nuke",
    description: "Stop nukers, bots and mass destruction before it happens.",
    commands: [
      cmd("anti", "Configure anti-raid and anti-abuse protections.", ",anti", ",anti"),
      cmd("anti ad", "Manage the ad setting for anti.", ",anti ad [action]", ",anti ad value"),
      cmd("anti bot", "Manage the bot setting for anti.", ",anti bot", ",anti bot"),
      cmd("anti ghost", "Manage the ghost setting for anti.", ",anti ghost", ",anti ghost"),
      cmd("anti link", "Manage the link setting for anti.", ",anti link [action] [punishment]", ",anti link value value"),
      cmd("anti raid", "Manage the raid setting for anti.", ",anti raid [action] [value] [seconds]", ",anti raid value value value"),
      cmd("anti spam", "Manage the spam setting for anti.", ",anti spam [action] [punishment]", ",anti spam value value"),
      cmd("antinuke", "Configure anti-nuke protection for your server.", ",antinuke", ",antinuke", ["an"]),
      cmd("antinuke admin", "Manage the admin setting for antinuke.", ",antinuke admin [user]", ",antinuke admin @alex"),
      cmd("antinuke admins", "Manage the admins setting for antinuke.", ",antinuke admins", ",antinuke admins"),
      cmd("antinuke config", "Configure the antinuke configuration.", ",antinuke config", ",antinuke config"),
      cmd("antinuke disable", "Disable the antinuke configuration.", ",antinuke disable", ",antinuke disable"),
      cmd("antinuke enable", "Enable the antinuke configuration.", ",antinuke enable", ",antinuke enable"),
      cmd("antinuke list", "List all entries for the antinuke configuration.", ",antinuke list", ",antinuke list"),
      cmd("antinuke logs", "Manage the logs setting for antinuke.", ",antinuke logs", ",antinuke logs"),
      cmd("antinuke punishment", "Manage the punishment setting for antinuke.", ",antinuke punishment [punishment]", ",antinuke punishment value"),
      cmd("antinuke view", "View the antinuke configuration.", ",antinuke view", ",antinuke view"),
      cmd("antinuke whitelist", "Manage the whitelist setting for antinuke.", ",antinuke whitelist [user id]", ",antinuke whitelist value"),
    ],
  },
  {
    slug: "automod",
    name: "AutoMod & Filters",
    description: "Content filters, banned words, invite and link blocking.",
    commands: [
      cmd("automod", "Configure automatic moderation rules.", ",automod", ",automod", ["am"]),
      cmd("automod blacklist", "Manage the blacklist setting for automod.", ",automod blacklist", ",automod blacklist"),
      cmd("automod config", "Configure the automod configuration.", ",automod config", ",automod config"),
      cmd("automod disable", "Disable the automod configuration.", ",automod disable", ",automod disable"),
      cmd("automod enable", "Enable the automod configuration.", ",automod enable", ",automod enable"),
      cmd("automod setup", "Set up the automod configuration.", ",automod setup", ",automod setup"),
      cmd("automod whitelist", "Manage the whitelist setting for automod.", ",automod whitelist", ",automod whitelist"),
      cmd("filter", "Manage the word filter.", ",filter", ",filter", ["f"]),
      cmd("filter add", "Add a new entry to the filter configuration.", ",filter add", ",filter add"),
      cmd("filter links", "Enable Ware's two-strike link filter with `filter links on`.", ",filter links [action]", ",filter links value"),
      cmd("filter list", "List all entries for the filter configuration.", ",filter list", ",filter list"),
      cmd("filter remove", "Remove an entry from the filter configuration.", ",filter remove", ",filter remove"),
    ],
  },
  {
    slug: "voicemaster",
    name: "VoiceMaster",
    description: "Temporary voice channels members fully control.",
    commands: [
      cmd("voicemaster", "Configure temporary voice channels.", ",voicemaster", ",voicemaster", ["vm", "vc"]),
      cmd("voicemaster activity", "Manage the activity setting for voicemaster.", ",voicemaster activity", ",voicemaster activity"),
      cmd("voicemaster bitrate", "Manage the bitrate setting for voicemaster.", ",voicemaster bitrate [bitrate]", ",voicemaster bitrate value"),
      cmd("voicemaster claim", "Manage the claim setting for voicemaster.", ",voicemaster claim", ",voicemaster claim"),
      cmd("voicemaster configuration", "Manage the configuration setting for voicemaster.", ",voicemaster configuration", ",voicemaster configuration"),
      cmd("voicemaster create", "Create the VoiceMaster category, join channel, and Ware Interface.", ",voicemaster create", ",voicemaster create"),
      cmd("voicemaster disconnect", "Manage the disconnect setting for voicemaster.", ",voicemaster disconnect [member]", ",voicemaster disconnect @alex"),
      cmd("voicemaster ghost", "Manage the ghost setting for voicemaster.", ",voicemaster ghost", ",voicemaster ghost"),
      cmd("voicemaster invite", "Manage the invite setting for voicemaster.", ",voicemaster invite [member]", ",voicemaster invite @alex"),
      cmd("voicemaster kick", "Manage the kick setting for voicemaster.", ",voicemaster kick [member]", ",voicemaster kick @alex"),
      cmd("voicemaster limit", "Manage the limit setting for voicemaster.", ",voicemaster limit [limit]", ",voicemaster limit value"),
      cmd("voicemaster lock", "Manage the lock setting for voicemaster.", ",voicemaster lock", ",voicemaster lock"),
      cmd("voicemaster move", "Manage the move setting for voicemaster.", ",voicemaster move [member]", ",voicemaster move @alex"),
      cmd("voicemaster mute", "Manage the mute setting for voicemaster.", ",voicemaster mute [member]", ",voicemaster mute @alex"),
      cmd("voicemaster name", "Manage the name setting for voicemaster.", ",voicemaster name", ",voicemaster name"),
      cmd("voicemaster owner", "Manage the owner setting for voicemaster.", ",voicemaster owner", ",voicemaster owner"),
      cmd("voicemaster permit", "Manage the permit setting for voicemaster.", ",voicemaster permit [member]", ",voicemaster permit @alex"),
      cmd("voicemaster permitall", "Manage the permitall setting for voicemaster.", ",voicemaster permitall", ",voicemaster permitall"),
      cmd("voicemaster permitrole", "Manage the permitrole setting for voicemaster.", ",voicemaster permitrole [role]", ",voicemaster permitrole @Staff"),
      cmd("voicemaster pin", "Manage the pin setting for voicemaster.", ",voicemaster pin", ",voicemaster pin"),
      cmd("voicemaster private", "Manage the private setting for voicemaster.", ",voicemaster private", ",voicemaster private"),
      cmd("voicemaster public", "Manage the public setting for voicemaster.", ",voicemaster public", ",voicemaster public"),
      cmd("voicemaster reject", "Manage the reject setting for voicemaster.", ",voicemaster reject [member]", ",voicemaster reject @alex"),
      cmd("voicemaster rejectall", "Manage the rejectall setting for voicemaster.", ",voicemaster rejectall", ",voicemaster rejectall"),
      cmd("voicemaster rejectrole", "Manage the rejectrole setting for voicemaster.", ",voicemaster rejectrole [role]", ",voicemaster rejectrole @Staff"),
      cmd("voicemaster reset", "Remove VoiceMaster and clear its saved configuration without recreating it.", ",voicemaster reset", ",voicemaster reset"),
      cmd("voicemaster rtc", "Manage the rtc setting for voicemaster.", ",voicemaster rtc", ",voicemaster rtc"),
      cmd("voicemaster status", "Manage the status setting for voicemaster.", ",voicemaster status", ",voicemaster status"),
      cmd("voicemaster sync", "Manage the sync setting for voicemaster.", ",voicemaster sync", ",voicemaster sync"),
      cmd("voicemaster transfer", "Manage the transfer setting for voicemaster.", ",voicemaster transfer [member]", ",voicemaster transfer @alex"),
      cmd("voicemaster trust", "Manage the trust setting for voicemaster.", ",voicemaster trust [member]", ",voicemaster trust @alex"),
      cmd("voicemaster unghost", "Manage the unghost setting for voicemaster.", ",voicemaster unghost", ",voicemaster unghost"),
      cmd("voicemaster unlock", "Manage the unlock setting for voicemaster.", ",voicemaster unlock", ",voicemaster unlock"),
      cmd("voicemaster unmute", "Manage the unmute setting for voicemaster.", ",voicemaster unmute [member]", ",voicemaster unmute @alex"),
      cmd("voicemaster untrust", "Manage the untrust setting for voicemaster.", ",voicemaster untrust [member]", ",voicemaster untrust @alex"),
    ],
  },
  {
    slug: "tickets",
    name: "Tickets",
    description: "Support ticket panels, claims, transcripts and staff tools.",
    commands: [
      cmd("ticket", "Manage the ticket system.", ",ticket", ",ticket", ["t"]),
      cmd("ticket add", "Add a new entry to the ticket configuration.", ",ticket add [member]", ",ticket add @alex"),
      cmd("ticket archive", "Manage the archive setting for ticket.", ",ticket archive", ",ticket archive"),
      cmd("ticket blacklist", "Manage the blacklist setting for ticket.", ",ticket blacklist [member]", ",ticket blacklist @alex"),
      cmd("ticket claim", "Manage the claim setting for ticket.", ",ticket claim", ",ticket claim"),
      cmd("ticket close", "Manage the close setting for ticket.", ",ticket close", ",ticket close"),
      cmd("ticket closeall", "Manage the closeall setting for ticket.", ",ticket closeall", ",ticket closeall"),
      cmd("ticket delete", "Delete an entry from the ticket configuration.", ",ticket delete [delay]", ",ticket delete value"),
      cmd("ticket export", "Manage the export setting for ticket.", ",ticket export", ",ticket export"),
      cmd("ticket info", "Show information about the ticket configuration.", ",ticket info", ",ticket info"),
      cmd("ticket merge", "Manage the merge setting for ticket.", ",ticket merge", ",ticket merge"),
      cmd("ticket move", "Manage the move setting for ticket.", ",ticket move", ",ticket move"),
      cmd("ticket panel", "Manage the panel setting for ticket.", ",ticket panel", ",ticket panel"),
      cmd("ticket priority", "Manage the priority setting for ticket.", ",ticket priority [level]", ",ticket priority value"),
      cmd("ticket reason", "Manage the reason setting for ticket.", ",ticket reason", ",ticket reason"),
      cmd("ticket remove", "Remove an entry from the ticket configuration.", ",ticket remove [member]", ",ticket remove @alex"),
      cmd("ticket rename", "Manage the rename setting for ticket.", ",ticket rename", ",ticket rename"),
      cmd("ticket reopen", "Manage the reopen setting for ticket.", ",ticket reopen", ",ticket reopen"),
      cmd("ticket setup", "Set up the ticket configuration.", ",ticket setup [staff role]", ",ticket setup value"),
      cmd("ticket split", "Manage the split setting for ticket.", ",ticket split", ",ticket split"),
      cmd("ticket transcript", "Manage the transcript setting for ticket.", ",ticket transcript", ",ticket transcript"),
      cmd("ticket unclaim", "Manage the unclaim setting for ticket.", ",ticket unclaim", ",ticket unclaim"),
    ],
  },
  {
    slug: "logging",
    name: "Logging",
    description: "Audit every action in your server with detailed logs.",
    commands: [
      cmd("2048", "Play a game of 2048 in chat.", ",2048", ",2048"),
      cmd("activities", "Start a Discord voice activity.", ",activities [member]", ",activities @alex", ["activity"]),
      cmd("audit", "View recent audit log entries.", ",audit [limit]", ",audit value"),
      cmd("battleship", "Play battleship against another member.", ",battleship [member]", ",battleship @alex", ["bs"]),
      cmd("bio", "View or set your profile bio.", ",bio [member]", ",bio @alex"),
      cmd("channel archive", "Manage the archive setting for channel.", ",channel archive [channel]", ",channel archive #general"),
      cmd("channel copy", "Manage the copy setting for channel.", ",channel copy [channel]", ",channel copy #general"),
      cmd("channel export", "Manage the export setting for channel.", ",channel export", ",channel export"),
      cmd("channel import", "Manage the import setting for channel.", ",channel import", ",channel import"),
      cmd("channel lock", "Manage the lock setting for channel.", ",channel lock [channel]", ",channel lock #general"),
      cmd("channel permissions", "Manage the permissions setting for channel.", ",channel permissions [channel]", ",channel permissions #general"),
      cmd("channel slowmode", "Manage the slowmode setting for channel.", ",channel slowmode [seconds] [channel]", ",channel slowmode value #general"),
      cmd("channel sync", "Manage the sync setting for channel.", ",channel sync [channel]", ",channel sync #general"),
      cmd("channel unlock", "Manage the unlock setting for channel.", ",channel unlock [channel]", ",channel unlock #general"),
      cmd("checkers", "Play checkers with a member.", ",checkers [member]", ",checkers @alex"),
      cmd("chess", "Play chess with a member.", ",chess [member]", ",chess @alex"),
      cmd("cloneuser", "Copy another user's nickname and roles style.", ",cloneuser [source] [target]", ",cloneuser value @alex", ["copyuser"]),
      cmd("count", "Show the counting channel progress.", ",count", ",count"),
      cmd("countdown", "Start a countdown timer.", ",countdown [seconds]", ",countdown value"),
      cmd("devices", "Show which devices a member is online from.", ",devices [member]", ",devices @alex"),
      cmd("disconnectall", "Disconnect everyone from a voice channel.", ",disconnectall", ",disconnectall", ["vdcall"]),
      cmd("duel", "Duel another member.", ",duel [member] [amount]", ",duel @alex 10"),
      cmd("execute", "Run a sandboxed snippet.", ",execute", ",execute"),
      cmd("force_role", "Force a role onto a member.", ",force_role [member] [role]", ",force_role @alex @Staff"),
      cmd("forceavatar", "Force a member's avatar override.", ",forceavatar [member]", ",forceavatar @alex"),
      cmd("forcerole", "Force a role onto a member.", ",forcerole [member] [role]", ",forcerole @alex @Staff", ["fr"]),
      cmd("forcetimeout", "Force a timeout on a member.", ",forcetimeout [member] [duration]", ",forcetimeout @alex 30m"),
      cmd("impersonate", "Send a message as another member via webhook.", ",impersonate [member]", ",impersonate @alex"),
      cmd("interest", "Collect bank interest.", ",interest", ",interest"),
      cmd("log", "Configure logging channels.", ",log", ",log", ["lg"]),
      cmd("log channel", "Manage the channel setting for log.", ",log channel [channel]", ",log channel #general"),
      cmd("log disable", "Disable the log configuration.", ",log disable [event]", ",log disable value"),
      cmd("log enable", "Enable the log configuration.", ",log enable [event]", ",log enable value"),
      cmd("log events", "Manage the events setting for log.", ",log events", ",log events"),
      cmd("logs", "Manage logging settings.", ",logs", ",logs", ["logging"]),
      cmd("logs add", "Add a new entry to the logs configuration.", ",logs add [channel]", ",logs add #general"),
      cmd("logs channel", "Manage the channel setting for logs.", ",logs channel [channel]", ",logs channel #general"),
      cmd("logs disable", "Disable the logs configuration.", ",logs disable [event]", ",logs disable value"),
      cmd("logs enable", "Enable the logs configuration.", ",logs enable [event]", ",logs enable value"),
      cmd("logs events", "Manage the events setting for logs.", ",logs events", ",logs events"),
      cmd("market", "Browse the item market.", ",market", ",market"),
      cmd("massdisconnect", "Disconnect all members from voice.", ",massdisconnect", ",massdisconnect"),
      cmd("masskick", "Kick multiple members at once.", ",masskick", ",masskick"),
      cmd("massmove", "Move all members to another voice channel.", ",massmove [channel]", ",massmove #general"),
      cmd("massnick", "Change nicknames in bulk.", ",massnick", ",massnick"),
      cmd("massrename", "Rename channels or emojis in bulk.", ",massrename", ",massrename"),
      cmd("massunmute", "Unmute everyone at once.", ",massunmute", ",massunmute"),
      cmd("massuntimeout", "Remove timeouts from everyone.", ",massuntimeout", ",massuntimeout"),
      cmd("modlog", "Set the moderation log channel.", ",modlog [channel]", ",modlog #general"),
      cmd("moveall", "Move everyone to another voice channel.", ",moveall [channel]", ",moveall #general", ["vamove"]),
      cmd("mutuals", "Show servers you share with a member.", ",mutuals [member]", ",mutuals @alex"),
      cmd("poker", "Play poker.", ",poker", ",poker"),
      cmd("purgeafter", "Delete messages after a given message.", ",purgeafter [message id] [amount]", ",purgeafter value 10"),
      cmd("purgebefore", "Delete messages before a given message.", ",purgebefore [message id] [amount]", ",purgebefore value 10"),
      cmd("purgebots", "Delete messages from bots.", ",purgebots [amount]", ",purgebots 10", ["clearbots"]),
      cmd("purgeembeds", "Delete messages containing embeds.", ",purgeembeds [amount]", ",purgeembeds 10"),
      cmd("purgefiles", "Delete messages with file attachments.", ",purgefiles [amount]", ",purgefiles 10"),
      cmd("purgehumans", "Delete messages from humans.", ",purgehumans [amount]", ",purgehumans 10", ["clearhumans"]),
      cmd("purgeimages", "Delete messages containing images.", ",purgeimages [amount]", ",purgeimages 10", ["clearimages"]),
      cmd("purgeinvites", "Delete messages containing invites.", ",purgeinvites [amount]", ",purgeinvites 10", ["clearinvites"]),
      cmd("purgelinks", "Delete messages containing links.", ",purgelinks [amount]", ",purgelinks 10", ["clearlinks"]),
      cmd("purgenitro", "Delete messages with nitro emojis.", ",purgenitro [amount]", ",purgenitro 10"),
      cmd("purgerange", "Delete messages between two messages.", ",purgerange [start id] [end id]", ",purgerange value value"),
      cmd("purgereactions", "Remove reactions from messages.", ",purgereactions [amount]", ",purgereactions 10"),
      cmd("purgeuser", "Delete messages from a specific member.", ",purgeuser [member] [amount]", ",purgeuser @alex 10"),
      cmd("sell", "Sell an item for currency.", ",sell", ",sell"),
      cmd("servervanity", "Show the server vanity URL.", ",servervanity", ",servervanity", ["guildvanity"]),
      cmd("stealrole", "Copy a role from another server.", ",stealrole [source] [target]", ",stealrole value @alex", ["copyroles"]),
      cmd("sudo", "Run a command as another member.", ",sudo [member]", ",sudo @alex"),
      cmd("timestamp", "Generate a Discord timestamp.", ",timestamp [unix]", ",timestamp value", ["ts"]),
      cmd("trade", "Trade items with another member.", ",trade [member]", ",trade @alex"),
    ],
  },
  {
    slug: "welcome",
    name: "Welcome & Config",
    description: "Welcome, goodbye, boost messages, autoroles and server setup.",
    commands: [
      cmd("autorole", "Give roles automatically when members join.", ",autorole [role]", ",autorole @Staff", ["ar", "autoroles"]),
      cmd("autorole add", "Add a new entry to the autorole configuration.", ",autorole add [role]", ",autorole add @Staff"),
      cmd("autorole list", "List all entries for the autorole configuration.", ",autorole list", ",autorole list"),
      cmd("autorole remove", "Remove an entry from the autorole configuration.", ",autorole remove", ",autorole remove"),
      cmd("autorole reset", "Reset the autorole configuration.", ",autorole reset", ",autorole reset"),
      cmd("autorole view", "View the autorole configuration.", ",autorole view", ",autorole view"),
      cmd("prefix", "Show/change server prefix, or set a personal prefix across all servers.", ",prefix [action]", ",prefix value"),
      cmd("settings", "View the current settings for vanity rewards.", ",settings <interaction>", ",settings value"),
      cmd("setup", "Run the ware setup wizard.", ",setup", ",setup"),
      cmd("stats", "Show ware statistics.", ",stats", ",stats", ["shards", "latency"]),
      cmd("welcome", "Configure welcome messages.", ",welcome", ",welcome", ["welc"]),
      cmd("welcome channel", "Manage the channel setting for welcome.", ",welcome channel [channel]", ",welcome channel #general"),
      cmd("welcome dm", "Manage the dm setting for welcome.", ",welcome dm", ",welcome dm"),
      cmd("welcome embed", "Manage the embed setting for welcome.", ",welcome embed [state]", ",welcome embed value"),
      cmd("welcome message", "Manage the message setting for welcome.", ",welcome message", ",welcome message"),
      cmd("welcome reset", "Reset the welcome configuration.", ",welcome reset", ",welcome reset"),
      cmd("welcome role", "Manage the role setting for welcome.", ",welcome role [role]", ",welcome role @Staff"),
      cmd("welcome setup", "Set up the welcome configuration.", ",welcome setup [channel]", ",welcome setup #general"),
      cmd("welcome test", "Manage the test setting for welcome.", ",welcome test", ",welcome test"),
      cmd("welcome view", "View the welcome configuration.", ",welcome view", ",welcome view"),
    ],
  },
  {
    slug: "roles",
    name: "Roles",
    description: "Role management, reaction roles, buttons and self roles.",
    commands: [
      cmd("bots", "List every bot in the server.", ",bots", ",bots"),
      cmd("buttonrole", "Set up button roles.", ",buttonrole", ",buttonrole"),
      cmd("buttonrole add", "Add a new entry to the buttonrole configuration.", ",buttonrole add [message link] [role] [style] [emoji]", ",buttonrole add value @Staff value value"),
      cmd("buttonrole list", "List all entries for the buttonrole configuration.", ",buttonrole list", ",buttonrole list"),
      cmd("buttonrole remove", "Remove an entry from the buttonrole configuration.", ",buttonrole remove [message link] [index]", ",buttonrole remove value value"),
      cmd("buttonrole removeall", "Manage the removeall setting for buttonrole.", ",buttonrole removeall [message link]", ",buttonrole removeall value"),
      cmd("buttonrole reset", "Reset the buttonrole configuration.", ",buttonrole reset", ",buttonrole reset"),
      cmd("humans", "Show the human member count.", ",humans", ",humans"),
      cmd("icon remove", "Remove an entry from the icon configuration.", ",icon remove", ",icon remove"),
      cmd("inrole", "List members with a role.", ",inrole", ",inrole"),
      cmd("massrole", "Add or remove a role from everyone.", ",massrole [role]", ",massrole @Staff"),
      cmd("reactionrole", "Set up reaction roles.", ",reactionrole", ",reactionrole", ["rr"]),
      cmd("reactionrole add", "Add a new entry to the reactionrole configuration.", ",reactionrole add [message link] [reaction] [role]", ",reactionrole add value value @Staff"),
      cmd("reactionrole list", "List all entries for the reactionrole configuration.", ",reactionrole list", ",reactionrole list"),
      cmd("reactionrole remove", "Remove an entry from the reactionrole configuration.", ",reactionrole remove [message link] [reaction]", ",reactionrole remove value value"),
      cmd("reactionrole removeall", "Manage the removeall setting for reactionrole.", ",reactionrole removeall [message link]", ",reactionrole removeall value"),
      cmd("reactionrole reset", "Reset the reactionrole configuration.", ",reactionrole reset", ",reactionrole reset"),
      cmd("reactionrole restore", "Manage the restore setting for reactionrole.", ",reactionrole restore [option]", ",reactionrole restore value"),
      cmd("role", "Manage roles and role assignments.", ",role", ",role", ["r"]),
      cmd("role bots", "Manage the bots setting for role.", ",role bots [role]", ",role bots @Staff"),
      cmd("role color", "Manage the color setting for role.", ",role color [role] [color]", ",role color @Staff value"),
      cmd("role create", "Create the role configuration.", ",role create", ",role create"),
      cmd("role delete", "Delete an entry from the role configuration.", ",role delete", ",role delete"),
      cmd("role duplicate", "Manage the duplicate setting for role.", ",role duplicate [role]", ",role duplicate @Staff"),
      cmd("role everyone", "Manage the everyone setting for role.", ",role everyone", ",role everyone"),
      cmd("role export", "Manage the export setting for role.", ",role export", ",role export"),
      cmd("role hoist", "Manage the hoist setting for role.", ",role hoist [role] [state]", ",role hoist @Staff value"),
      cmd("role humans", "Manage the humans setting for role.", ",role humans [role]", ",role humans @Staff"),
      cmd("role icon", "Manage the icon setting for role.", ",role icon [role]", ",role icon @Staff"),
      cmd("role import", "Manage the import setting for role.", ",role import", ",role import"),
      cmd("role info", "Show information about the role configuration.", ",role info", ",role info"),
      cmd("role invc", "Manage the invc setting for role.", ",role invc [role]", ",role invc @Staff"),
      cmd("role members", "Manage the members setting for role.", ",role members", ",role members"),
      cmd("role mentionable", "Manage the mentionable setting for role.", ",role mentionable [role] [state]", ",role mentionable @Staff value"),
      cmd("role position", "Manage the position setting for role.", ",role position [role] [position]", ",role position @Staff value"),
      cmd("role random", "Manage the random setting for role.", ",role random [role] [amount]", ",role random @Staff 10"),
      cmd("role rename", "Manage the rename setting for role.", ",role rename [role]", ",role rename @Staff"),
      cmd("role restore", "Restore roles stripped within the previous hour.", ",role restore [user reference]", ",role restore value"),
      cmd("roleall", "Give a role to everyone.", ",roleall [role]", ",roleall @Staff"),
      cmd("rolebots", "Give a role to all bots.", ",rolebots [role]", ",rolebots @Staff"),
      cmd("rolehumans", "Give a role to all humans.", ",rolehumans [role]", ",rolehumans @Staff"),
      cmd("roles", "List all server roles.", ",roles", ",roles", ["userroles", "rolelist", "memberroles"]),
      cmd("selfrole", "Set up self-assignable roles.", ",selfrole", ",selfrole", ["selfroles", "sr"]),
      cmd("selfrole add", "Add a new entry to the selfrole configuration.", ",selfrole add [panel id] [role]", ",selfrole add value @Staff"),
      cmd("selfrole create", "Create the selfrole configuration.", ",selfrole create [panel id]", ",selfrole create value"),
      cmd("selfrole delete", "Delete an entry from the selfrole configuration.", ",selfrole delete [panel id]", ",selfrole delete value"),
      cmd("selfrole description", "Manage the description setting for selfrole.", ",selfrole description [panel id]", ",selfrole description value"),
      cmd("selfrole list", "List all entries for the selfrole configuration.", ",selfrole list", ",selfrole list"),
      cmd("selfrole max", "Manage the max setting for selfrole.", ",selfrole max [panel id] [amount]", ",selfrole max value 10"),
      cmd("selfrole remove", "Remove an entry from the selfrole configuration.", ",selfrole remove [panel id] [role]", ",selfrole remove value @Staff"),
      cmd("selfrole send", "Manage the send setting for selfrole.", ",selfrole send [panel id] [channel]", ",selfrole send value #general"),
      cmd("unroleall", "Remove a role from everyone.", ",unroleall [role]", ",unroleall @Staff"),
    ],
  },
  {
    slug: "booster",
    name: "Booster & Vanity",
    description: "Reward boosters and vanity status users automatically.",
    commands: [
      cmd("boosterrole", "Create or manage personal booster roles.", ",boosterrole [color] [second color]", ",boosterrole value value", ["br"]),
      cmd("boosterrole award", "Manage the award setting for boosterrole.", ",boosterrole award [role]", ",boosterrole award @Staff"),
      cmd("boosterrole base", "Manage the base setting for boosterrole.", ",boosterrole base [role]", ",boosterrole base @Staff"),
      cmd("boosterrole cleanup", "Manage the cleanup setting for boosterrole.", ",boosterrole cleanup", ",boosterrole cleanup"),
      cmd("boosterrole color", "Manage the color setting for boosterrole.", ",boosterrole color [color] [second color]", ",boosterrole color value value"),
      cmd("boosterrole create", "Create at most one personal booster role per member.", ",boosterrole create", ",boosterrole create"),
      cmd("boosterrole dominant", "Manage the dominant setting for boosterrole.", ",boosterrole dominant", ",boosterrole dominant"),
      cmd("boosterrole filter", "Manage the filter setting for boosterrole.", ",boosterrole filter", ",boosterrole filter"),
      cmd("boosterrole icon", "Manage the icon setting for boosterrole.", ",boosterrole icon", ",boosterrole icon"),
      cmd("boosterrole limit", "Manage the limit setting for boosterrole.", ",boosterrole limit [amount]", ",boosterrole limit 10"),
      cmd("boosterrole link", "Manage the link setting for boosterrole.", ",boosterrole link [role]", ",boosterrole link @Staff"),
      cmd("boosterrole list", "List all entries for the boosterrole configuration.", ",boosterrole list", ",boosterrole list"),
      cmd("boosterrole random", "Manage the random setting for boosterrole.", ",boosterrole random", ",boosterrole random"),
      cmd("boosterrole remove", "Remove an entry from the boosterrole configuration.", ",boosterrole remove", ",boosterrole remove"),
      cmd("boosterrole rename", "Manage the rename setting for boosterrole.", ",boosterrole rename", ",boosterrole rename"),
      cmd("boosterrole share", "Manage the share setting for boosterrole.", ",boosterrole share [member]", ",boosterrole share @alex"),
      cmd("rewards add", "Add a new entry to the rewards configuration.", ",rewards add [role]", ",rewards add @Staff"),
      cmd("rewards clear", "Clear the rewards configuration.", ",rewards clear", ",rewards clear"),
      cmd("rewards list", "List all entries for the rewards configuration.", ",rewards list", ",rewards list"),
      cmd("rewards remove", "Remove an entry from the rewards configuration.", ",rewards remove", ",rewards remove"),
      cmd("vanity", "Configure vanity status rewards.", ",vanity", ",vanity", ["vanitystatus", "vanityreward"]),
      cmd("vanity channel", "Manage the channel setting for vanity.", ",vanity channel [channel]", ",vanity channel #general"),
      cmd("vanity disable", "Disable the vanity configuration.", ",vanity disable", ",vanity disable"),
      cmd("vanity message", "Manage the message setting for vanity.", ",vanity message", ",vanity message"),
      cmd("vanity rewards", "Manage the rewards setting for vanity.", ",vanity rewards", ",vanity rewards"),
      cmd("vanity scan", "Manage the scan setting for vanity.", ",vanity scan", ",vanity scan"),
      cmd("vanity set", "Set the vanity configuration.", ",vanity set", ",vanity set"),
      cmd("vanity syncslash", "Manage the syncslash setting for vanity.", ",vanity syncslash", ",vanity syncslash"),
      cmd("vanity test", "Manage the test setting for vanity.", ",vanity test [member]", ",vanity test @alex"),
    ],
  },
  {
    slug: "levels",
    name: "Levels & Leaderboards",
    description: "XP, ranks, level rewards and leaderboards.",
    commands: [
      cmd("leaderboards", "View server leaderboards.", ",leaderboards", ",leaderboards", ["lbs"]),
      cmd("leaderboards economy", "Manage the economy setting for leaderboards.", ",leaderboards economy", ",leaderboards economy"),
      cmd("leaderboards invites", "Manage the invites setting for leaderboards.", ",leaderboards invites", ",leaderboards invites"),
      cmd("leaderboards levels", "Manage the levels setting for leaderboards.", ",leaderboards levels", ",leaderboards levels"),
      cmd("leaderboards messages", "Manage the messages setting for leaderboards.", ",leaderboards messages", ",leaderboards messages"),
      cmd("leaderboards voice", "Manage the voice setting for leaderboards.", ",leaderboards voice", ",leaderboards voice"),
      cmd("rank", "Show your level and rank card.", ",rank [user]", ",rank @alex", ["level"]),
      cmd("xp", "Manage member XP.", ",xp [member]", ",xp @alex"),
    ],
  },
  {
    slug: "economy",
    name: "Economy",
    description: "Currency, gambling, work, shop and everything money.",
    commands: [
      cmd("aura", "Check a member's aura score.", ",aura [user]", ",aura @alex"),
      cmd("award unset", "Manage the unset setting for award.", ",award unset", ",award unset"),
      cmd("award view", "View the award configuration.", ",award view", ",award view"),
      cmd("balance", "Check your or another member's balance.", ",balance [user]", ",balance @alex", ["bal"]),
      cmd("bank", "View and manage your bank account.", ",bank", ",bank"),
      cmd("beg", "Beg for a small amount of currency.", ",beg", ",beg"),
      cmd("birthday", "Set and track member birthdays.", ",birthday [member]", ",birthday @alex", ["bday"]),
      cmd("birthday channel", "Manage the channel setting for birthday.", ",birthday channel [channel]", ",birthday channel #general"),
      cmd("birthday list", "List all entries for the birthday configuration.", ",birthday list", ",birthday list"),
      cmd("birthday remove", "Remove an entry from the birthday configuration.", ",birthday remove", ",birthday remove"),
      cmd("birthday role", "Manage the role setting for birthday.", ",birthday role [role]", ",birthday role @Staff"),
      cmd("birthday set", "Set the birthday configuration.", ",birthday set", ",birthday set"),
      cmd("birthday test", "Manage the test setting for birthday.", ",birthday test [member]", ",birthday test @alex"),
      cmd("birthday today", "Manage the today setting for birthday.", ",birthday today", ",birthday today"),
      cmd("birthday toggle", "Toggle the birthday configuration.", ",birthday toggle", ",birthday toggle"),
      cmd("bitches", "Joke command that rates your popularity.", ",bitches [user]", ",bitches @alex"),
      cmd("blackjack", "Play blackjack with your balance.", ",blackjack [amount]", ",blackjack 10", ["bj"]),
      cmd("boostcount", "Show the server's boost count.", ",boostcount", ",boostcount"),
      cmd("boosters", "List everyone boosting the server.", ",boosters", ",boosters"),
      cmd("boostmessage", "Set the message sent when someone boosts.", ",boostmessage", ",boostmessage"),
      cmd("braincells", "Joke command that counts your braincells.", ",braincells [user]", ",braincells @alex"),
      cmd("buy", "Buy an item from the shop.", ",buy [item]", ",buy value"),
      cmd("challenge", "Challenge a member to a game.", ",challenge", ",challenge"),
      cmd("choose", "Pick randomly between options.", ",choose", ",choose"),
      cmd("clown", "Joke command that rates how much of a clown you are.", ",clown [user]", ",clown @alex"),
      cmd("code", "Format or run a code snippet.", ",code", ",code"),
      cmd("coin", "Flip a coin.", ",coin", ",coin"),
      cmd("coinflip", "Flip a coin, optionally for currency.", ",coinflip [bet] [side]", ",coinflip value value", ["cf"]),
      cmd("continue", "Continue the last AI response.", ",continue", ",continue"),
      cmd("cook", "Joke cooking command.", ",cook [user]", ",cook @alex"),
      cmd("crash", "Play the crash gambling game.", ",crash [amount]", ",crash 10"),
      cmd("crime", "Commit a crime for currency.", ",crime", ",crime"),
      cmd("daily", "Claim your daily reward.", ",daily", ",daily"),
      cmd("dashboard", "Get a link to the web dashboard.", ",dashboard", ",dashboard", ["dash"]),
      cmd("define", "Look up a dictionary definition.", ",define", ",define"),
      cmd("delulu", "Joke command that rates how delusional you are.", ",delulu [user]", ",delulu @alex"),
      cmd("deposit", "Deposit currency into your bank.", ",deposit [amount]", ",deposit 10", ["dep"]),
      cmd("dice", "Roll dice.", ",dice", ",dice"),
      cmd("dih", "Joke command.", ",dih [user]", ",dih @alex"),
      cmd("economy", "Manage the server's economy settings.", ",economy [member]", ",economy @alex", ["eco"]),
      cmd("economy buy", "Manage the buy setting for economy.", ",economy buy [item]", ",economy buy value"),
      cmd("economy daily", "Manage the daily setting for economy.", ",economy daily", ",economy daily"),
      cmd("economy shop", "Manage the shop setting for economy.", ",economy shop", ",economy shop"),
      cmd("economy work", "Manage the work setting for economy.", ",economy work", ",economy work"),
      cmd("essay", "Generate an essay with AI.", ",essay", ",essay"),
      cmd("explain", "Explain something with AI.", ",explain", ",explain"),
      cmd("gay", "Joke rating command.", ",gay [user]", ",gay @alex"),
      cmd("imagerestore", "Restore and enhance an image.", ",imagerestore", ",imagerestore"),
      cmd("inventory", "Show your item inventory.", ",inventory [member]", ",inventory @alex", ["inv"]),
      cmd("lesbian", "Joke rating command.", ",lesbian [user]", ",lesbian @alex"),
      cmd("lottery", "Buy a lottery ticket.", ",lottery", ",lottery", ["lotto"]),
      cmd("luck", "Test your luck.", ",luck [user]", ",luck @alex"),
      cmd("memorygame", "Play a memory game.", ",memorygame", ",memorygame"),
      cmd("mines", "Run the mines command.", ",mines [amount] [bombs]", ",mines 10 value", ["minesweeper"]),
      cmd("npc", "Joke command.", ",npc [user]", ",npc @alex"),
      cmd("pay", "Pay currency to another member.", ",pay [user] [amount]", ",pay @alex 10", ["transfer"]),
      cmd("poll", "Create a poll.", ",poll", ",poll"),
      cmd("profile", "Show your ware profile.", ",profile [member]", ",profile @alex"),
      cmd("quote", "Create a quote image from supplied text or the message being replied to.", ",quote", ",quote"),
      cmd("removebg", "Remove the background from an image.", ",removebg", ",removebg"),
      cmd("review", "Leave a review for ware.", ",review", ",review"),
      cmd("rizz", "Joke rating command.", ",rizz [user]", ",rizz @alex"),
      cmd("roast", "Roast a member.", ",roast [user]", ",roast @alex"),
      cmd("roleplay", "Send a roleplay action.", ",roleplay [option]", ",roleplay value"),
      cmd("roulette", "Play roulette.", ",roulette [amount] [choice]", ",roulette 10 value"),
      cmd("scramble", "Play the word scramble game.", ",scramble", ",scramble", ["scramblemedia"]),
      cmd("shop", "Browse the item shop.", ",shop", ",shop"),
      cmd("sigma", "Joke rating command.", ",sigma [user]", ",sigma @alex"),
      cmd("simp", "Joke rating command.", ",simp [user]", ",simp @alex"),
      cmd("slots", "Play the slot machine.", ",slots [amount]", ",slots 10"),
      cmd("steal", "Steal an emoji or sticker.", ",steal [message link]", ",steal value"),
      cmd("touchgrass", "Joke command telling someone to touch grass.", ",touchgrass [user]", ",touchgrass @alex"),
      cmd("upscale", "Upscale an image.", ",upscale", ",upscale"),
      cmd("virgin", "Joke rating command.", ",virgin [user]", ",virgin @alex"),
      cmd("weekly", "Claim your weekly reward.", ",weekly", ",weekly"),
      cmd("wiki", "Search Wikipedia.", ",wiki", ",wiki"),
      cmd("withdraw", "Withdraw currency from your bank.", ",withdraw [amount]", ",withdraw 10", ["with"]),
      cmd("work", "Work to earn currency.", ",work", ",work"),
      cmd("wrapped", "Show your yearly ware wrapped.", ",wrapped [member]", ",wrapped @alex"),
    ],
  },
  {
    slug: "fun",
    name: "Fun & Games",
    description: "Games, memes and everything to keep chat alive.",
    commands: [
      cmd("8ball", "Ask the magic 8ball a question.", ",8ball", ",8ball"),
      cmd("blacktea", "Start a stable reaction-based BlackTea game.", ",blacktea", ",blacktea"),
      cmd("blacktea stop", "Stop the active BlackTea game in this channel.", ",blacktea stop", ",blacktea stop"),
      cmd("connect4", "Play Connect 4 with a member.", ",connect4 [user]", ",connect4 @alex", ["c4"]),
      cmd("flag", "Show a country flag.", ",flag", ",flag", ["flaggif"]),
      cmd("flags", "Show a user's public flags.", ",flags", ",flags"),
      cmd("game", "Show what game a member is playing.", ",game", ",game"),
      cmd("hangman", "Play hangman.", ",hangman", ",hangman"),
      cmd("howgay", "Joke rating command.", ",howgay [user]", ",howgay @alex"),
      cmd("joke", "Tell a random joke.", ",joke", ",joke"),
      cmd("pp", "Joke rating command.", ",pp [user]", ",pp @alex"),
      cmd("rate", "Rate anything out of ten.", ",rate", ",rate"),
      cmd("reverse", "Reverse text or media.", ",reverse", ",reverse", ["rev"]),
      cmd("rps", "Play rock paper scissors.", ",rps [choice]", ",rps value"),
      cmd("ship", "Ship two members together.", ",ship [a] [b]", ",ship value value"),
      cmd("tictactoe", "Play tic tac toe.", ",tictactoe [user]", ",tictactoe @alex", ["ttt"]),
      cmd("tictactoe leaderboard", "Manage the leaderboard setting for tictactoe.", ",tictactoe leaderboard", ",tictactoe leaderboard"),
      cmd("tictactoe statistics", "Manage the statistics setting for tictactoe.", ",tictactoe statistics [member]", ",tictactoe statistics @alex"),
      cmd("trivia", "Play a trivia round.", ",trivia", ",trivia"),
      cmd("uwu", "Uwu-ify text.", ",uwu", ",uwu"),
    ],
  },
  {
    slug: "media",
    name: "Media & Social",
    description: "Media downloads, images, avatars and social platform lookups.",
    commands: [
      cmd("8d", "8D panning audio effect.", ",8d <interaction> <audio> [speed]", ",8d value value value"),
      cmd("addemote", "Add an emoji to the server.", ",addemote [emoji]", ",addemote value", ["ae", "emojiadd"]),
      cmd("ai-watermark", "Add a fake AI watermark to an image.", ",ai-watermark <interaction> <media> <brand> [text] [position] [opacity]", ",ai-watermark value value value hello value value"),
      cmd("anime", "Search for an anime title.", ",anime", ",anime"),
      cmd("apply", "Generate a fake Apply to Join application card.", ",apply <interaction> <user> <server> [answer]", ",apply value @alex value value"),
      cmd("avatar", "Show a user's avatar.", ",avatar [user]", ",avatar @alex", ["av", "pfp"]),
      cmd("banner", "Show a user's profile banner.", ",banner [user]", ",banner @alex"),
      cmd("base64", "Encode or decode base64 text.", ",base64 [mode]", ",base64 value", ["b64"]),
      cmd("book", "Look up a book.", ",book", ",book", ["bookfx"]),
      cmd("botinfo", "Show information about ware.", ",botinfo", ",botinfo", ["bi", "about"]),
      cmd("brainly", "Search Brainly for an answer.", ",brainly", ",brainly", ["brain", "studyanswer"]),
      cmd("character", "Look up a character.", ",character", ",character"),
      cmd("charinfo", "Show unicode info for characters.", ",charinfo", ",charinfo"),
      cmd("cleargnames", "Clear stored guild name history.", ",cleargnames", ",cleargnames", ["gnamesclear", "guildnamesclear"]),
      cmd("clearnames", "Clear a member's stored name history.", ",clearnames", ",clearnames", ["namesclear"]),
      cmd("color", "Preview a hex color.", ",color [hex color]", ",color value", ["colour", "hex"]),
      cmd("convo", "Generate a fake Discord conversation.", ",convo <interaction> <first user> <first message> <second user> <second message>", ",convo value value value value value"),
      cmd("createembed", "Build a custom embed.", ",createembed", ",createembed"),
      cmd("discog", "Look up music releases.", ",discog", ",discog", ["discogs"]),
      cmd("discog collections", "Manage the collections setting for discog.", ",discog collections", ",discog collections"),
      cmd("discog login", "Manage the login setting for discog.", ",discog login", ",discog login"),
      cmd("discog logout", "Manage the logout setting for discog.", ",discog logout", ",discog logout"),
      cmd("discog profile", "Manage the profile setting for discog.", ",discog profile", ",discog profile"),
      cmd("discog search", "Manage the search setting for discog.", ",discog search", ",discog search"),
      cmd("discog wantlist", "Manage the wantlist setting for discog.", ",discog wantlist", ",discog wantlist"),
      cmd("duckduckgo", "Search DuckDuckGo.", ",duckduckgo", ",duckduckgo", ["ddg"]),
      cmd("embedcode", "Get the embed code for a message.", ",embedcode [message link]", ",embedcode value"),
      cmd("freaky", "Joke rating command.", ",freaky", ",freaky"),
      cmd("giphy", "Search Giphy for a GIF.", ",giphy", ",giphy"),
      cmd("github", "Look up a GitHub user or repo.", ",github", ",github"),
      cmd("gnames", "Show the server's name history.", ",gnames [guild id]", ",gnames value", ["guildnames", "servernames"]),
      cmd("google", "Search Google.", ",google", ",google"),
      cmd("image2gif", "Shortcut for media image togif.", ",image2gif <interaction> <image>", ",image2gif value value"),
      cmd("img", "Search for an image.", ",img", ",img", ["image", "images", "duckduckgoimage"]),
      cmd("instagram", "Look up an Instagram profile.", ",instagram", ",instagram", ["ig"]),
      cmd("jumbo", "Enlarge an emoji.", ",jumbo [emoji]", ",jumbo value"),
      cmd("juul", "Juul utility commands.", ",juul", ",juul", ["j"]),
      cmd("juul flavor", "Manage the flavor setting for juul.", ",juul flavor", ",juul flavor"),
      cmd("juul hit", "Manage the hit setting for juul.", ",juul hit", ",juul hit"),
      cmd("juul pass", "Manage the pass setting for juul.", ",juul pass [member]", ",juul pass @alex"),
      cmd("juul stats", "Manage the stats setting for juul.", ",juul stats", ",juul stats"),
      cmd("juul steal", "Manage the steal setting for juul.", ",juul steal", ",juul steal"),
      cmd("juul toggle", "Toggle the juul configuration.", ",juul toggle", ",juul toggle"),
      cmd("lego", "Turn an image into lego bricks.", ",lego [url]", ",lego value"),
      cmd("lyrics", "Fetch song lyrics.", ",lyrics", ",lyrics"),
      cmd("makegif", "Turn media into a GIF.", ",makegif", ",makegif"),
      cmd("makemp3", "Convert media into an MP3.", ",makemp3 [url]", ",makemp3 value", ["mp3", "toaudio"]),
      cmd("manga", "Search for a manga title.", ",manga", ",manga"),
      cmd("media", "Download and convert media.", ",media", ",media", ["m"]),
      cmd("media billboard", "Manage the billboard setting for media.", ",media billboard [url]", ",media billboard value"),
      cmd("media bloom", "Manage the bloom setting for media.", ",media bloom [url] [radius] [brightness] [sharpness]", ",media bloom value value value value"),
      cmd("media blur", "Manage the blur setting for media.", ",media blur [url] [strength]", ",media blur value value"),
      cmd("media book", "Manage the book setting for media.", ",media book [url]", ",media book value"),
      cmd("media caption", "Manage the caption setting for media.", ",media caption [first]", ",media caption value"),
      cmd("media circuitboard", "Manage the circuitboard setting for media.", ",media circuitboard [url]", ",media circuitboard value"),
      cmd("media deepfry", "Manage the deepfry setting for media.", ",media deepfry [url]", ",media deepfry value"),
      cmd("media fisheye", "Manage the fisheye setting for media.", ",media fisheye [url]", ",media fisheye value"),
      cmd("media flag", "Manage the flag setting for media.", ",media flag [url]", ",media flag value"),
      cmd("media flag2", "Manage the flag2 setting for media.", ",media flag2 [url]", ",media flag2 value"),
      cmd("media fortune", "Manage the fortune setting for media.", ",media fortune [url]", ",media fortune value"),
      cmd("media gifmagik", "Manage the gifmagik setting for media.", ",media gifmagik [url]", ",media gifmagik value"),
      cmd("media grayscale", "Manage the grayscale setting for media.", ",media grayscale [url]", ",media grayscale value"),
      cmd("media heart", "Manage the heart setting for media.", ",media heart [url]", ",media heart value"),
      cmd("media invert", "Manage the invert setting for media.", ",media invert [url]", ",media invert value"),
      cmd("media magik", "Manage the magik setting for media.", ",media magik [url]", ",media magik value"),
      cmd("media meme", "Manage the meme setting for media.", ",media meme [url] [top]", ",media meme value value"),
      cmd("media motivate", "Manage the motivate setting for media.", ",media motivate [url] [top]", ",media motivate value value"),
      cmd("media neon", "Manage the neon setting for media.", ",media neon [url]", ",media neon value"),
      cmd("media pixelate", "Manage the pixelate setting for media.", ",media pixelate [url]", ",media pixelate value"),
      cmd("media rainbow", "Manage the rainbow setting for media.", ",media rainbow [url]", ",media rainbow value"),
      cmd("media reverse", "Manage the reverse setting for media.", ",media reverse [url]", ",media reverse value"),
      cmd("media rubiks", "Manage the rubiks setting for media.", ",media rubiks [url]", ",media rubiks value"),
      cmd("media scramble", "Manage the scramble setting for media.", ",media scramble [url]", ",media scramble value"),
      cmd("media speechbubble", "Manage the speechbubble setting for media.", ",media speechbubble [url]", ",media speechbubble value"),
      cmd("media speed", "Manage the speed setting for media.", ",media speed [url] [multiplier]", ",media speed value value"),
      cmd("media spin", "Manage the spin setting for media.", ",media spin [url]", ",media spin value"),
      cmd("media spread", "Manage the spread setting for media.", ",media spread [url] [strength]", ",media spread value value"),
      cmd("media swirl", "Manage the swirl setting for media.", ",media swirl [url] [strength]", ",media swirl value value"),
      cmd("media tattoo", "Manage the tattoo setting for media.", ",media tattoo [url]", ",media tattoo value"),
      cmd("media toaster", "Manage the toaster setting for media.", ",media toaster [url]", ",media toaster value"),
      cmd("media valentine", "Manage the valentine setting for media.", ",media valentine [url]", ",media valentine value"),
      cmd("media wormhole", "Manage the wormhole setting for media.", ",media wormhole [url]", ",media wormhole value"),
      cmd("media zoom", "Manage the zoom setting for media.", ",media zoom [url]", ",media zoom value"),
      cmd("media zoomblur", "Manage the zoomblur setting for media.", ",media zoomblur [url]", ",media zoomblur value"),
      cmd("movie", "Look up a movie.", ",movie", ",movie"),
      cmd("movie expand", "Manage the expand setting for movie.", ",movie expand", ",movie expand"),
      cmd("names", "Show a member's name history.", ",names [member]", ",names @alex", ["namehistory", "nhistory"]),
      cmd("oauth", "Get ware's OAuth invite link.", ",oauth", ",oauth", ["invite", "inviteme"]),
      cmd("ocrtr", "Read and translate text from an image.", ",ocrtr [to language]", ",ocrtr value"),
      cmd("qr", "Generate a QR code.", ",qr", ",qr", ["qrcode"]),
      cmd("quickpoll", "Create a quick yes/no poll.", ",quickpoll", ",quickpoll"),
      cmd("randomhex", "Generate a random hex color.", ",randomhex", ",randomhex"),
      cmd("request", "Generate a fake Discord friend request notification.", ",request <interaction> <user> [mutual friends]", ",request value @alex value"),
      cmd("reverseimage", "Run a reverse image search.", ",reverseimage [url]", ",reverseimage value", ["reverseimg"]),
      cmd("roblox", "Look up a Roblox profile.", ",roblox", ",roblox", ["rbx", "rblx"]),
      cmd("robloxid", "Look up a Roblox user by ID.", ",robloxid [user id]", ",robloxid value", ["rbxid", "rblxid"]),
      cmd("run", "Run a code snippet.", ",run", ",run"),
      cmd("search", "Search the web.", ",search", ",search"),
      cmd("sendmessage", "Send a message as ware.", ",sendmessage [user]", ",sendmessage @alex", ["senddm", "dmuser", "sm"]),
      cmd("setupdashboard", "Set up the server dashboard.", ",setupdashboard", ",setupdashboard", ["sd"]),
      cmd("share limit", "Manage the limit setting for share.", ",share limit [amount]", ",share limit 10"),
      cmd("share list", "List all entries for the share configuration.", ",share list", ",share list"),
      cmd("share max", "Manage the max setting for share.", ",share max [amount]", ",share max 10"),
      cmd("share remove", "Remove an entry from the share configuration.", ",share remove [member]", ",share remove @alex"),
      cmd("shazam", "Identify a song from audio.", ",shazam [url]", ",shazam value", ["songfind", "recognizesong"]),
      cmd("spotify", "Show and control Spotify listening.", ",spotify [member]", ",spotify @alex"),
      cmd("spotify login", "Manage the login setting for spotify.", ",spotify login", ",spotify login"),
      cmd("spotify logout", "Manage the logout setting for spotify.", ",spotify logout", ",spotify logout"),
      cmd("support", "Get the support server link.", ",support", ",support"),
      cmd("tenor", "Search Tenor for a GIF.", ",tenor", ",tenor"),
      cmd("tiktok", "Run the tiktok command.", ",tiktok", ",tiktok", ["tt"]),
      cmd("timediff", "Show the difference between two times.", ",timediff [first id] [second id]", ",timediff value value"),
      cmd("togif", "Convert an image to GIF.", ",togif <interaction> <image>", ",togif value value"),
      cmd("tone", "Analyze the tone of a message.", ",tone", ",tone"),
      cmd("topcommands", "Show the most used commands.", ",topcommands", ",topcommands", ["topcmds", "commandstats"]),
      cmd("transparent", "Make an image transparent.", ",transparent [url]", ",transparent value"),
      cmd("tts", "Send text as speech.", ",tts [speaker]", ",tts value"),
      cmd("tts channel", "Manage the channel setting for tts.", ",tts channel [speaker]", ",tts channel value"),
      cmd("tvshow", "Look up a TV show.", ",tvshow", ",tvshow"),
      cmd("uptime", "Show how long ware has been online.", ",uptime", ",uptime"),
      cmd("urban", "Look up an Urban Dictionary definition.", ",urban", ",urban"),
      cmd("vote", "Vote for ware.", ",vote", ",vote"),
      cmd("weather", "Check the weather anywhere.", ",weather", ",weather"),
      cmd("wikihow", "Search WikiHow.", ",wikihow", ",wikihow", ["howto", "whow"]),
      cmd("wolfram", "Query Wolfram Alpha.", ",wolfram", ",wolfram"),
      cmd("wouldyourather", "Play would you rather.", ",wouldyourather", ",wouldyourather", ["wyr"]),
      cmd("youtube", "Search YouTube.", ",youtube", ",youtube"),
    ],
  },
  {
    slug: "messages",
    name: "Messages & Embeds",
    description: "Embeds, sticky messages, autoresponders, tags and replies.",
    commands: [
      cmd("alias", "Manage custom aliases for commands.", ",alias", ",alias"),
      cmd("alias add", "Add a new entry to the alias configuration.", ",alias add [shortcut]", ",alias add value"),
      cmd("alias list", "List all entries for the alias configuration.", ",alias list", ",alias list"),
      cmd("alias remove", "Remove an entry from the alias configuration.", ",alias remove [shortcut]", ",alias remove value"),
      cmd("alias removeall", "Manage the removeall setting for alias.", ",alias removeall", ",alias removeall"),
      cmd("alias reset", "Reset the alias configuration.", ",alias reset", ",alias reset"),
      cmd("alias view", "View the alias configuration.", ",alias view [shortcut]", ",alias view value"),
      cmd("autoreact", "Auto-react to messages in a channel.", ",autoreact", ",autoreact", ["react", "autoreactions"]),
      cmd("autoreact add", "Add a new entry to the autoreact configuration.", ",autoreact add [trigger] [emojis]", ",autoreact add value value"),
      cmd("autoreact clear", "Clear the autoreact configuration.", ",autoreact clear", ",autoreact clear"),
      cmd("autoreact list", "List all entries for the autoreact configuration.", ",autoreact list", ",autoreact list"),
      cmd("autoreact remove", "Remove an entry from the autoreact configuration.", ",autoreact remove [trigger]", ",autoreact remove value"),
      cmd("autoresponder", "Create automatic replies to trigger words.", ",autoresponder", ",autoresponder"),
      cmd("autoresponder add", "Add a new entry to the autoresponder configuration.", ",autoresponder add [trigger]", ",autoresponder add value"),
      cmd("autoresponder clear", "Clear the autoresponder configuration.", ",autoresponder clear", ",autoresponder clear"),
      cmd("autoresponder list", "List all entries for the autoresponder configuration.", ",autoresponder list", ",autoresponder list"),
      cmd("autoresponder remove", "Remove an entry from the autoresponder configuration.", ",autoresponder remove", ",autoresponder remove"),
      cmd("clearreactionsnipe", "Clear the saved reaction snipe.", ",clearreactionsnipe", ",clearreactionsnipe", ["clearrs"]),
      cmd("editsnipe", "Show the last edited message.", ",editsnipe [index]", ",editsnipe value", ["es"]),
      cmd("embed", "Create and send rich embeds.", ",embed", ",embed"),
      cmd("embed copy", "Manage the copy setting for embed.", ",embed copy [message link]", ",embed copy value"),
      cmd("embed create", "Create the embed configuration.", ",embed create [name]", ",embed create value"),
      cmd("embed delete", "Delete an entry from the embed configuration.", ",embed delete", ",embed delete"),
      cmd("embed list", "List all entries for the embed configuration.", ",embed list", ",embed list"),
      cmd("embed preview", "Manage the preview setting for embed.", ",embed preview", ",embed preview"),
      cmd("message", "Set the message sent in the vanity channel.", ",message <interaction> <message>", ",message value hello"),
      cmd("message embed", "Manage the embed setting for message.", ",message embed", ",message embed"),
      cmd("reactionsnipe", "Show a recently removed reaction in the current channel.", ",reactionsnipe [index]", ",reactionsnipe value", ["rs"]),
      cmd("rename", "Rename channels, roles or emojis in bulk.", ",rename", ",rename"),
      cmd("rename emojis", "Manage the emojis setting for rename.", ",rename emojis", ",rename emojis"),
      cmd("rename stickers", "Manage the stickers setting for rename.", ",rename stickers", ",rename stickers"),
      cmd("reply", "Generate a fake Discord reply message.", ",reply <interaction> <user> <message> <replying to>", ",reply value @alex hello value"),
      cmd("reply add", "Add a new entry to the reply configuration.", ",reply add", ",reply add"),
      cmd("reply clear", "Clear the reply configuration.", ",reply clear", ",reply clear"),
      cmd("reply list", "List all entries for the reply configuration.", ",reply list", ",reply list"),
      cmd("reply remove", "Remove an entry from the reply configuration.", ",reply remove", ",reply remove"),
      cmd("snipe", "Show the last deleted message.", ",snipe [index]", ",snipe value", ["s"]),
      cmd("stick", "Stick a message to a channel.", ",stick", ",stick", ["sticky"]),
      cmd("stick embed", "Manage the embed setting for stick.", ",stick embed", ",stick embed"),
      cmd("stick list", "List all entries for the stick configuration.", ",stick list", ",stick list"),
      cmd("stick message", "Manage the message setting for stick.", ",stick message", ",stick message"),
      cmd("stick remove", "Remove an entry from the stick configuration.", ",stick remove [channel]", ",stick remove #general"),
      cmd("tags", "Create and manage custom tags.", ",tags", ",tags", ["tag"]),
      cmd("tags add", "Add a new entry to the tags configuration.", ",tags add [tag name]", ",tags add value"),
      cmd("tags author", "Manage the author setting for tags.", ",tags author", ",tags author"),
      cmd("tags edit", "Edit the tags configuration.", ",tags edit [tag name]", ",tags edit value"),
      cmd("tags list", "List all entries for the tags configuration.", ",tags list [member]", ",tags list @alex"),
      cmd("tags random", "Manage the random setting for tags.", ",tags random", ",tags random"),
      cmd("tags remove", "Remove an entry from the tags configuration.", ",tags remove", ",tags remove"),
      cmd("tags rename", "Manage the rename setting for tags.", ",tags rename [tag name]", ",tags rename value"),
      cmd("tags reset", "Reset the tags configuration.", ",tags reset", ",tags reset"),
      cmd("tags search", "Manage the search setting for tags.", ",tags search", ",tags search"),
    ],
  },
  {
    slug: "giveaways",
    name: "Giveaways",
    description: "Run giveaways with requirements, rerolls and winners.",
    commands: [
      cmd("counting", "Configure the counting game channel.", ",counting [channel]", ",counting #general"),
      cmd("country", "Look up country information.", ",country", ",country"),
      cmd("emojiinfo", "Show information about an emoji.", ",emojiinfo [emoji]", ",emojiinfo value"),
      cmd("end", "End a giveaway or active event.", ",end", ",end"),
      cmd("end blacktea", "Manage the blacktea setting for end.", ",end blacktea", ",end blacktea"),
      cmd("end flags", "Manage the flags setting for end.", ",end flags", ",end flags"),
      cmd("fasttype", "Play a typing speed game.", ",fasttype", ",fasttype"),
      cmd("gend", "End a giveaway early.", ",gend", ",gend"),
      cmd("giveaway", "Create and manage giveaways.", ",giveaway", ",giveaway", ["gw", "giveaways"]),
      cmd("giveaway blacklist", "Manage the blacklist setting for giveaway.", ",giveaway blacklist [role]", ",giveaway blacklist @Staff"),
      cmd("giveaway bonus", "Manage the bonus setting for giveaway.", ",giveaway bonus [role] [entries]", ",giveaway bonus @Staff value"),
      cmd("giveaway cancel", "Manage the cancel setting for giveaway.", ",giveaway cancel [message id]", ",giveaway cancel value"),
      cmd("giveaway dmcreator", "Manage the dmcreator setting for giveaway.", ",giveaway dmcreator", ",giveaway dmcreator"),
      cmd("giveaway dmwinners", "Manage the dmwinners setting for giveaway.", ",giveaway dmwinners", ",giveaway dmwinners"),
      cmd("giveaway duplicate", "Manage the duplicate setting for giveaway.", ",giveaway duplicate [message id] [duration]", ",giveaway duplicate value 30m"),
      cmd("giveaway edit", "Edit the giveaway configuration.", ",giveaway edit [message id] [field]", ",giveaway edit value value"),
      cmd("giveaway end", "Manage the end setting for giveaway.", ",giveaway end [message reference]", ",giveaway end value"),
      cmd("giveaway info", "Show information about the giveaway configuration.", ",giveaway info [message id]", ",giveaway info value"),
      cmd("giveaway list", "List all entries for the giveaway configuration.", ",giveaway list", ",giveaway list"),
      cmd("giveaway pause", "Manage the pause setting for giveaway.", ",giveaway pause [message id]", ",giveaway pause value"),
      cmd("giveaway reroll", "Manage the reroll setting for giveaway.", ",giveaway reroll [message reference]", ",giveaway reroll value"),
      cmd("giveaway resume", "Manage the resume setting for giveaway.", ",giveaway resume [message id]", ",giveaway resume value"),
      cmd("giveaway setmax", "Manage the setmax setting for giveaway.", ",giveaway setmax [role] [max entries]", ",giveaway setmax @Staff value"),
      cmd("giveaway start", "Manage the start setting for giveaway.", ",giveaway start [duration] [winners]", ",giveaway start 30m value"),
      cmd("giveaway template", "Manage the template setting for giveaway.", ",giveaway template", ",giveaway template"),
      cmd("greroll", "Reroll a giveaway winner.", ",greroll", ",greroll"),
      cmd("gstart", "Start a giveaway.", ",gstart [duration] [winners]", ",gstart 30m value"),
      cmd("higherlower", "Play higher or lower.", ",higherlower", ",higherlower"),
      cmd("inviteinfo", "Show details about an invite.", ",inviteinfo [code]", ",inviteinfo value"),
      cmd("math", "Solve a math expression.", ",math", ",math"),
      cmd("newest", "Show the newest server members.", ",newest", ",newest"),
      cmd("oldest", "Show the oldest server members.", ",oldest", ",oldest"),
      cmd("snowflake", "Decode a Discord snowflake ID.", ",snowflake [snowflake id]", ",snowflake value"),
      cmd("starboard", "Configure the starboard.", ",starboard [channel] [threshold]", ",starboard #general value"),
      cmd("stickerinfo", "Show information about a sticker.", ",stickerinfo [sticker name]", ",stickerinfo value"),
      cmd("unscramble", "Solve a scrambled word.", ",unscramble", ",unscramble"),
    ],
  },
  {
    slug: "ai",
    name: "AI",
    description: "Ask questions, generate content and chat with AI.",
    commands: [
      cmd("ai", "Ask the AI assistant anything.", ",ai", ",ai", ["ask"]),
      cmd("gemini", "Ask Gemini a question.", ",gemini", ",gemini", ["askgemini"]),
      cmd("imagine", "Generate an image from a prompt.", ",imagine", ",imagine"),
      cmd("memory", "Manage what the AI remembers.", ",memory", ",memory", ["mem"]),
      cmd("memory add", "Add a new entry to the memory configuration.", ",memory add", ",memory add"),
      cmd("memory clear", "Clear the memory configuration.", ",memory clear", ",memory clear"),
      cmd("memory delete", "Delete an entry from the memory configuration.", ",memory delete [note id]", ",memory delete value"),
      cmd("memory list", "List all entries for the memory configuration.", ",memory list", ",memory list"),
      cmd("memory search", "Manage the search setting for memory.", ",memory search", ",memory search"),
      cmd("ocr", "Extract visible text from an image attachment or replied-to image.", ",ocr", ",ocr"),
      cmd("summarize", "Summarize a conversation or text with AI.", ",summarize", ",summarize"),
      cmd("translate", "Translate text to another language.", ",translate [target lang]", ",translate value", ["tr", "tl"]),
    ],
  },
  {
    slug: "utility",
    name: "Utility",
    description: "Everyday helpers: info, lookups, reminders and server tools.",
    commands: [
      cmd("add", "Add a reward to vanity rewards.", ",add <interaction> <role>", ",add value @Staff"),
      cmd("afk", "Set your AFK status with an optional reason.", ",afk", ",afk", ["a"]),
      cmd("ai2", "Ask the secondary AI model a question.", ",ai2", ",ai2"),
      cmd("aichat", "Start a conversational AI chat session.", ",aichat", ",aichat", ["chatbot"]),
      cmd("aicode", "Generate code with AI.", ",aicode", ",aicode", ["codeai", "aic"]),
      cmd("aiexplain", "Have the AI explain a topic or snippet.", ",aiexplain", ",aiexplain", ["explainai", "aiex"]),
      cmd("aigrammar", "Fix grammar and spelling with AI.", ",aigrammar", ",aigrammar", ["grammarai", "grammar"]),
      cmd("aiimage", "Generate an image with AI.", ",aiimage", ",aiimage", ["imageai"]),
      cmd("aimod", "Let AI review a message for rule breaks.", ",aimod", ",aimod"),
      cmd("badges", "Show a user's Discord badges.", ",badges [user]", ",badges @alex", ["badge", "userbadges", "userflags"]),
      cmd("blur", "Blur an image.", ",blur [user]", ",blur @alex", ["blurry"]),
      cmd("bot", "Manage bot-wide settings.", ",bot", ",bot"),
      cmd("bot add", "Add a new entry to the bot configuration.", ",bot add [action]", ",bot add value"),
      cmd("bot message", "Manage the message setting for bot.", ",bot message", ",bot message"),
      cmd("bot reply", "Manage the reply setting for bot.", ",bot reply", ",bot reply"),
      cmd("btc", "Show the current Bitcoin price.", ",btc", ",btc"),
      cmd("button", "Create message buttons.", ",button [label] [url]", ",button value value"),
      cmd("calculator", "Open an interactive calculator.", ",calculator", ",calculator", ["calc"]),
      cmd("casino", "Open the casino menu.", ",casino", ",casino"),
      cmd("channel", "Manage channels.", ",channel", ",channel", ["ch"]),
      cmd("channel category", "Manage the category setting for channel.", ",channel category [channel]", ",channel category #general"),
      cmd("channel clone", "Manage the clone setting for channel.", ",channel clone [channel]", ",channel clone #general"),
      cmd("channel create", "Create the channel configuration.", ",channel create [kind]", ",channel create value"),
      cmd("channel delete", "Delete an entry from the channel configuration.", ",channel delete [channel]", ",channel delete #general"),
      cmd("channel nsfw", "Manage the nsfw setting for channel.", ",channel nsfw [channel] [state]", ",channel nsfw #general value"),
      cmd("channel rename", "Manage the rename setting for channel.", ",channel rename [channel]", ",channel rename #general"),
      cmd("channel topic", "Manage the topic setting for channel.", ",channel topic [channel]", ",channel topic #general"),
      cmd("channelinfo", "Show information about a channel.", ",channelinfo [channel]", ",channelinfo #general", ["ci"]),
      cmd("clih", "Give the user a random clih tightness percentage, capped at 100%.", ",clih", ",clih"),
      cmd("cmds", "List every ware command.", ",cmds", ",cmds", ["commands"]),
      cmd("crypto", "Look up a cryptocurrency price.", ",crypto", ",crypto"),
      cmd("cs", "Clear deleted and edited snipes for the current channel.", ",cs", ",cs", ["clearsnipe", "clearsnipes"]),
      cmd("customize", "Customize ware for your server.", ",customize", ",customize"),
      cmd("customize avatar", "Manage the avatar setting for customize.", ",customize avatar", ",customize avatar"),
      cmd("customize banner", "Manage the banner setting for customize.", ",customize banner", ",customize banner"),
      cmd("customize bio", "Manage the bio setting for customize.", ",customize bio", ",customize bio"),
      cmd("diagnose", "Check whether vanity rewards can detect statuses and assign roles.", ",diagnose <interaction>", ",diagnose value"),
      cmd("disable", "Disable vanity rewards.", ",disable <interaction>", ",disable value"),
      cmd("dropdown", "Create a dropdown menu message.", ",dropdown", ",dropdown"),
      cmd("emojis", "List the server's emojis.", ",emojis", ",emojis"),
      cmd("enable", "Enable vanity rewards.", ",enable <interaction>", ",enable value"),
      cmd("firstmessage", "Jump to the first message in a channel.", ",firstmessage [channel]", ",firstmessage #general", ["firstmsg"]),
      cmd("fishing", "Go fishing for currency.", ",fishing", ",fishing"),
      cmd("fn", "Look up Fortnite stats.", ",fn [member]", ",fn @alex"),
      cmd("force", "Force an action or setting.", ",force", ",force"),
      cmd("force nickname", "Manage the nickname setting for force.", ",force nickname [member]", ",force nickname @alex"),
      cmd("gedit", "Edit an active giveaway.", ",gedit", ",gedit"),
      cmd("getuser", "Look up a user by ID.", ",getuser", ",getuser"),
      cmd("getuser id", "Manage the id setting for getuser.", ",getuser id", ",getuser id"),
      cmd("ghost ping", "Manage the ping setting for ghost.", ",ghost ping [action]", ",ghost ping value"),
      cmd("glist", "List active giveaways.", ",glist", ",glist"),
      cmd("height", "Give the user a random height, capped at 7'10\".", ",height", ",height", ["ht"]),
      cmd("heist", "Start a bank heist with other members.", ",heist [amount]", ",heist 10"),
      cmd("help", "Show help for ware and its commands.", ",help", ",help", ["h"]),
      cmd("howhot", "Joke rating command.", ",howhot [user]", ",howhot @alex", ["hot"]),
      cmd("https://warebot.xyz", "Run the https://warebot.xyz command.", ",https://warebot.xyz [user]", ",https://warebot.xyz @alex"),
      cmd("invert", "Invert the colors of an image.", ",invert [user]", ",invert @alex", ["negative"]),
      cmd("invites", "Show invite statistics.", ",invites", ",invites"),
      cmd("join", "Make ware join your voice channel.", ",join", ",join"),
      cmd("join ping", "Manage the ping setting for join.", ",join ping [state]", ",join ping value"),
      cmd("joined", "Show when a member joined.", ",joined [user]", ",joined @alex", ["joinedat"]),
      cmd("lastseen", "Show when a member was last active.", ",lastseen [member]", ",lastseen @alex"),
      cmd("leveling", "Configure the leveling system.", ",leveling", ",leveling", ["levels", "lvl"]),
      cmd("leveling rewards", "Manage the rewards setting for leveling.", ",leveling rewards", ",leveling rewards"),
      cmd("list", "List the rewards for vanity rewards.", ",list <interaction>", ",list value"),
      cmd("ltc", "Show the Litecoin price.", ",ltc", ",ltc"),
      cmd("marry", "Marry another member.", ",marry [user]", ",marry @alex"),
      cmd("membercount", "Show the server member count.", ",membercount", ",membercount", ["mc"]),
      cmd("monthly", "Claim your monthly reward.", ",monthly", ",monthly"),
      cmd("move", "Move a member to another voice channel.", ",move [user] [channel]", ",move @alex #general"),
      cmd("notes", "View staff notes on a member.", ",notes [member]", ",notes @alex", ["nt"]),
      cmd("notes add", "Add a new entry to the notes configuration.", ",notes add [member]", ",notes add @alex"),
      cmd("perms", "Show a member's permissions.", ",perms [user]", ",perms @alex", ["permissions"]),
      cmd("pets", "Manage your pets.", ",pets", ",pets"),
      cmd("ping", "Check ware's latency.", ",ping", ",ping"),
      cmd("pixelate", "Pixelate an image.", ",pixelate [user]", ",pixelate @alex", ["pixel"]),
      cmd("premium", "Manage premium features.", ",premium", ",premium", ["prem"]),
      cmd("premium activate", "Manage the activate setting for premium.", ",premium activate [key]", ",premium activate value"),
      cmd("premium servers", "Manage the servers setting for premium.", ",premium servers", ",premium servers"),
      cmd("punishments", "List configured punishments.", ",punishments [member]", ",punishments @alex"),
      cmd("reason", "Update the reason on a moderation case.", ",reason [case id]", ",reason value"),
      cmd("remind", "Set a reminder.", ",remind [duration]", ",remind 30m", ["remindme"]),
      cmd("remove", "Remove a reward from vanity rewards.", ",remove <interaction> <role>", ",remove value @Staff"),
      cmd("resetnick", "Reset a member's nickname.", ",resetnick [user]", ",resetnick @alex"),
      cmd("rewrite", "Rewrite text with AI.", ",rewrite", ",rewrite"),
      cmd("roleinfo", "Show information about a role.", ",roleinfo", ",roleinfo", ["ri"]),
      cmd("s?u", "Shortcut utility command.", ",s?u", ",s?u"),
      cmd("scan", "Scan members and apply vanity rewards now.", ",scan <interaction>", ",scan value"),
      cmd("serveravatar", "Show a member's server avatar.", ",serveravatar [user]", ",serveravatar @alex", ["sav", "guildavatar"]),
      cmd("serverbanner", "Show the server banner.", ",serverbanner", ",serverbanner", ["guildbanner", "sbanner"]),
      cmd("servericon", "Show the server icon.", ",servericon", ",servericon", ["guildicon", "sicon"]),
      cmd("serverinfo", "Show information about the server.", ",serverinfo", ",serverinfo", ["si"]),
      cmd("set", "Setup the vanity URL you want for vanity rewards.", ",set <interaction> <vanity>", ",set value value"),
      cmd("sol", "Show the Solana price.", ",sol", ",sol"),
      cmd("stickers", "List the server's stickers.", ",stickers", ",stickers"),
      cmd("stocks", "Look up a stock price.", ",stocks", ",stocks"),
      cmd("suggest", "Submit a suggestion.", ",suggest", ",suggest"),
      cmd("sync", "Refresh Ware's global slash commands without creating duplicates.", ",sync <interaction>", ",sync value"),
      cmd("test", "Test whether a member has the vanity in their status.", ",test <interaction> [member]", ",test value @alex"),
      cmd("timer", "Start a timer.", ",timer [duration]", ",timer 30m"),
      cmd("timezone", "Set and view member timezones.", ",timezone", ",timezone", ["tz"]),
      cmd("timezone set", "Set the timezone configuration.", ",timezone set", ",timezone set"),
      cmd("trash", "Joke rating command.", ",trash [user]", ",trash @alex"),
      cmd("triggered", "Make a triggered image.", ",triggered [user]", ",triggered @alex"),
      cmd("voiceban", "Ban a member from voice channels.", ",voiceban [user]", ",voiceban @alex"),
      cmd("voicekick", "Kick a member from a voice channel.", ",voicekick [user]", ",voicekick @alex"),
      cmd("voiceunban", "Unban a member from voice channels.", ",voiceunban [user]", ",voiceunban @alex"),
      cmd("wanted", "Make a wanted poster image.", ",wanted [user]", ",wanted @alex"),
      cmd("who", "Look up who a member is.", ",who", ",who"),
      cmd("whois", "Show detailed information about a user.", ",whois", ",whois", ["userinfo", "ui"]),
    ],
  },
];
