export interface CommandDef {
  name: string;
  description: string;
  usage: string;
  example: string;
}

export interface CommandCategory {
  slug: string;
  name: string;
  description: string;
  commands: CommandDef[];
}

const cmd = (
  name: string,
  description: string,
  usage: string,
  example: string,
): CommandDef => ({ name, description, usage, example });

export const commandCategories: CommandCategory[] = [
  {
    slug: "moderation",
    name: "Moderation",
    description: "Keep your server safe with a full moderation toolkit.",
    commands: [
      cmd("ban", "Permanently ban a member from the server.", ",ban <user> [reason]", ",ban @alex spamming invites"),
      cmd("kick", "Kick a member from the server.", ",kick <user> [reason]", ",kick @alex breaking rule 3"),
      cmd("unban", "Unban a previously banned user by ID or tag.", ",unban <user|id>", ",unban 349128374019283740"),
      cmd("hardban", "Ban a user and prevent them from ever being unbanned without owner override.", ",hardban <user> [reason]", ",hardban @troll raiding"),
      cmd("softban", "Ban then immediately unban to purge a user's recent messages.", ",softban <user> [reason]", ",softban @alex clearing spam"),
      cmd("massban", "Ban multiple users at once by ID.", ",massban <ids...> [reason]", ",massban 111 222 333 raid cleanup"),
      cmd("mute", "Text-mute a member so they can't send messages.", ",mute <user> [duration] [reason]", ",mute @alex 30m chill out"),
      cmd("unmute", "Remove a text mute from a member.", ",unmute <user>", ",unmute @alex"),
      cmd("timeout", "Discord native timeout on a member.", ",timeout <user> <duration> [reason]", ",timeout @alex 1h flaming"),
      cmd("untimeout", "Remove a Discord timeout early.", ",untimeout <user>", ",untimeout @alex"),
      cmd("warn", "Issue a warning that is logged to the member's history.", ",warn <user> <reason>", ",warn @alex no politics in general"),
      cmd("jail", "Move a member into the jail role/channel until released.", ",jail <user> [reason]", ",jail @alex under review"),
      cmd("unjail", "Release a member from jail.", ",unjail <user>", ",unjail @alex"),
      cmd("rmute", "Reaction-mute a member so they can't add reactions.", ",rmute <user> [duration]", ",rmute @alex 1h"),
      cmd("imute", "Image-mute a member so they can't attach files or embeds.", ",imute <user> [duration]", ",imute @alex 2h"),
      cmd("clear", "Bulk delete messages in the current channel.", ",clear <amount> [user]", ",clear 50 @alex"),
      cmd("strip", "Remove every role from a member.", ",strip <user>", ",strip @alex"),
      cmd("restore", "Restore a member's previous roles after they rejoin.", ",restore <user>", ",restore @alex"),
      cmd("lockdown", "Lock every configured channel at once.", ",lockdown [reason]", ",lockdown raid in progress"),
      cmd("lock", "Prevent @everyone from sending in a channel.", ",lock [channel]", ",lock #general"),
      cmd("unlock", "Reopen a locked channel.", ",unlock [channel]", ",unlock #general"),
      cmd("lockall", "Lock every text channel in the server.", ",lockall", ",lockall"),
      cmd("masskick", "Kick many members by role or ID list.", ",masskick <role|ids...>", ",masskick @Unverified"),
      cmd("massmove", "Move every user from one voice channel to another.", ",massmove <from> <to>", ",massmove Lobby AFK"),
      cmd("massrename", "Rename every member matching a filter.", ",massrename <filter> <new name>", ",massrename bots Verified"),
      cmd("massrole", "Add or remove a role from every member matching a filter.", ",massrole <add|remove> <role> [filter]", ",massrole add @Member humans"),
      cmd("massdisconnect", "Disconnect everyone in voice channels.", ",massdisconnect", ",massdisconnect"),
      cmd("massdm", "DM a message to every member matching a role.", ",massdm <role> <message>", ",massdm @Beta thanks for testing!"),
    ],
  },
  {
    slug: "security",
    name: "Security",
    description:
      "Enterprise-grade server protection: antinuke, verification, quarantine, and permission hardening. Every destructive action is watched, rate-limited, and reversible.",
    commands: [
      cmd("security", "Open the full security dashboard with every module, status, and punishment.", ",security", ",security"),
      cmd("security setup", "Guided setup that turns on the recommended protection profile.", ",security setup [profile]", ",security setup strict"),
      cmd("security profile", "Switch between low / medium / high / extreme protection profiles.", ",security profile <level>", ",security profile high"),
      cmd("security status", "Show which security modules are active and their thresholds.", ",security status", ",security status"),
      cmd("security reset", "Reset every security module to defaults.", ",security reset", ",security reset"),
      cmd("verification", "Configure the member verification gate (captcha, age, questions).", ",verification <on|off|mode> [value]", ",verification mode captcha"),
      cmd("verify", "Verify yourself through the configured challenge.", ",verify", ",verify"),
      cmd("captcha", "Configure the captcha challenge and difficulty.", ",captcha <on|off|difficulty> [value]", ",captcha difficulty hard"),
      cmd("agecheck", "Reject accounts younger than X days at join.", ",agecheck <on|off> [days]", ",agecheck on 7"),
      cmd("quarantine", "Instantly quarantine a member: strip roles, block DMs, isolate to a review channel.", ",quarantine <user> [reason]", ",quarantine @alex suspicious"),
      cmd("unquarantine", "Release a quarantined member and restore their roles.", ",unquarantine <user>", ",unquarantine @alex"),
      cmd("trust", "Mark a user as trusted so security modules ignore them.", ",trust <user>", ",trust @alex"),
      cmd("untrust", "Remove a user from the trusted list.", ",untrust <user>", ",untrust @alex"),
      cmd("trusted", "List every trusted user, role, and bot.", ",trusted", ",trusted"),
      cmd("owner", "Grant a user full override permissions on ware's security stack.", ",owner <add|remove|list> [user]", ",owner add @alex"),
      cmd("extraowner", "Add an additional co-owner who bypasses antinuke limits.", ",extraowner <add|remove> <user>", ",extraowner add @jamie"),
      cmd("whitelist", "Whitelist a user, role, or bot from every anti module.", ",whitelist <add|remove|list> [target]", ",whitelist add @Mods"),
      cmd("permit", "Grant a one-time permit to perform a normally blocked action.", ",permit <user> <action> [duration]", ",permit @alex ban 10m"),
      cmd("rolelock", "Lock a role so nobody can hand it out except approved staff.", ",rolelock <role> <on|off>", ",rolelock @Admin on"),
      cmd("channellock", "Lock a channel's permissions so they can't be overwritten.", ",channellock <channel> <on|off>", ",channellock #announcements on"),
      cmd("perms", "Show effective permissions and dangerous grants for a member.", ",perms <user>", ",perms @alex"),
      cmd("dangerous", "List every role, user, or webhook with dangerous permissions.", ",dangerous", ",dangerous"),
      cmd("threats", "Live feed of currently detected threats and blocked actions.", ",threats", ",threats"),
      cmd("recover", "Undo the last destructive action (mass ban, mass delete, role wipe).", ",recover [action-id]", ",recover 42"),
      cmd("rollback", "Restore channels, roles, and permissions from a snapshot after a nuke attempt.", ",rollback <snapshot-id>", ",rollback last"),
      cmd("snapshot", "Take an on-demand snapshot of channels, roles, and permissions.", ",snapshot", ",snapshot"),
      cmd("snapshots", "List saved snapshots you can rollback to.", ",snapshots", ",snapshots"),
      cmd("panicmode", "Lock the entire server and quarantine every recent joiner in one command.", ",panicmode <on|off>", ",panicmode on"),
      cmd("raidmode", "Force raidmode: kick new joins, disable invites, tighten verification.", ",raidmode <on|off> [duration]", ",raidmode on 30m"),
      cmd("joingate", "Configure automatic join filters (account age, avatar, flagged names).", ",joingate <rule> <on|off> [value]", ",joingate noavatar on"),
      cmd("altdetect", "Detect and flag suspected alt accounts of banned members.", ",altdetect <on|off>", ",altdetect on"),
      cmd("namefilter", "Block or auto-rename members with blacklisted names.", ",namefilter <add|remove|list> [pattern]", ",namefilter add discord.gg/"),
      cmd("dehoist", "Auto-rename members using hoist characters to jump the member list.", ",dehoist <on|off>", ",dehoist on"),
      cmd("normalize", "Force-normalize unicode / zalgo / rtl usernames.", ",normalize <on|off>", ",normalize on"),
      cmd("suspicious", "Show accounts flagged as suspicious by the trust engine.", ",suspicious", ",suspicious"),
    ],
  },
  {
    slug: "anti",
    name: "Anti-Nuke & Anti-Raid",
    description:
      "Automated protections against nukes, raids, spam, and malicious insiders. Every rule has a threshold, a punishment, and a rollback path.",
    commands: [
      cmd("anti", "Overview of every anti-abuse module and their status.", ",anti", ",anti"),
      cmd("antinuke", "Configure the antinuke system that blocks mass channel/role/ban actions.", ",antinuke <module> <on|off> [punishment]", ",antinuke ban on strip"),
      cmd("antinuke punishment", "Set the default punishment for antinuke trips (strip / kick / ban / quarantine).", ",antinuke punishment <type>", ",antinuke punishment strip"),
      cmd("antinuke threshold", "Set how many destructive actions in a window trigger antinuke.", ",antinuke threshold <module> <count> <seconds>", ",antinuke threshold ban 3 60"),
      cmd("antinuke bypass", "Grant a role or user antinuke bypass (uses trusted list).", ",antinuke bypass <add|remove> <target>", ",antinuke bypass add @Admin"),
      cmd("antinuke logs", "View the antinuke event log.", ",antinuke logs [module]", ",antinuke logs ban"),
      cmd("anti channel", "Block mass channel create / delete / update.", ",anti channel <on|off> [punishment]", ",anti channel on strip"),
      cmd("anti role", "Block mass role create / delete / permission edits.", ",anti role <on|off> [punishment]", ",anti role on strip"),
      cmd("anti ban", "Block mass bans by non-owners.", ",anti ban <on|off> [punishment]", ",anti ban on ban"),
      cmd("anti kick", "Block mass kicks by non-owners.", ",anti kick <on|off> [punishment]", ",anti kick on strip"),
      cmd("anti prune", "Block mass member prune attempts.", ",anti prune <on|off> [punishment]", ",anti prune on strip"),
      cmd("anti webhook", "Block webhook create / update / delete outside approved staff.", ",anti webhook <on|off>", ",anti webhook on"),
      cmd("anti emoji", "Block mass emoji or sticker deletion.", ",anti emoji <on|off>", ",anti emoji on"),
      cmd("anti server", "Block edits to server name, icon, region, or vanity.", ",anti server <on|off>", ",anti server on"),
      cmd("anti permission", "Block dangerous permission changes to roles.", ",anti permission <on|off>", ",anti permission on"),
      cmd("anti mention", "Punish mass mentions in a single message.", ",anti mention <on|off> [max]", ",anti mention on 5"),
      cmd("anti invite", "Block invite links and third-party ads.", ",anti invite <on|off> [punishment]", ",anti invite on mute"),
      cmd("anti link", "Block all links except whitelisted domains.", ",anti link <on|off>", ",anti link on"),
      cmd("anti raid", "Automatically catch join raids and lock the server.", ",anti raid <on|off> [threshold]", ",anti raid on 10"),
      cmd("anti spam", "Detect and punish message spam.", ",anti spam <on|off> [threshold]", ",anti spam on 6"),
      cmd("anti flood", "Punish channel flooding with duplicate messages.", ",anti flood <on|off> [threshold]", ",anti flood on 4"),
      cmd("anti caps", "Punish excessive capital letters.", ",anti caps <on|off> [percent]", ",anti caps on 70"),
      cmd("anti emojispam", "Punish excessive emoji spam.", ",anti emojispam <on|off> [max]", ",anti emojispam on 10"),
      cmd("anti stickerspam", "Punish sticker spam.", ",anti stickerspam <on|off>", ",anti stickerspam on"),
      cmd("anti massmention", "Auto-punish members that mass mention roles or users.", ",anti massmention <on|off> [max]", ",anti massmention on 5"),
      cmd("anti selfbot", "Detect and punish suspected selfbots.", ",anti selfbot <on|off>", ",anti selfbot on"),
      cmd("anti nsfw", "Scan images for NSFW content and remove.", ",anti nsfw <on|off>", ",anti nsfw on"),
      cmd("anti scam", "Block known scam / phishing domains.", ",anti scam <on|off>", ",anti scam on"),
      cmd("anti token", "Detect and delete leaked Discord tokens.", ",anti token <on|off>", ",anti token on"),
      cmd("anti ghostping", "Warn or log members who ping then delete.", ",anti ghostping <on|off>", ",anti ghostping on"),
      cmd("anti bot", "Block new bots from being added without approval.", ",anti bot <on|off>", ",anti bot on"),
      cmd("anti newaccount", "Kick or quarantine accounts under X days old.", ",anti newaccount <on|off> [days]", ",anti newaccount on 7"),
      cmd("anti noavatar", "Kick or quarantine accounts with no avatar.", ",anti noavatar <on|off>", ",anti noavatar on"),
      cmd("anti vpn", "Block joins from known VPN / proxy IPs.", ",anti vpn <on|off>", ",anti vpn on"),
      cmd("anti dm", "Block ware from being DM'd by non-trusted users.", ",anti dm <on|off>", ",anti dm on"),
      cmd("anti impersonation", "Detect members impersonating staff by name or avatar.", ",anti impersonation <on|off>", ",anti impersonation on"),
      cmd("automod", "Enable Discord AutoMod rulesets managed by ware.", ",automod <rule> <on|off>", ",automod mentions on"),
      cmd("filter", "Manage the word/phrase filter.", ",filter <add|remove|list> [word]", ",filter add slur"),
      cmd("blacklist", "Block a user from using ware in your server.", ",blacklist <user> [reason]", ",blacklist @alex abuse"),
    ],
  },
  {
    slug: "voicemaster",
    name: "VoiceMaster",
    description: "Give members full control over their own voice channels.",
    commands: [
      cmd("voicemaster setup", "Create the voicemaster category and join-to-create channel.", ",voicemaster setup", ",voicemaster setup"),
      cmd("reset", "Reset your voice channel settings to defaults.", ",reset", ",reset"),
      cmd("sendinterface", "Post the voicemaster control panel in a channel.", ",sendinterface [channel]", ",sendinterface #voice-controls"),
      cmd("lock", "Lock your voice channel so no one else can join.", ",lock", ",lock"),
      cmd("unlock", "Unlock your voice channel.", ",unlock", ",unlock"),
      cmd("hide", "Hide your voice channel from the channel list.", ",hide", ",hide"),
      cmd("reveal", "Reveal your hidden voice channel.", ",reveal", ",reveal"),
      cmd("rename", "Rename your voice channel.", ",rename <name>", ",rename late night"),
      cmd("claim", "Claim ownership of a voice channel whose owner left.", ",claim", ",claim"),
      cmd("delete", "Delete your voice channel.", ",delete", ",delete"),
      cmd("limit", "Set the user limit on your voice channel.", ",limit <number>", ",limit 5"),
      cmd("bitrate", "Set the bitrate of your voice channel.", ",bitrate <kbps>", ",bitrate 96"),
      cmd("status", "Set the status text of your voice channel.", ",status <text>", ",status ranked grind"),
      cmd("permit", "Allow a specific user to join your locked channel.", ",permit <user>", ",permit @alex"),
      cmd("reject", "Kick a user from your channel and block them.", ",reject <user>", ",reject @troll"),
      cmd("drag", "Drag a user into your voice channel.", ",drag <user>", ",drag @alex"),
      cmd("temporary", "Toggle whether your channel deletes when empty.", ",temporary <on|off>", ",temporary off"),
      cmd("joinrole", "Set a role automatically given while in your channel.", ",joinrole <role>", ",joinrole @In-VC"),
      cmd("information", "Show info about the current voice channel.", ",information", ",information"),
    ],
  },
  {
    slug: "logging",
    name: "Logging",
    description: "Track everything happening in your server.",
    commands: [
      cmd("log", "Configure a log channel for a specific event.", ",log <event> <channel>", ",log messages #mod-logs"),
      cmd("logs", "List every configured log channel.", ",logs", ",logs"),
      cmd("audit", "Show recent audit log entries with filters.", ",audit [action] [user]", ",audit ban @alex"),
      cmd("case", "View a moderation case by ID.", ",case <id>", ",case 42"),
      cmd("cases", "List moderation cases for a member.", ",cases <user>", ",cases @alex"),
    ],
  },
  {
    slug: "welcome",
    name: "Welcome",
    description: "Onboarding, boosts, invites, and member events.",
    commands: [
      cmd("autorole", "Automatically assign roles when a member joins.", ",autorole <add|remove|list> [role]", ",autorole add @Member"),
      cmd("boostrole", "Give boosters a custom personal role.", ",boostrole <create|color|name> [value]", ",boostrole color #ff69b4"),
      cmd("boostmessage", "Set the message sent when someone boosts.", ",boostmessage <channel> <message>", ",boostmessage #general thanks {user}!"),
      cmd("counting", "Set up the counting game channel.", ",counting <channel>", ",counting #counting"),
      cmd("birthday", "Set your birthday for server shoutouts.", ",birthday <MM/DD>", ",birthday 04/12"),
      cmd("invite", "Create an invite for the current channel.", ",invite [channel]", ",invite #general"),
      cmd("inviteinfo", "Show info about an invite code.", ",inviteinfo <code>", ",inviteinfo penthouses"),
      cmd("invites", "Show how many invites a user has.", ",invites [user]", ",invites @alex"),
    ],
  },
  {
    slug: "economy",
    name: "Economy",
    description: "Currency, games, and a full server-side economy.",
    commands: [
      cmd("balance", "Show your or a user's wallet and bank balance.", ",balance [user]", ",balance @alex"),
      cmd("bank", "Manage your bank account.", ",bank", ",bank"),
      cmd("deposit", "Deposit money into your bank.", ",deposit <amount|all>", ",deposit all"),
      cmd("daily", "Claim your daily currency reward.", ",daily", ",daily"),
      cmd("beg", "Beg strangers for money.", ",beg", ",beg"),
      cmd("crime", "Commit a crime for a big payout or a big fine.", ",crime", ",crime"),
      cmd("heist", "Start or join a bank heist with other members.", ",heist [amount]", ",heist 500"),
      cmd("gamble", "Gamble your money on a coin flip.", ",gamble <amount>", ",gamble 250"),
      cmd("casino", "Open the casino menu.", ",casino", ",casino"),
      cmd("lottery", "Buy a lottery ticket for the daily draw.", ",lottery [tickets]", ",lottery 5"),
      cmd("market", "Browse the item market.", ",market [page]", ",market 2"),
      cmd("inventory", "Show items in your inventory.", ",inventory [user]", ",inventory"),
      cmd("buy", "Buy an item from the market.", ",buy <item> [amount]", ",buy fishing_rod"),
      cmd("fishing", "Go fishing to earn items and money.", ",fishing", ",fishing"),
    ],
  },
  {
    slug: "ai",
    name: "AI",
    description: "Chat, code, and image generation powered by AI.",
    commands: [
      cmd("ai", "Ask the default AI assistant a question.", ",ai <prompt>", ",ai explain quantum entanglement"),
      cmd("ask", "Ask a one-off question with no memory.", ",ask <question>", ",ask what time is it in tokyo"),
      cmd("gemini", "Ask Google Gemini directly.", ",gemini <prompt>", ",gemini summarize this article"),
      cmd("aichat", "Enable a channel as an ongoing AI chat.", ",aichat <channel> <on|off>", ",aichat #ai-chat on"),
      cmd("aicode", "Generate code from a description.", ",aicode <language> <prompt>", ",aicode python fibonacci function"),
      cmd("aiexplain", "Explain a code snippet.", ",aiexplain <code>", ",aiexplain `useEffect(() => {}, [])`"),
      cmd("aigrammar", "Fix grammar in a passage.", ",aigrammar <text>", ",aigrammar their going too the store"),
      cmd("aiimage", "Generate an image from a prompt.", ",aiimage <prompt>", ",aiimage a cat astronaut, oil painting"),
      cmd("essay", "Write an essay on a topic.", ",essay <topic>", ",essay the fall of rome"),
      cmd("explain", "Explain a concept in simple terms.", ",explain <topic>", ",explain black holes like i'm 5"),
      cmd("code", "Quick shorthand for aicode.", ",code <language> <prompt>", ",code js debounce util"),
    ],
  },
  {
    slug: "utility",
    name: "Utility",
    description: "Everyday tools your server actually needs.",
    commands: [
      cmd("help", "Show the help menu or details for a command.", ",help [command]", ",help ban"),
      cmd("prefix", "Show or change the server prefix.", ",prefix [set|reset] [symbol]", ",prefix set !"),
      cmd("avatar", "Show a user's avatar.", ",avatar [user]", ",avatar @alex"),
      cmd("banner", "Show a user's profile banner.", ",banner [user]", ",banner @alex"),
      cmd("userinfo", "Show info about a member.", ",userinfo [user]", ",userinfo @alex"),
      cmd("serverinfo", "Show info about the current server.", ",serverinfo", ",serverinfo"),
      cmd("membercount", "Show total, human, and bot counts.", ",membercount", ",membercount"),
      cmd("channelinfo", "Show info about a channel.", ",channelinfo [channel]", ",channelinfo #general"),
      cmd("emojiinfo", "Show info about a custom emoji.", ",emojiinfo <emoji>", ",emojiinfo :ware:"),
      cmd("google", "Search Google and return the top results.", ",google <query>", ",google discord.py docs"),
      cmd("github", "Look up a GitHub user or repo.", ",github <user|user/repo>", ",github torvalds/linux"),
      cmd("calculator", "Evaluate a math expression.", ",calculator <expression>", ",calculator (12+8)*3"),
      cmd("math", "Alias for calculator.", ",math <expression>", ",math sqrt(144)"),
      cmd("define", "Show a dictionary definition.", ",define <word>", ",define ephemeral"),
      cmd("crypto", "Show the current price of a crypto asset.", ",crypto <symbol>", ",crypto btc"),
      cmd("countdown", "Set a countdown timer in the channel.", ",countdown <duration> <label>", ",countdown 10m stream starts"),
      cmd("base64", "Encode or decode base64.", ",base64 <encode|decode> <text>", ",base64 encode hello"),
    ],
  },
  {
    slug: "fun",
    name: "Fun",
    description: "Games, minigames, and social commands.",
    commands: [
      cmd("8ball", "Ask the magic 8-ball a question.", ",8ball <question>", ",8ball will i win?"),
      cmd("coinflip", "Flip a coin.", ",coinflip", ",coinflip"),
      cmd("dice", "Roll a die.", ",dice [sides]", ",dice 20"),
      cmd("hangman", "Play a game of hangman.", ",hangman", ",hangman"),
      cmd("checkers", "Challenge someone to checkers.", ",checkers <user>", ",checkers @alex"),
      cmd("chess", "Challenge someone to chess.", ",chess <user>", ",chess @alex"),
      cmd("connect4", "Challenge someone to Connect Four.", ",connect4 <user>", ",connect4 @alex"),
      cmd("battleship", "Challenge someone to Battleship.", ",battleship <user>", ",battleship @alex"),
      cmd("higherlower", "Play higher or lower.", ",higherlower", ",higherlower"),
      cmd("fasttype", "Typing speed challenge.", ",fasttype", ",fasttype"),
      cmd("memorygame", "Match-pairs memory game.", ",memorygame", ",memorygame"),
      cmd("joke", "Send a random joke.", ",joke", ",joke"),
      cmd("hug", "Hug a member.", ",hug <user>", ",hug @alex"),
      cmd("kiss", "Kiss a member.", ",kiss <user>", ",kiss @alex"),
      cmd("cuddle", "Cuddle with a member.", ",cuddle <user>", ",cuddle @alex"),
      cmd("gay", "Fun gay-o-meter roast.", ",gay [user]", ",gay @alex"),
      cmd("howgay", "Rate how gay a member is (0-100%).", ",howgay [user]", ",howgay @alex"),
      cmd("howhot", "Rate how hot a member is (0-100%).", ",howhot [user]", ",howhot @alex"),
      cmd("braincells", "Count a member's braincells.", ",braincells [user]", ",braincells @alex"),
      cmd("delulu", "Rate how delulu a member is.", ",delulu [user]", ",delulu @alex"),
      cmd("marry", "Propose to a member.", ",marry <user>", ",marry @alex"),
    ],
  },
  {
    slug: "message-tools",
    name: "Message Tools",
    description: "Embeds, cloning, snipes, and message management.",
    commands: [
      cmd("embed", "Build a custom embed with the embed script.", ",embed <script>", ",embed {title: hello}{description: world}"),
      cmd("embeds", "List saved embeds in the server.", ",embeds", ",embeds"),
      cmd("message", "Send a message as ware to a channel.", ",message <channel> <content>", ",message #announcements hello"),
      cmd("copy", "Copy a specific message by link or id.", ",copy <message>", ",copy 111222333"),
      cmd("clone", "Clone a channel with all its settings.", ",clone [channel]", ",clone #general"),
      cmd("cloneuser", "Clone a member's roles onto another.", ",cloneuser <from> <to>", ",cloneuser @alex @jamie"),
      cmd("cleanup", "Delete ware's own recent messages.", ",cleanup [amount]", ",cleanup 20"),
      cmd("editsnipe", "Show the most recently edited message.", ",editsnipe [channel]", ",editsnipe"),
      cmd("clearsnipe", "Clear the snipe cache for the channel.", ",clearsnipe", ",clearsnipe"),
      cmd("firstmessage", "Show the first message ever sent in a channel.", ",firstmessage [channel]", ",firstmessage #general"),
    ],
  },
  {
    slug: "administration",
    name: "Administration",
    description: "Server-wide controls and configuration.",
    commands: [
      cmd("backup", "Create a full backup of the server.", ",backup <create|load|list> [id]", ",backup create"),
      cmd("dashboard", "Open the web dashboard for this server.", ",dashboard", ",dashboard"),
      cmd("config", "View or edit ware's configuration.", ",config [module]", ",config welcome"),
      cmd("load", "Load a saved backup into the server.", ",load <backup-id>", ",load 8d0f1"),
      cmd("import", "Import config from another server.", ",import <server-id>", ",import 940382019283740192"),
      cmd("export", "Export the current server config.", ",export", ",export"),
      cmd("execute", "Run a raw command as ware.", ",execute <command>", ",execute ban @alex"),
      cmd("force", "Force an action ignoring hierarchy checks.", ",force <command> <args>", ",force strip @alex"),
      cmd("forcerole", "Force-add a role bypassing role locks.", ",forcerole <user> <role>", ",forcerole @alex @Admin"),
      cmd("forcetimeout", "Force-timeout a member.", ",forcetimeout <user> <duration>", ",forcetimeout @alex 1h"),
      cmd("forceavatar", "Force change a member's server avatar.", ",forceavatar <user> <url>", ",forceavatar @alex https://.../a.png"),
      cmd("ghost", "Ghost mode: run commands invisibly.", ",ghost <command>", ",ghost ban @alex"),
    ],
  },
];
