export type WareCommandDoc = {
  name: string;
  description: string;
  usage: string;
  example: string;
  aliases?: string[];
  permission?: string;
};

const lfm = (
  name: string,
  description: string,
  usage: string,
  permission = "None",
  aliases?: string[],
): WareCommandDoc => ({ name, description, usage, example: usage, permission, aliases });

export const lastFmCategory = {
  slug: "lastfm",
  name: "Last.fm",
  description: "Connect Last.fm, view scrobbles, compare music taste, and explore listening statistics.",
  commands: [
    lfm("lastfm", "Integrate your Last.fm account with Ware and view your scrobble stats.", ",lastfm"),
    lfm("lastfm mode", "Use a different embed for Now Playing or create your own.", ",lastfm mode (type)", "Tier 1 Only"),
    lfm("lastfm color", "Set the embed color for Last.fm commands.", ",lastfm color (hex)"),
    lfm("lastfm logout", "Remove your Last.fm account from Ware's internal system.", ",lastfm logout"),
    lfm("lastfm taste", "Compare your music taste with another member.", ",lastfm taste (member) (period)"),
    lfm("lastfm playsall", "Check how many plays you have for every song on an album.", ",lastfm playsall (member) (artist and album)"),
    lfm("lastfm update", "Update and validate your Last.fm library connection.", ",lastfm update (parameters)"),
    lfm("lastfm topartists", "View your most listened-to artists.", ",lastfm topartists (member) (period)"),
    lfm("lastfm playsalbum", "Check how many plays you have for an album.", ",lastfm playsalbum (member) (artist and album)"),
    lfm("lastfm toptracks", "View your most listened-to tracks.", ",lastfm toptracks (member) (period)"),
    lfm("lastfm favorites", "View yours or a member's liked tracks.", ",lastfm favorites (member)"),
    lfm("lastfm milestone", "See what track your given-number scrobble was.", ",lastfm milestone (number)"),
    lfm("lastfm streak", "View your current listening streak.", ",lastfm streak (member)"),
    lfm("lastfm playstrack", "Check how many plays you have for a specific track.", ",lastfm playstrack (member) (artist and track)"),
    lfm("lastfm count", "View your total Last.fm scrobbles.", ",lastfm count (member)"),
    lfm("lastfm topalbums", "View your most listened-to albums.", ",lastfm topalbums (member) (period)"),
    lfm("lastfm collage", "View a collage of your most listened-to albums.", ",lastfm collage (member) (rows x cols) (period)"),
    lfm("lastfm hide", "Hide users from appearing on whoknows commands.", ",lastfm hide (member)", "Manage Guild"),
    lfm("lastfm hide list", "View the list of hidden members.", ",lastfm hide list"),
    lfm("lastfm whois", "View Last.fm profile information.", ",lastfm whois (member)"),
    lfm("lastfm url", "Submit custom artwork for an album instead of the Last.fm artwork.", ",lastfm url (url) (album)"),
    lfm("lastfm lyrics", "Get lyrics for the current song playing.", ",lastfm lyrics (member)"),
    lfm("lastfm whoknows", "View the top listeners for an artist in a server.", ",lastfm whoknows (artist)", "None", ["wk"]),
    lfm("lastfm soundcloud", "Get a SoundCloud link for the current song playing.", ",lastfm soundcloud (member)"),
    lfm("lastfm playing", "See what song everyone is listening to in a server.", ",lastfm playing"),
    lfm("lastfm vote", "Vote for submitted album artwork to display on Now Playing.", ",lastfm vote (artist and album)"),
    lfm("lastfm itunes", "Get an iTunes link for the current song playing.", ",lastfm itunes (member)"),
    lfm("lastfm recommendation", "Recommend a random artist from your library.", ",lastfm recommendation (member)"),
    lfm("lastfm toptenalbums", "View your top ten albums for an artist.", ",lastfm toptenalbums (member) (artist)"),
    lfm("lastfm score", "View your Last.fm score and statistics.", ",lastfm score (member)"),
    lfm("lastfm customreactions", "Set personal upvote and downvote reactions for Now Playing.", ",lastfm customreactions (upvote) (downvote)", "Tier 1 Only"),
    lfm("lastfm spotify", "Get a Spotify link for the current song playing.", ",lastfm spotify (member)"),
    lfm("lastfm customcommand", "Set your own custom Now Playing command.", ",lastfm customcommand (substring)"),
    lfm("lastfm customcommand list", "View the list of custom Now Playing commands.", ",lastfm customcommand list", "Manage Guild"),
    lfm("lastfm customcommand reset", "Reset all custom Now Playing commands.", ",lastfm customcommand reset", "Manage Guild"),
    lfm("lastfm customcommand cleanup", "Clean up custom commands from absent members.", ",lastfm customcommand cleanup", "Administrator"),
    lfm("lastfm customcommand remove", "Remove a custom command for a member.", ",lastfm customcommand remove (member)", "Manage Guild"),
    lfm("lastfm customcommand public", "Toggle the public flag for a custom command.", ",lastfm customcommand public (substring)", "Manage Guild"),
    lfm("lastfm customcommand blacklist", "Blacklist users from using their own Now Playing command.", ",lastfm customcommand blacklist (member)", "Manage Guild"),
    lfm("lastfm customcommand blacklist list", "View blacklisted custom-command users for Now Playing.", ",lastfm customcommand blacklist list", "Manage Guild"),
    lfm("lastfm globalwhoknows", "View the top listeners for an artist globally.", ",lastfm globalwhoknows (artist)"),
    lfm("lastfm react", "Set server upvote and downvote reactions for Now Playing.", ",lastfm react (upvote) (downvote)", "Manage Guild"),
    lfm("lastfm globalboard", "View the Last.fm global scoreboard.", ",lastfm globalboard"),
    lfm("lastfm youtube", "Get a YouTube link for the current song playing.", ",lastfm youtube (member)"),
    lfm("lastfm globalwktrack", "View the top listeners for a track globally.", ",lastfm globalwktrack (artist)"),
    lfm("lastfm scoreboard", "View the Last.fm server scoreboard.", ",lastfm scoreboard"),
    lfm("lastfm now", "Show your current song playing from Last.fm.", ",lastfm now (member)", "None", ["np"]),
    lfm("lastfm mostcrowns", "View a list of members with the most crowns.", ",lastfm mostcrowns"),
    lfm("lastfm globalwkalbum", "View the top listeners for an album globally.", ",lastfm globalwkalbum (artist)"),
    lfm("lastfm wktrack", "View the top listeners for a specific song by an artist.", ",lastfm wktrack (track)"),
    lfm("lastfm recent", "View your recent tracks.", ",lastfm recent (member)"),
    lfm("lastfm crowns", "View a list of your crowns.", ",lastfm crowns (member)"),
    lfm("lastfm toptentracks", "View your top ten tracks for an artist.", ",lastfm toptentracks (member) (artist)"),
    lfm("lastfm overview", "See your statistics for an artist.", ",lastfm overview (member) (artistname)"),
    lfm("lastfm wkalbum", "View the top listeners for an album by an artist.", ",lastfm wkalbum (album)"),
    lfm("lastfm recentfor", "View your recent tracks for an artist.", ",lastfm recentfor (artist)"),
    lfm("lastfm plays", "Check how many plays you have for an artist.", ",lastfm plays (member) (artist)"),
    lfm("lastfm login", "Login and authenticate Ware to use your Last.fm account.", ",lastfm login"),
    lfm("nowplaying", "Show your current song playing from Last.fm.", ",nowplaying (member)", "None", ["np"]),
    lfm("itunes", "Find a song using the iTunes API.", ",itunes (song)"),
    lfm("spotifyalbum", "Find album results from the Spotify API.", ",spotifyalbum (album)"),
    lfm("spotifytrack", "Find track results from the Spotify API.", ",spotifytrack (track)"),
  ],
};
