export type ReferenceCommand = {
  name: string;
  description: string;
  usage: string;
  example: string;
  aliases?: string[];
  permission?: string;
};

const cmd = (
  name: string,
  description: string,
  args: string[] = [],
  permission = "None",
): ReferenceCommand => ({
  name,
  description,
  usage: `,${name}${args.length ? ` ${args.map(arg => `(${arg})`).join(" ")}` : ""}`,
  example: `,${name}${args.length ? ` ${args.map(arg => `<${arg}>`).join(" ")}` : ""}`,
  permission,
});

export const referenceCommandCategories = [
  {
    slug: "crypto",
    name: "Crypto",
    description: "Prices, gas, transaction lookups, and confirmation alerts.",
    commands: [
      cmd("crypto", "Checks the current price of the specified cryptocurrency", ["crypto", "cur"]),
      cmd("subscribe", "Subscribe to a bitcoin transaction for one confirmation", ["hash"]),
      cmd("transaction", "Get information about a BTC, LTC or ETH transaction", ["hash"]),
      cmd("gas", "View the current gas prices"),
    ],
  },
  {
    slug: "snipe",
    name: "Snipe",
    description: "Deleted, edited, and removed-reaction history tools.",
    commands: [
      cmd("clearsnipe", "Clear all results for reactions, edits and messages", [], "Manage Messages"),
      cmd("reactionhistory", "See logged reactions for a message", ["messagelink"], "Manage Messages"),
      cmd("reactionsnipe", "Snipe the latest reaction that was removed"),
      cmd("editsnipe", "Snipe the latest message that was edited"),
      cmd("snipe", "Snipe the latest message that was deleted"),
    ],
  },
  {
    slug: "counters",
    name: "Counters",
    description: "Live server statistic counters backed by channel names.",
    commands: [
      cmd("counter", "Create counters for everybody to see", [], "Manage Channels"),
      cmd("counter set", "Set a channel counter to an existing channel", ["channel", "option"], "Manage Channels"),
      cmd("counter list", "List every counter available in this server", [], "Manage Channels"),
      cmd("counter remove", "Remove a channel counter", ["channel", "action"], "Manage Channels"),
      cmd("counter add", "Create channel counter", ["option", "channel"], "Manage Channels"),
    ],
  },
  {
    slug: "timers",
    name: "Timers",
    description: "Recurring server messages and activity controls.",
    commands: [
      cmd("timer", "Post repeating messages in your server", [], "Manage Guild"),
      cmd("timer list", "View all auto messages in your server", [], "Manage Guild"),
      cmd("timer remove", "Remove repeating message from a channel", ["channel"], "Manage Guild"),
      cmd("timer view", "Preview a channel's auto message", ["channel"], "Manage Guild"),
      cmd("timer add", "Add repeating message to a channel", ["channel", "interval", "message"], "Manage Guild"),
      cmd("timer activity", "Enable or disable channel activity requirement", ["setting"], "Manage Guild"),
    ],
  },
  {
    slug: "twitch",
    name: "Twitch",
    description: "Profile lookups and live-stream notifications.",
    commands: [
      cmd("twitch", "Check a Twitch profile or set up stream notifications", ["username"]),
      cmd("twitch remove", "Remove stream notifications from a channel", ["channel", "streamer"], "Manage Guild"),
      cmd("twitch message", "Set a message for Twitch notifications", ["streamer", "message"], "Manage Guild"),
      cmd("twitch message view", "View Twitch message for new streams", ["streamer"], "Manage Guild"),
      cmd("twitch add", "Add stream notifications to a channel", ["channel", "streamer"], "Manage Guild"),
      cmd("twitch list", "View all Twitch stream notifications", [], "Manage Guild"),
    ],
  },
  {
    slug: "youtube",
    name: "YouTube",
    description: "Video search and channel upload notifications.",
    commands: [
      cmd("youtube", "Search YouTube for video results", ["search"]),
      cmd("youtube list", "View all YouTube post notifications", [], "Manage Guild"),
      cmd("youtube remove", "Disable post notifications for a channel", ["channel", "channelurl"], "Manage Guild"),
      cmd("youtube message", "Customize the message for YouTube notifications", ["channelurl", "message"], "Manage Guild"),
      cmd("youtube message view", "View YouTube message for new posts", ["channelurl"], "Manage Guild"),
      cmd("youtube add", "Enable post notifications to a channel", ["channel", "channelurl"], "Manage Guild"),
    ],
  },
  {
    slug: "logs",
    name: "Logs",
    description: "Logging channels, ignored targets, and per-event colors.",
    commands: [
      cmd("log", "Set up logging for your community", [], "Manage Guild"),
      cmd("log remove", "Remove events from a logging channel", ["channel", "event"], "Manage Guild"),
      cmd("log ignore", "Ignore a member or channel from being logged", ["member or channel"], "Manage Guild"),
      cmd("log ignore list", "View all ignored members and channels", [], "Manage Guild"),
      cmd("log color", "Customize embed color for an event", ["channel", "event", "color"], "Manage Guild"),
      cmd("log color list", "List embed color customization for events", ["channel"], "Manage Guild"),
    ],
  },
  {
    slug: "twitter",
    name: "X / Twitter",
    description: "Profile lookups and new-post feeds from X.",
    commands: [
      cmd("twitter", "Gets profile information on the given Twitter user", ["handle"]),
      cmd("twitter remove", "Remove feed for new tweets", ["channel", "handle"], "Manage Channels"),
      cmd("twitter add", "Create feed for new tweets from a user", ["channel", "handle"], "Manage Channels"),
      cmd("twitter message", "Set a message for new tweets", ["handle", "message"], "Manage Channels"),
      cmd("twitter message view", "View Twitter message for new tweets", ["handle"], "Manage Channels"),
      cmd("twitter list", "View a list of every Twitter feed", [], "Manage Channels"),
    ],
  },
  {
    slug: "fortnite",
    name: "Fortnite",
    description: "Item information, shop updates, pings, voting, and watches.",
    commands: [
      cmd("fortnite", "Set automatic Fortnite Shop rotation updates", [], "Manage Guild"),
      cmd("fortnite shop", "Set channel for Item Shop updates", ["channel"], "Manage Guild"),
      cmd("fortnite shop ping", "Set role for Item Shop updates", ["role"], "Manage Guild"),
      cmd("fortnite shop voting", "Set voting for Item Shop updates", ["setting"], "Manage Guild"),
      cmd("fortnite item", "View information on a Fortnite cosmetic item", ["name"]),
      cmd("fortnite watch", "Set reminder for an item", ["item"]),
    ],
  },
  {
    slug: "antiraid",
    name: "AntiRaid",
    description: "Join protection, account-age rules, avatar rules, and raid state.",
    commands: [
      cmd("antiraid", "Configure protection against potential raids", [], "Manage Guild"),
      cmd("antiraid newaccounts", "Punish new registered accounts", ["setting", "flags"], "Manage Guild"),
      cmd("antiraid whitelist", "Create a one-time whitelist to allow a user to join", ["member"], "Manage Guild"),
      cmd("antiraid whitelist view", "View all current antiraid whitelists", [], "Manage Guild"),
      cmd("antiraid avatar", "Punish accounts without a profile picture", ["setting", "flags"], "Manage Guild"),
      cmd("antiraid config", "View server antiraid configuration", [], "Manage Guild"),
      cmd("antiraid state", "Turn off server's raid state", [], "Manage Guild"),
      cmd("antiraid massjoin", "Protect server against mass bot raids", ["setting", "flags"], "Manage Guild"),
    ],
  },
  {
    slug: "bump-reminder",
    name: "Bump Reminder",
    description: "Disboard bump reminders, channel controls, and cleanup behavior.",
    commands: [
      cmd("bumpreminder", "Get reminders to /bump your server on Disboard!", ["setting"], "Manage Channels"),
      cmd("bumpreminder autoclean", "Automatically delete messages that aren't /bump", ["choice"], "Manage Channels"),
      cmd("bumpreminder channel", "Set Bump Reminder channel for the server", ["channel"], "Manage Channels"),
      cmd("bumpreminder autolock", "Lock channel until ready to use /bump", ["choice"], "Manage Channels"),
      cmd("bumpreminder message", "Set the reminder message to run /bump", ["message"], "Manage Channels"),
      cmd("bumpreminder message view", "View the current remind message", [], "Manage Channels"),
    ],
  },
  {
    slug: "utility",
    name: "Utility",
    description: "Useful server tools, expression copying, and general utilities.",
    commands: [
      cmd("steal", "Copy custom Discord emojis from other servers into the current server", ["emojis"], "Manage Expressions"),
      cmd("steal-sticker", "Copy a Discord sticker into the current server from a Discord message link", ["message link"], "Manage Expressions"),
    ],
  },
  {
    slug: "manipulation",
    name: "Manipulation",
    description: "Image, GIF, and video manipulation tools.",
    commands: [
      cmd("media", "Image manipulation for photos, videos and GIFs"),
      cmd("media flag", "Put a selected image onto a flag GIF", ["url or attachment"], "Attach Files"),
      cmd("media gifmagik", "Create a gif of the magik filter being applied on a given photo", ["url or attachment"], "Attach Files"),
      cmd("media toaster", "Generate your image on a toaster GIF", ["url or attachment"], "Attach Files"),
      cmd("media pixelate", "Pixelate a given image", ["url or attachment"], "Attach Files"),
      cmd("media billboard", "Put your photo on a billboard", ["url or attachment"], "Attach Files"),
      cmd("media bloom", "Apply a bloom effect to an image", ["url or attachment", "radius", "brightness", "sharpness"], "Attach Files"),
      cmd("media speed", "Change the speed of a video", ["url or attachment", "multiplier"], "Attach Files"),
      cmd("media motivate", "Create a motivation meme using your image and custom text", ["url or attachment", "top", "bottom"], "Attach Files"),
      cmd("media rubiks", "Put your image onto a rubiks cube", ["url or attachment"], "Attach Files"),
      cmd("media flag2", "Put a selected image onto a flag GIF", ["url or attachment"], "Attach Files"),
      cmd("media tattoo", "Tattoo your photo onto a body", ["url or attachment"], "Attach Files"),
      cmd("media spin", "Create a gif of your selected photo rotating clockwise", ["url or attachment"], "Attach Files"),
      cmd("media fisheye", "Apply a fisheye filter onto a photo", ["url or attachment"], "Attach Files"),
      cmd("media magik", "Apply the Magik filter to a photo", ["url or attachment"], "Attach Files"),
      cmd("media grayscale", "Apply a greyscale filter to a photo", ["url or attachment"], "Attach Files"),
      cmd("media blur", "Blur an image", ["url or attachment", "strength"], "Attach Files"),
      cmd("media circuitboard", "Put your picture on a circuitboard GIF", ["url or attachment"], "Attach Files"),
      cmd("media caption", "Create your own caption meme using an image", ["url or attachment", "text"], "Attach Files"),
      cmd("media neon", "Create a neon effect using the outlines in the picture provided", ["url or attachment"], "Attach Files"),
      cmd("media scramble", "Randomise frames within the given media", ["url or attachment"], "Attach Files"),
      cmd("media deepfry", "Apply a deepfried filter to a photo", ["url or attachment"], "Attach Files"),
      cmd("media fortune", "Put a given image inside a fortune cookie", ["url or attachment"], "Attach Files"),
      cmd("media valentine", "Use your photo in a valentines gif", ["url or attachment"], "Attach Files"),
      cmd("media invert", "Invert an image's colours", ["url or attachment"], "Attach Files"),
      cmd("media swirl", "Apply a swirl filter to a photo", ["url or attachment", "strength"], "Attach Files"),
      cmd("media speechbubble", "Create a quotation meme using a photo", ["url or attachment"], "Attach Files"),
      cmd("media heart", "Create a heart gif with your desired photo and caption", ["url or attachment", "text"], "Attach Files"),
      cmd("media book", "Put your photo in a book", ["url or attachment"], "Attach Files"),
      cmd("media reverse", "Reverse the playback of a video", ["url or attachment"], "Attach Files"),
      cmd("media meme", "Create a top and bottom text meme", ["url or attachment", "top", "bottom"], "Attach Files"),
      cmd("media rainbow", "Apply an animated rainbow color effect to your photo", ["url or attachment"], "Attach Files"),
      cmd("media zoom", "Create a zooming gif using your photo", ["url or attachment"], "Attach Files"),
      cmd("media zoomblur", "Apply a zoom blur effect onto your photo", ["url or attachment"], "Attach Files"),
      cmd("media spread", "Apply a paint spread filter to a photo", ["url or attachment", "strength"], "Attach Files"),
      cmd("media wormhole", "Create a wormhole animation using a photo", ["url or attachment"], "Attach Files"),
    ],
  },
  {
    slug: "miscellaneous",
    name: "Miscellaneous",
    description: "Embed creation, management, and related message tools.",
    commands: [
      cmd("embed", "Manage and create new embeds easily"),
      cmd("embed list", "List all available embeds"),
      cmd("embed copy", "Copy an existing embed's code for creating an embed", ["embed"]),
      cmd("embed delete", "Delete a stored embed", ["embed"]),
      cmd("embed preview", "Send an existing embed", ["embed"]),
      cmd("embed create", "Start customization for an embed"),
      cmd("editembed", "Edit an embed you created", ["embed"]),
      cmd("createembed", "Create your own embed"),
      cmd("embedcode", "Copy an existing embed's code for creating an embed", ["embed"]),
      cmd("purge embeds", "Purge embeds from chat", ["amount"], "Manage Messages"),
      cmd("pinterest embeds", "Enable or disable embeds for new pins", ["setting"], "Manage Guild"),
      cmd("reposter embed", "Enable or disable embed attached to media", ["setting"], "Manage Guild"),
    ],
  },
] as const;