import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowLeft, Search } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { DocsLayout } from "@/components/docs/DocsLayout";
import { commandCategories } from "@/lib/commands";
const WARE_IMAGE="/6ef1b8a8-6882-4b66-a59f-22f2bf408ca8.png";
function commandAnchor(name:string){return `command-${name.toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"")}`;}
export const Route=createFileRoute("/docs/commands")({head:()=>({meta:[{title:"Commands — ware docs"},{name:"description",content:"Browse all Ware commands and categories."}]}),component:CommandsIndex});
function CommandsIndex(){
 const [query,setQuery]=useState(""); const [category,setCategory]=useState("all"); const [loaderVisible,setLoaderVisible]=useState(true); const [loaderLeaving,setLoaderLeaving]=useState(false);
 useEffect(()=>{const a=window.setTimeout(()=>setLoaderLeaving(true),480);const b=window.setTimeout(()=>setLoaderVisible(false),800);return()=>{clearTimeout(a);clearTimeout(b);};},[]);
 const allCommands=useMemo(()=>commandCategories.flatMap(group=>group.commands.map(command=>({...command,category:group.name,categorySlug:group.slug}))),[]);
 const visibleCommands=useMemo(()=>{const q=query.trim().toLowerCase();return allCommands.filter(command=>(category==="all"||command.categorySlug===category)&&(!q||command.name.toLowerCase().includes(q)||command.description.toLowerCase().includes(q)||command.usage.toLowerCase().includes(q)||command.category.toLowerCase().includes(q)||(command.aliases??[]).some(alias=>alias.toLowerCase().includes(q))));},[allCommands,category,query]);
 const activeName=category==="all"?"All Commands":commandCategories.find(group=>group.slug===category)?.name??"Commands";
 return <>{loaderVisible&&<div className={`fixed inset-0 z-[120] grid place-items-center bg-[#050505] transition-all duration-300 ${loaderLeaving?"pointer-events-none scale-[1.04] opacity-0":"scale-100 opacity-100"}`}><div className="flex flex-col items-center gap-4"><div className="relative h-20 w-20 overflow-hidden rounded-[22px] border border-white/15 bg-white/[0.035] shadow-[0_0_80px_rgba(255,255,255,.08)]"><img src={WARE_IMAGE} alt="Ware" className="h-full w-full object-cover"/><div className="absolute inset-0 animate-pulse bg-white/[0.045]"/></div><span className="font-mono text-[10px] uppercase tracking-[0.3em] text-white/40">commands</span></div></div>}
 <DocsLayout active="commands" toc={[{id:"all-commands",label:"All Commands"}]}>
  <div className="rounded-[26px] border border-white/[0.08] bg-gradient-to-b from-white/[0.045] to-transparent p-5 md:p-7"><p className="text-[10px] font-semibold uppercase tracking-[0.2em] text-white/35">Command Center</p><h1 className="mt-3 text-4xl font-bold tracking-[-0.05em] md:text-6xl">All Commands</h1><p className="mt-4 max-w-2xl text-base leading-7 text-muted-foreground">Browse Ware's full command library. Pick a category or search by command, alias, usage, or feature.</p></div>
  <div className="mt-10 rounded-[24px] border border-white/10 bg-white/[0.025] p-3 shadow-[0_18px_70px_-45px_rgba(255,255,255,.2)] sm:p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-center"><label className="group flex min-w-0 flex-1 items-center gap-3 rounded-2xl border border-white/10 bg-black/30 px-4 py-3.5 text-sm text-muted-foreground transition-all focus-within:border-white/25 focus-within:bg-white/[0.045]"><Search className="h-4 w-4 shrink-0 group-focus-within:text-white"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search Ware commands..." className="min-w-0 flex-1 bg-transparent text-white outline-none placeholder:text-white/28" aria-label="Search commands"/></label><Link to="/" className="inline-flex h-12 shrink-0 items-center justify-center gap-2 rounded-2xl border border-white/10 bg-white/[0.04] px-5 text-xs font-medium transition-all hover:border-white/20 hover:bg-white/[0.08]"><ArrowLeft className="h-3.5 w-3.5"/>Home</Link></div></div>
  <div className="mt-5 overflow-x-auto pb-3 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden"><div className="flex min-w-max items-center gap-2"><button onClick={()=>setCategory("all")} className={`rounded-2xl border px-4 py-2.5 text-xs font-semibold transition-all ${category==="all"?"border-white/25 bg-white text-black":"border-white/10 bg-white/[0.025] text-white/60 hover:bg-white/[0.07] hover:text-white"}`}>All Commands</button>{commandCategories.map(group=><button key={group.slug} onClick={()=>setCategory(group.slug)} className={`rounded-2xl border px-4 py-2.5 text-xs transition-all ${category===group.slug?"border-white/25 bg-white text-black":"border-white/10 bg-white/[0.025] text-white/60 hover:bg-white/[0.07] hover:text-white"}`}>{group.name}</button>)}</div></div>
  <section id="all-commands" className="mt-7"><div className="border-b border-white/[0.07] pb-5"><p className="text-[10px] font-semibold uppercase tracking-[0.18em] text-white/32">Command library</p><h2 className="mt-2 text-2xl font-semibold tracking-tight">{activeName}</h2></div>
  {visibleCommands.length===0?<div className="mt-6 rounded-2xl border border-white/[0.08] bg-white/[0.02] px-5 py-14 text-center text-sm text-muted-foreground">No commands match “{query}”.</div>:<div className="mt-6 grid grid-cols-1 gap-3 md:grid-cols-2 xl:grid-cols-3">{visibleCommands.map((command,index)=><article key={`${command.category}-${command.name}-${index}`} id={commandAnchor(command.name)} className="group scroll-mt-28 rounded-2xl border border-white/[0.08] bg-white/[0.022] p-4 transition-all duration-200 hover:-translate-y-0.5 hover:border-white/[0.18] hover:bg-white/[0.045]"><div className="flex items-start justify-between gap-3"><span className="max-w-full truncate rounded-lg border border-white/[0.11] bg-white/[0.07] px-2.5 py-1.5 text-sm font-semibold">,{command.name}</span><span className="shrink-0 rounded-full border border-white/[0.07] px-2 py-1 text-[9px] uppercase tracking-[0.12em] text-white/35">{command.category}</span></div><p className="mt-3 text-sm leading-6 text-white/65">{command.description}</p><div className="mt-4 border-t border-white/[0.06] pt-3 font-mono text-[11px] leading-5 text-white/40">{command.usage}</div>{command.aliases&&command.aliases.length>0&&<div className="mt-3 flex flex-wrap gap-1.5">{command.aliases.slice(0,4).map(alias=><span key={alias} className="rounded-md border border-white/[0.06] bg-white/[0.02] px-2 py-1 font-mono text-[10px] text-white/38">,{alias}</span>)}</div>}</article>)}</div>}</section>
 </DocsLayout></>;
}
