/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DocsSlugRouteImport } from './routes/docs.$slug'
import { Route as DashboardGuildIdTicketsRouteImport } from './routes/dashboard.$guildId.tickets'
import { Route as ApiPublicAuthDiscordLogoutRouteImport } from './routes/api/public/auth/discord/logout'
import { Route as ApiPublicAuthDiscordLoginRouteImport } from './routes/api/public/auth/discord/login'
import { Route as ApiPublicAuthDiscordCallbackRouteImport } from './routes/api/public/auth/discord/callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSlugRoute = DocsSlugRouteImport.update({
  id: '/docs/$slug',
  path: '/docs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardGuildIdTicketsRoute = DashboardGuildIdTicketsRouteImport.update({
  id: '/dashboard/$guildId/tickets',
  path: '/dashboard/$guildId/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAuthDiscordLogoutRoute =
  ApiPublicAuthDiscordLogoutRouteImport.update({
    id: '/api/public/auth/discord/logout',
    path: '/api/public/auth/discord/logout',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAuthDiscordLoginRoute =
  ApiPublicAuthDiscordLoginRouteImport.update({
    id: '/api/public/auth/discord/login',
    path: '/api/public/auth/discord/login',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAuthDiscordCallbackRoute =
  ApiPublicAuthDiscordCallbackRouteImport.update({
    id: '/api/public/auth/discord/callback',
    path: '/api/public/auth/discord/callback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/dashboard/$guildId/tickets': typeof DashboardGuildIdTicketsRoute
  '/api/public/auth/discord/callback': typeof ApiPublicAuthDiscordCallbackRoute
  '/api/public/auth/discord/login': typeof ApiPublicAuthDiscordLoginRoute
  '/api/public/auth/discord/logout': typeof ApiPublicAuthDiscordLogoutRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/dashboard': typeof DashboardIndexRoute
  '/docs': typeof DocsIndexRoute
  '/dashboard/$guildId/tickets': typeof DashboardGuildIdTicketsRoute
  '/api/public/auth/discord/callback': typeof ApiPublicAuthDiscordCallbackRoute
  '/api/public/auth/discord/login': typeof ApiPublicAuthDiscordLoginRoute
  '/api/public/auth/discord/logout': typeof ApiPublicAuthDiscordLogoutRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/dashboard/$guildId/tickets': typeof DashboardGuildIdTicketsRoute
  '/api/public/auth/discord/callback': typeof ApiPublicAuthDiscordCallbackRoute
  '/api/public/auth/discord/login': typeof ApiPublicAuthDiscordLoginRoute
  '/api/public/auth/discord/logout': typeof ApiPublicAuthDiscordLogoutRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs/$slug'
    | '/dashboard/'
    | '/docs/'
    | '/dashboard/$guildId/tickets'
    | '/api/public/auth/discord/callback'
    | '/api/public/auth/discord/login'
    | '/api/public/auth/discord/logout'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs/$slug'
    | '/dashboard'
    | '/docs'
    | '/dashboard/$guildId/tickets'
    | '/api/public/auth/discord/callback'
    | '/api/public/auth/discord/login'
    | '/api/public/auth/discord/logout'
  id:
    | '__root__'
    | '/'
    | '/docs/$slug'
    | '/dashboard/'
    | '/docs/'
    | '/dashboard/$guildId/tickets'
    | '/api/public/auth/discord/callback'
    | '/api/public/auth/discord/login'
    | '/api/public/auth/discord/logout'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsSlugRoute: typeof DocsSlugRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DocsIndexRoute: typeof DocsIndexRoute
  DashboardGuildIdTicketsRoute: typeof DashboardGuildIdTicketsRoute
  ApiPublicAuthDiscordCallbackRoute: typeof ApiPublicAuthDiscordCallbackRoute
  ApiPublicAuthDiscordLoginRoute: typeof ApiPublicAuthDiscordLoginRoute
  ApiPublicAuthDiscordLogoutRoute: typeof ApiPublicAuthDiscordLogoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$slug': {
      id: '/docs/$slug'
      path: '/docs/$slug'
      fullPath: '/docs/$slug'
      preLoaderRoute: typeof DocsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$guildId/tickets': {
      id: '/dashboard/$guildId/tickets'
      path: '/dashboard/$guildId/tickets'
      fullPath: '/dashboard/$guildId/tickets'
      preLoaderRoute: typeof DashboardGuildIdTicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auth/discord/logout': {
      id: '/api/public/auth/discord/logout'
      path: '/api/public/auth/discord/logout'
      fullPath: '/api/public/auth/discord/logout'
      preLoaderRoute: typeof ApiPublicAuthDiscordLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auth/discord/login': {
      id: '/api/public/auth/discord/login'
      path: '/api/public/auth/discord/login'
      fullPath: '/api/public/auth/discord/login'
      preLoaderRoute: typeof ApiPublicAuthDiscordLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auth/discord/callback': {
      id: '/api/public/auth/discord/callback'
      path: '/api/public/auth/discord/callback'
      fullPath: '/api/public/auth/discord/callback'
      preLoaderRoute: typeof ApiPublicAuthDiscordCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsSlugRoute: DocsSlugRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DocsIndexRoute: DocsIndexRoute,
  DashboardGuildIdTicketsRoute: DashboardGuildIdTicketsRoute,
  ApiPublicAuthDiscordCallbackRoute: ApiPublicAuthDiscordCallbackRoute,
  ApiPublicAuthDiscordLoginRoute: ApiPublicAuthDiscordLoginRoute,
  ApiPublicAuthDiscordLogoutRoute: ApiPublicAuthDiscordLogoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
