/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthorizedRouteImport } from './routes/authorized'
import { Route as CommandsRouteImport } from './routes/commands'
import { Route as DocumentationRouteImport } from './routes/documentation'
import { Route as EmbedsRouteImport } from './routes/embeds'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as HelpRouteImport } from './routes/help'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RefundsRouteImport } from './routes/refunds'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as DocsSlugRouteImport } from './routes/docs.$slug'
import { Route as DocsCommandsRouteImport } from './routes/docs.commands'
import { Route as DocsIntroductionRouteImport } from './routes/docs.introduction'
import { Route as KickCallbackRouteImport } from './routes/kick.callback'
import { Route as LastfmCallbackRouteImport } from './routes/lastfm.callback'
import { Route as TranscriptsTranscriptIdRouteImport } from './routes/transcripts.$transcriptId'
import { Route as TranscriptsIngestRouteImport } from './routes/transcripts.ingest'
import { Route as AuthDiscordCallbackRouteImport } from './routes/auth.discord.callback'
import { Route as AuthDiscordLoginRouteImport } from './routes/auth.discord.login'
import { Route as AuthDiscordLogoutRouteImport } from './routes/auth.discord.logout'
import { Route as DashboardGuildIdIndexRouteImport } from './routes/dashboard.$guildId.index'
import { Route as DashboardGuildIdAutomationsRouteImport } from './routes/dashboard.$guildId.automations'
import { Route as DashboardGuildIdCustomCommandsRouteImport } from './routes/dashboard.$guildId.custom-commands'
import { Route as DashboardGuildIdDiscordAppsRouteImport } from './routes/dashboard.$guildId.discord-apps'
import { Route as DashboardGuildIdEmbedsRouteImport } from './routes/dashboard.$guildId.embeds'
import { Route as DashboardGuildIdHistoryRouteImport } from './routes/dashboard.$guildId.history'
import { Route as DashboardGuildIdJoinGateRouteImport } from './routes/dashboard.$guildId.join-gate'
import { Route as DashboardGuildIdLastfmRouteImport } from './routes/dashboard.$guildId.lastfm'
import { Route as DashboardGuildIdLeaderboardRouteImport } from './routes/dashboard.$guildId.leaderboard'
import { Route as DashboardGuildIdLevelingRouteImport } from './routes/dashboard.$guildId.leveling'
import { Route as DashboardGuildIdLoggingRouteImport } from './routes/dashboard.$guildId.logging'
import { Route as DashboardGuildIdMessagesRouteImport } from './routes/dashboard.$guildId.messages'
import { Route as DashboardGuildIdPanelsRouteImport } from './routes/dashboard.$guildId.panels'
import { Route as DashboardGuildIdPermissionsRouteImport } from './routes/dashboard.$guildId.permissions'
import { Route as DashboardGuildIdSecurityRouteImport } from './routes/dashboard.$guildId.security'
import { Route as DashboardGuildIdSettingsRouteImport } from './routes/dashboard.$guildId.settings'
import { Route as DashboardGuildIdTicketsRouteImport } from './routes/dashboard.$guildId.tickets'
import { Route as DashboardGuildIdVerificationRouteImport } from './routes/dashboard.$guildId.verification'
import { Route as DashboardGuildIdVoicemasterRouteImport } from './routes/dashboard.$guildId.voicemaster'
import { Route as DashboardGuildIdWebhooksRouteImport } from './routes/dashboard.$guildId.webhooks'
import { Route as ApiPublicAnalyticsSnapshotRouteImport } from './routes/api/public/analytics/snapshot'
import { Route as ApiPublicLastfmAccountRouteImport } from './routes/api/public/lastfm/account'
import { Route as ApiPublicSecurityConfigRouteImport } from './routes/api/public/security/config'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe/webhook'
import { Route as ApiPublicTicketsTranscriptRouteImport } from './routes/api/public/tickets/transcript'
import { Route as ApiPublicAuthDiscordCallbackRouteImport } from './routes/api/public/auth/discord/callback'
import { Route as ApiPublicAuthDiscordLoginRouteImport } from './routes/api/public/auth/discord/login'
import { Route as ApiPublicAuthDiscordLogoutRouteImport } from './routes/api/public/auth/discord/logout'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorizedRoute = AuthorizedRouteImport.update({
  id: '/authorized',
  path: '/authorized',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandsRoute = CommandsRouteImport.update({
  id: '/commands',
  path: '/commands',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentationRoute = DocumentationRouteImport.update({
  id: '/documentation',
  path: '/documentation',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedsRoute = EmbedsRouteImport.update({
  id: '/embeds',
  path: '/embeds',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundsRoute = RefundsRouteImport.update({
  id: '/refunds',
  path: '/refunds',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSlugRoute = DocsSlugRouteImport.update({
  id: '/docs/$slug',
  path: '/docs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsCommandsRoute = DocsCommandsRouteImport.update({
  id: '/docs/commands',
  path: '/docs/commands',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIntroductionRoute = DocsIntroductionRouteImport.update({
  id: '/docs/introduction',
  path: '/docs/introduction',
  getParentRoute: () => rootRouteImport,
} as any)
const KickCallbackRoute = KickCallbackRouteImport.update({
  id: '/kick/callback',
  path: '/kick/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const LastfmCallbackRoute = LastfmCallbackRouteImport.update({
  id: '/lastfm/callback',
  path: '/lastfm/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const TranscriptsTranscriptIdRoute = TranscriptsTranscriptIdRouteImport.update({
  id: '/transcripts/$transcriptId',
  path: '/transcripts/$transcriptId',
  getParentRoute: () => rootRouteImport,
} as any)
const TranscriptsIngestRoute = TranscriptsIngestRouteImport.update({
  id: '/transcripts/ingest',
  path: '/transcripts/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDiscordCallbackRoute = AuthDiscordCallbackRouteImport.update({
  id: '/auth/discord/callback',
  path: '/auth/discord/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDiscordLoginRoute = AuthDiscordLoginRouteImport.update({
  id: '/auth/discord/login',
  path: '/auth/discord/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDiscordLogoutRoute = AuthDiscordLogoutRouteImport.update({
  id: '/auth/discord/logout',
  path: '/auth/discord/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardGuildIdIndexRoute = DashboardGuildIdIndexRouteImport.update({
  id: '/dashboard/$guildId/',
  path: '/dashboard/$guildId/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardGuildIdAutomationsRoute =
  DashboardGuildIdAutomationsRouteImport.update({
    id: '/dashboard/$guildId/automations',
    path: '/dashboard/$guildId/automations',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardGuildIdCustomCommandsRoute =
  DashboardGuildIdCustomCommandsRouteImport.update({
    id: '/dashboard/$guildId/custom-commands',
    path: '/dashboard/$guildId/custom-commands',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardGuildIdDiscordAppsRoute =
  DashboardGuildIdDiscordAppsRouteImport.update({
    id: '/dashboard/$guildId/discord-apps',
    path: '/dashboard/$guildId/discord-apps',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardGuildIdEmbedsRoute = DashboardGuildIdEmbedsRouteImport.update({
  id: '/dashboard/$guildId/embeds',
  path: '/dashboard/$guildId/embeds',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardGuildIdHistoryRoute = DashboardGuildIdHistoryRouteImport.update({
  id: '/dashboard/$guildId/history',
  path: '/dashboard/$guildId/history',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardGuildIdJoinGateRoute =
  DashboardGuildIdJoinGateRouteImport.update({
    id: '/dashboard/$guildId/join-gate',
    path: '/dashboard/$guildId/join-gate',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardGuildIdLastfmRoute = DashboardGuildIdLastfmRouteImport.update({
  id: '/dashboard/$guildId/lastfm',
  path: '/dashboard/$guildId/lastfm',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardGuildIdLeaderboardRoute =
  DashboardGuildIdLeaderboardRouteImport.update({
    id: '/dashboard/$guildId/leaderboard',
    path: '/dashboard/$guildId/leaderboard',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardGuildIdLevelingRoute =
  DashboardGuildIdLevelingRouteImport.update({
    id: '/dashboard/$guildId/leveling',
    path: '/dashboard/$guildId/leveling',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardGuildIdLoggingRoute = DashboardGuildIdLoggingRouteImport.update({
  id: '/dashboard/$guildId/logging',
  path: '/dashboard/$guildId/logging',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardGuildIdMessagesRoute =
  DashboardGuildIdMessagesRouteImport.update({
    id: '/dashboard/$guildId/messages',
    path: '/dashboard/$guildId/messages',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardGuildIdPanelsRoute = DashboardGuildIdPanelsRouteImport.update({
  id: '/dashboard/$guildId/panels',
  path: '/dashboard/$guildId/panels',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardGuildIdPermissionsRoute =
  DashboardGuildIdPermissionsRouteImport.update({
    id: '/dashboard/$guildId/permissions',
    path: '/dashboard/$guildId/permissions',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardGuildIdSecurityRoute =
  DashboardGuildIdSecurityRouteImport.update({
    id: '/dashboard/$guildId/security',
    path: '/dashboard/$guildId/security',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardGuildIdSettingsRoute =
  DashboardGuildIdSettingsRouteImport.update({
    id: '/dashboard/$guildId/settings',
    path: '/dashboard/$guildId/settings',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardGuildIdTicketsRoute = DashboardGuildIdTicketsRouteImport.update({
  id: '/dashboard/$guildId/tickets',
  path: '/dashboard/$guildId/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardGuildIdVerificationRoute =
  DashboardGuildIdVerificationRouteImport.update({
    id: '/dashboard/$guildId/verification',
    path: '/dashboard/$guildId/verification',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardGuildIdVoicemasterRoute =
  DashboardGuildIdVoicemasterRouteImport.update({
    id: '/dashboard/$guildId/voicemaster',
    path: '/dashboard/$guildId/voicemaster',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardGuildIdWebhooksRoute =
  DashboardGuildIdWebhooksRouteImport.update({
    id: '/dashboard/$guildId/webhooks',
    path: '/dashboard/$guildId/webhooks',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAnalyticsSnapshotRoute =
  ApiPublicAnalyticsSnapshotRouteImport.update({
    id: '/api/public/analytics/snapshot',
    path: '/api/public/analytics/snapshot',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicLastfmAccountRoute = ApiPublicLastfmAccountRouteImport.update({
  id: '/api/public/lastfm/account',
  path: '/api/public/lastfm/account',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSecurityConfigRoute = ApiPublicSecurityConfigRouteImport.update({
  id: '/api/public/security/config',
  path: '/api/public/security/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe/webhook',
  path: '/api/public/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTicketsTranscriptRoute =
  ApiPublicTicketsTranscriptRouteImport.update({
    id: '/api/public/tickets/transcript',
    path: '/api/public/tickets/transcript',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAuthDiscordCallbackRoute =
  ApiPublicAuthDiscordCallbackRouteImport.update({
    id: '/api/public/auth/discord/callback',
    path: '/api/public/auth/discord/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAuthDiscordLoginRoute =
  ApiPublicAuthDiscordLoginRouteImport.update({
    id: '/api/public/auth/discord/login',
    path: '/api/public/auth/discord/login',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAuthDiscordLogoutRoute =
  ApiPublicAuthDiscordLogoutRouteImport.update({
    id: '/api/public/auth/discord/logout',
    path: '/api/public/auth/discord/logout',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/authorized': typeof AuthorizedRoute
  '/commands': typeof CommandsRoute
  '/documentation': typeof DocumentationRoute
  '/embeds': typeof EmbedsRoute
  '/faq': typeof FaqRoute
  '/help': typeof HelpRoute
  '/privacy': typeof PrivacyRoute
  '/refunds': typeof RefundsRoute
  '/terms': typeof TermsRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/docs/commands': typeof DocsCommandsRoute
  '/docs/introduction': typeof DocsIntroductionRoute
  '/kick/callback': typeof KickCallbackRoute
  '/lastfm/callback': typeof LastfmCallbackRoute
  '/transcripts/$transcriptId': typeof TranscriptsTranscriptIdRoute
  '/transcripts/ingest': typeof TranscriptsIngestRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/auth/discord/callback': typeof AuthDiscordCallbackRoute
  '/auth/discord/login': typeof AuthDiscordLoginRoute
  '/auth/discord/logout': typeof AuthDiscordLogoutRoute
  '/dashboard/$guildId/automations': typeof DashboardGuildIdAutomationsRoute
  '/dashboard/$guildId/custom-commands': typeof DashboardGuildIdCustomCommandsRoute
  '/dashboard/$guildId/discord-apps': typeof DashboardGuildIdDiscordAppsRoute
  '/dashboard/$guildId/embeds': typeof DashboardGuildIdEmbedsRoute
  '/dashboard/$guildId/history': typeof DashboardGuildIdHistoryRoute
  '/dashboard/$guildId/join-gate': typeof DashboardGuildIdJoinGateRoute
  '/dashboard/$guildId/lastfm': typeof DashboardGuildIdLastfmRoute
  '/dashboard/$guildId/leaderboard': typeof DashboardGuildIdLeaderboardRoute
  '/dashboard/$guildId/leveling': typeof DashboardGuildIdLevelingRoute
  '/dashboard/$guildId/logging': typeof DashboardGuildIdLoggingRoute
  '/dashboard/$guildId/messages': typeof DashboardGuildIdMessagesRoute
  '/dashboard/$guildId/panels': typeof DashboardGuildIdPanelsRoute
  '/dashboard/$guildId/permissions': typeof DashboardGuildIdPermissionsRoute
  '/dashboard/$guildId/security': typeof DashboardGuildIdSecurityRoute
  '/dashboard/$guildId/settings': typeof DashboardGuildIdSettingsRoute
  '/dashboard/$guildId/tickets': typeof DashboardGuildIdTicketsRoute
  '/dashboard/$guildId/verification': typeof DashboardGuildIdVerificationRoute
  '/dashboard/$guildId/voicemaster': typeof DashboardGuildIdVoicemasterRoute
  '/dashboard/$guildId/webhooks': typeof DashboardGuildIdWebhooksRoute
  '/dashboard/$guildId/': typeof DashboardGuildIdIndexRoute
  '/api/public/analytics/snapshot': typeof ApiPublicAnalyticsSnapshotRoute
  '/api/public/lastfm/account': typeof ApiPublicLastfmAccountRoute
  '/api/public/security/config': typeof ApiPublicSecurityConfigRoute
  '/api/public/stripe/webhook': typeof ApiPublicStripeWebhookRoute
  '/api/public/tickets/transcript': typeof ApiPublicTicketsTranscriptRoute
  '/api/public/auth/discord/callback': typeof ApiPublicAuthDiscordCallbackRoute
  '/api/public/auth/discord/login': typeof ApiPublicAuthDiscordLoginRoute
  '/api/public/auth/discord/logout': typeof ApiPublicAuthDiscordLogoutRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/authorized': typeof AuthorizedRoute
  '/commands': typeof CommandsRoute
  '/documentation': typeof DocumentationRoute
  '/embeds': typeof EmbedsRoute
  '/faq': typeof FaqRoute
  '/help': typeof HelpRoute
  '/privacy': typeof PrivacyRoute
  '/refunds': typeof RefundsRoute
  '/terms': typeof TermsRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/docs/commands': typeof DocsCommandsRoute
  '/docs/introduction': typeof DocsIntroductionRoute
  '/kick/callback': typeof KickCallbackRoute
  '/lastfm/callback': typeof LastfmCallbackRoute
  '/transcripts/$transcriptId': typeof TranscriptsTranscriptIdRoute
  '/transcripts/ingest': typeof TranscriptsIngestRoute
  '/dashboard': typeof DashboardIndexRoute
  '/docs': typeof DocsIndexRoute
  '/auth/discord/callback': typeof AuthDiscordCallbackRoute
  '/auth/discord/login': typeof AuthDiscordLoginRoute
  '/auth/discord/logout': typeof AuthDiscordLogoutRoute
  '/dashboard/$guildId/automations': typeof DashboardGuildIdAutomationsRoute
  '/dashboard/$guildId/custom-commands': typeof DashboardGuildIdCustomCommandsRoute
  '/dashboard/$guildId/discord-apps': typeof DashboardGuildIdDiscordAppsRoute
  '/dashboard/$guildId/embeds': typeof DashboardGuildIdEmbedsRoute
  '/dashboard/$guildId/history': typeof DashboardGuildIdHistoryRoute
  '/dashboard/$guildId/join-gate': typeof DashboardGuildIdJoinGateRoute
  '/dashboard/$guildId/lastfm': typeof DashboardGuildIdLastfmRoute
  '/dashboard/$guildId/leaderboard': typeof DashboardGuildIdLeaderboardRoute
  '/dashboard/$guildId/leveling': typeof DashboardGuildIdLevelingRoute
  '/dashboard/$guildId/logging': typeof DashboardGuildIdLoggingRoute
  '/dashboard/$guildId/messages': typeof DashboardGuildIdMessagesRoute
  '/dashboard/$guildId/panels': typeof DashboardGuildIdPanelsRoute
  '/dashboard/$guildId/permissions': typeof DashboardGuildIdPermissionsRoute
  '/dashboard/$guildId/security': typeof DashboardGuildIdSecurityRoute
  '/dashboard/$guildId/settings': typeof DashboardGuildIdSettingsRoute
  '/dashboard/$guildId/tickets': typeof DashboardGuildIdTicketsRoute
  '/dashboard/$guildId/verification': typeof DashboardGuildIdVerificationRoute
  '/dashboard/$guildId/voicemaster': typeof DashboardGuildIdVoicemasterRoute
  '/dashboard/$guildId/webhooks': typeof DashboardGuildIdWebhooksRoute
  '/dashboard/$guildId': typeof DashboardGuildIdIndexRoute
  '/api/public/analytics/snapshot': typeof ApiPublicAnalyticsSnapshotRoute
  '/api/public/lastfm/account': typeof ApiPublicLastfmAccountRoute
  '/api/public/security/config': typeof ApiPublicSecurityConfigRoute
  '/api/public/stripe/webhook': typeof ApiPublicStripeWebhookRoute
  '/api/public/tickets/transcript': typeof ApiPublicTicketsTranscriptRoute
  '/api/public/auth/discord/callback': typeof ApiPublicAuthDiscordCallbackRoute
  '/api/public/auth/discord/login': typeof ApiPublicAuthDiscordLoginRoute
  '/api/public/auth/discord/logout': typeof ApiPublicAuthDiscordLogoutRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/authorized': typeof AuthorizedRoute
  '/commands': typeof CommandsRoute
  '/documentation': typeof DocumentationRoute
  '/embeds': typeof EmbedsRoute
  '/faq': typeof FaqRoute
  '/help': typeof HelpRoute
  '/privacy': typeof PrivacyRoute
  '/refunds': typeof RefundsRoute
  '/terms': typeof TermsRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/docs/commands': typeof DocsCommandsRoute
  '/docs/introduction': typeof DocsIntroductionRoute
  '/kick/callback': typeof KickCallbackRoute
  '/lastfm/callback': typeof LastfmCallbackRoute
  '/transcripts/$transcriptId': typeof TranscriptsTranscriptIdRoute
  '/transcripts/ingest': typeof TranscriptsIngestRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/auth/discord/callback': typeof AuthDiscordCallbackRoute
  '/auth/discord/login': typeof AuthDiscordLoginRoute
  '/auth/discord/logout': typeof AuthDiscordLogoutRoute
  '/dashboard/$guildId/automations': typeof DashboardGuildIdAutomationsRoute
  '/dashboard/$guildId/custom-commands': typeof DashboardGuildIdCustomCommandsRoute
  '/dashboard/$guildId/discord-apps': typeof DashboardGuildIdDiscordAppsRoute
  '/dashboard/$guildId/embeds': typeof DashboardGuildIdEmbedsRoute
  '/dashboard/$guildId/history': typeof DashboardGuildIdHistoryRoute
  '/dashboard/$guildId/join-gate': typeof DashboardGuildIdJoinGateRoute
  '/dashboard/$guildId/lastfm': typeof DashboardGuildIdLastfmRoute
  '/dashboard/$guildId/leaderboard': typeof DashboardGuildIdLeaderboardRoute
  '/dashboard/$guildId/leveling': typeof DashboardGuildIdLevelingRoute
  '/dashboard/$guildId/logging': typeof DashboardGuildIdLoggingRoute
  '/dashboard/$guildId/messages': typeof DashboardGuildIdMessagesRoute
  '/dashboard/$guildId/panels': typeof DashboardGuildIdPanelsRoute
  '/dashboard/$guildId/permissions': typeof DashboardGuildIdPermissionsRoute
  '/dashboard/$guildId/security': typeof DashboardGuildIdSecurityRoute
  '/dashboard/$guildId/settings': typeof DashboardGuildIdSettingsRoute
  '/dashboard/$guildId/tickets': typeof DashboardGuildIdTicketsRoute
  '/dashboard/$guildId/verification': typeof DashboardGuildIdVerificationRoute
  '/dashboard/$guildId/voicemaster': typeof DashboardGuildIdVoicemasterRoute
  '/dashboard/$guildId/webhooks': typeof DashboardGuildIdWebhooksRoute
  '/dashboard/$guildId/': typeof DashboardGuildIdIndexRoute
  '/api/public/analytics/snapshot': typeof ApiPublicAnalyticsSnapshotRoute
  '/api/public/lastfm/account': typeof ApiPublicLastfmAccountRoute
  '/api/public/security/config': typeof ApiPublicSecurityConfigRoute
  '/api/public/stripe/webhook': typeof ApiPublicStripeWebhookRoute
  '/api/public/tickets/transcript': typeof ApiPublicTicketsTranscriptRoute
  '/api/public/auth/discord/callback': typeof ApiPublicAuthDiscordCallbackRoute
  '/api/public/auth/discord/login': typeof ApiPublicAuthDiscordLoginRoute
  '/api/public/auth/discord/logout': typeof ApiPublicAuthDiscordLogoutRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/authorized'
    | '/commands'
    | '/documentation'
    | '/embeds'
    | '/faq'
    | '/help'
    | '/privacy'
    | '/refunds'
    | '/terms'
    | '/docs/$slug'
    | '/docs/commands'
    | '/docs/introduction'
    | '/kick/callback'
    | '/lastfm/callback'
    | '/transcripts/$transcriptId'
    | '/transcripts/ingest'
    | '/dashboard/'
    | '/docs/'
    | '/auth/discord/callback'
    | '/auth/discord/login'
    | '/auth/discord/logout'
    | '/dashboard/$guildId/automations'
    | '/dashboard/$guildId/custom-commands'
    | '/dashboard/$guildId/discord-apps'
    | '/dashboard/$guildId/embeds'
    | '/dashboard/$guildId/history'
    | '/dashboard/$guildId/join-gate'
    | '/dashboard/$guildId/lastfm'
    | '/dashboard/$guildId/leaderboard'
    | '/dashboard/$guildId/leveling'
    | '/dashboard/$guildId/logging'
    | '/dashboard/$guildId/messages'
    | '/dashboard/$guildId/panels'
    | '/dashboard/$guildId/permissions'
    | '/dashboard/$guildId/security'
    | '/dashboard/$guildId/settings'
    | '/dashboard/$guildId/tickets'
    | '/dashboard/$guildId/verification'
    | '/dashboard/$guildId/voicemaster'
    | '/dashboard/$guildId/webhooks'
    | '/dashboard/$guildId/'
    | '/api/public/analytics/snapshot'
    | '/api/public/lastfm/account'
    | '/api/public/security/config'
    | '/api/public/stripe/webhook'
    | '/api/public/tickets/transcript'
    | '/api/public/auth/discord/callback'
    | '/api/public/auth/discord/login'
    | '/api/public/auth/discord/logout'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/authorized'
    | '/commands'
    | '/documentation'
    | '/embeds'
    | '/faq'
    | '/help'
    | '/privacy'
    | '/refunds'
    | '/terms'
    | '/docs/$slug'
    | '/docs/commands'
    | '/docs/introduction'
    | '/kick/callback'
    | '/lastfm/callback'
    | '/transcripts/$transcriptId'
    | '/transcripts/ingest'
    | '/dashboard'
    | '/docs'
    | '/auth/discord/callback'
    | '/auth/discord/login'
    | '/auth/discord/logout'
    | '/dashboard/$guildId/automations'
    | '/dashboard/$guildId/custom-commands'
    | '/dashboard/$guildId/discord-apps'
    | '/dashboard/$guildId/embeds'
    | '/dashboard/$guildId/history'
    | '/dashboard/$guildId/join-gate'
    | '/dashboard/$guildId/lastfm'
    | '/dashboard/$guildId/leaderboard'
    | '/dashboard/$guildId/leveling'
    | '/dashboard/$guildId/logging'
    | '/dashboard/$guildId/messages'
    | '/dashboard/$guildId/panels'
    | '/dashboard/$guildId/permissions'
    | '/dashboard/$guildId/security'
    | '/dashboard/$guildId/settings'
    | '/dashboard/$guildId/tickets'
    | '/dashboard/$guildId/verification'
    | '/dashboard/$guildId/voicemaster'
    | '/dashboard/$guildId/webhooks'
    | '/dashboard/$guildId'
    | '/api/public/analytics/snapshot'
    | '/api/public/lastfm/account'
    | '/api/public/security/config'
    | '/api/public/stripe/webhook'
    | '/api/public/tickets/transcript'
    | '/api/public/auth/discord/callback'
    | '/api/public/auth/discord/login'
    | '/api/public/auth/discord/logout'
  id:
    | '__root__'
    | '/'
    | '/authorized'
    | '/commands'
    | '/documentation'
    | '/embeds'
    | '/faq'
    | '/help'
    | '/privacy'
    | '/refunds'
    | '/terms'
    | '/docs/$slug'
    | '/docs/commands'
    | '/docs/introduction'
    | '/kick/callback'
    | '/lastfm/callback'
    | '/transcripts/$transcriptId'
    | '/transcripts/ingest'
    | '/dashboard/'
    | '/docs/'
    | '/auth/discord/callback'
    | '/auth/discord/login'
    | '/auth/discord/logout'
    | '/dashboard/$guildId/automations'
    | '/dashboard/$guildId/custom-commands'
    | '/dashboard/$guildId/discord-apps'
    | '/dashboard/$guildId/embeds'
    | '/dashboard/$guildId/history'
    | '/dashboard/$guildId/join-gate'
    | '/dashboard/$guildId/lastfm'
    | '/dashboard/$guildId/leaderboard'
    | '/dashboard/$guildId/leveling'
    | '/dashboard/$guildId/logging'
    | '/dashboard/$guildId/messages'
    | '/dashboard/$guildId/panels'
    | '/dashboard/$guildId/permissions'
    | '/dashboard/$guildId/security'
    | '/dashboard/$guildId/settings'
    | '/dashboard/$guildId/tickets'
    | '/dashboard/$guildId/verification'
    | '/dashboard/$guildId/voicemaster'
    | '/dashboard/$guildId/webhooks'
    | '/dashboard/$guildId/'
    | '/api/public/analytics/snapshot'
    | '/api/public/lastfm/account'
    | '/api/public/security/config'
    | '/api/public/stripe/webhook'
    | '/api/public/tickets/transcript'
    | '/api/public/auth/discord/callback'
    | '/api/public/auth/discord/login'
    | '/api/public/auth/discord/logout'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthorizedRoute: typeof AuthorizedRoute
  CommandsRoute: typeof CommandsRoute
  DocumentationRoute: typeof DocumentationRoute
  EmbedsRoute: typeof EmbedsRoute
  FaqRoute: typeof FaqRoute
  HelpRoute: typeof HelpRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundsRoute: typeof RefundsRoute
  TermsRoute: typeof TermsRoute
  DocsSlugRoute: typeof DocsSlugRoute
  DocsCommandsRoute: typeof DocsCommandsRoute
  DocsIntroductionRoute: typeof DocsIntroductionRoute
  KickCallbackRoute: typeof KickCallbackRoute
  LastfmCallbackRoute: typeof LastfmCallbackRoute
  TranscriptsTranscriptIdRoute: typeof TranscriptsTranscriptIdRoute
  TranscriptsIngestRoute: typeof TranscriptsIngestRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DocsIndexRoute: typeof DocsIndexRoute
  AuthDiscordCallbackRoute: typeof AuthDiscordCallbackRoute
  AuthDiscordLoginRoute: typeof AuthDiscordLoginRoute
  AuthDiscordLogoutRoute: typeof AuthDiscordLogoutRoute
  DashboardGuildIdAutomationsRoute: typeof DashboardGuildIdAutomationsRoute
  DashboardGuildIdCustomCommandsRoute: typeof DashboardGuildIdCustomCommandsRoute
  DashboardGuildIdDiscordAppsRoute: typeof DashboardGuildIdDiscordAppsRoute
  DashboardGuildIdEmbedsRoute: typeof DashboardGuildIdEmbedsRoute
  DashboardGuildIdHistoryRoute: typeof DashboardGuildIdHistoryRoute
  DashboardGuildIdJoinGateRoute: typeof DashboardGuildIdJoinGateRoute
  DashboardGuildIdLastfmRoute: typeof DashboardGuildIdLastfmRoute
  DashboardGuildIdLeaderboardRoute: typeof DashboardGuildIdLeaderboardRoute
  DashboardGuildIdLevelingRoute: typeof DashboardGuildIdLevelingRoute
  DashboardGuildIdLoggingRoute: typeof DashboardGuildIdLoggingRoute
  DashboardGuildIdMessagesRoute: typeof DashboardGuildIdMessagesRoute
  DashboardGuildIdPanelsRoute: typeof DashboardGuildIdPanelsRoute
  DashboardGuildIdPermissionsRoute: typeof DashboardGuildIdPermissionsRoute
  DashboardGuildIdSecurityRoute: typeof DashboardGuildIdSecurityRoute
  DashboardGuildIdSettingsRoute: typeof DashboardGuildIdSettingsRoute
  DashboardGuildIdTicketsRoute: typeof DashboardGuildIdTicketsRoute
  DashboardGuildIdVerificationRoute: typeof DashboardGuildIdVerificationRoute
  DashboardGuildIdVoicemasterRoute: typeof DashboardGuildIdVoicemasterRoute
  DashboardGuildIdWebhooksRoute: typeof DashboardGuildIdWebhooksRoute
  DashboardGuildIdIndexRoute: typeof DashboardGuildIdIndexRoute
  ApiPublicAnalyticsSnapshotRoute: typeof ApiPublicAnalyticsSnapshotRoute
  ApiPublicLastfmAccountRoute: typeof ApiPublicLastfmAccountRoute
  ApiPublicSecurityConfigRoute: typeof ApiPublicSecurityConfigRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
  ApiPublicTicketsTranscriptRoute: typeof ApiPublicTicketsTranscriptRoute
  ApiPublicAuthDiscordCallbackRoute: typeof ApiPublicAuthDiscordCallbackRoute
  ApiPublicAuthDiscordLoginRoute: typeof ApiPublicAuthDiscordLoginRoute
  ApiPublicAuthDiscordLogoutRoute: typeof ApiPublicAuthDiscordLogoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authorized': {
      id: '/authorized'
      path: '/authorized'
      fullPath: '/authorized'
      preLoaderRoute: typeof AuthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commands': {
      id: '/commands'
      path: '/commands'
      fullPath: '/commands'
      preLoaderRoute: typeof CommandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentation': {
      id: '/documentation'
      path: '/documentation'
      fullPath: '/documentation'
      preLoaderRoute: typeof DocumentationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embeds': {
      id: '/embeds'
      path: '/embeds'
      fullPath: '/embeds'
      preLoaderRoute: typeof EmbedsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refunds': {
      id: '/refunds'
      path: '/refunds'
      fullPath: '/refunds'
      preLoaderRoute: typeof RefundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$slug': {
      id: '/docs/$slug'
      path: '/docs/$slug'
      fullPath: '/docs/$slug'
      preLoaderRoute: typeof DocsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/commands': {
      id: '/docs/commands'
      path: '/docs/commands'
      fullPath: '/docs/commands'
      preLoaderRoute: typeof DocsCommandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/introduction': {
      id: '/docs/introduction'
      path: '/docs/introduction'
      fullPath: '/docs/introduction'
      preLoaderRoute: typeof DocsIntroductionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kick/callback': {
      id: '/kick/callback'
      path: '/kick/callback'
      fullPath: '/kick/callback'
      preLoaderRoute: typeof KickCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lastfm/callback': {
      id: '/lastfm/callback'
      path: '/lastfm/callback'
      fullPath: '/lastfm/callback'
      preLoaderRoute: typeof LastfmCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transcripts/$transcriptId': {
      id: '/transcripts/$transcriptId'
      path: '/transcripts/$transcriptId'
      fullPath: '/transcripts/$transcriptId'
      preLoaderRoute: typeof TranscriptsTranscriptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transcripts/ingest': {
      id: '/transcripts/ingest'
      path: '/transcripts/ingest'
      fullPath: '/transcripts/ingest'
      preLoaderRoute: typeof TranscriptsIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/discord/callback': {
      id: '/auth/discord/callback'
      path: '/auth/discord/callback'
      fullPath: '/auth/discord/callback'
      preLoaderRoute: typeof AuthDiscordCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/discord/login': {
      id: '/auth/discord/login'
      path: '/auth/discord/login'
      fullPath: '/auth/discord/login'
      preLoaderRoute: typeof AuthDiscordLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/discord/logout': {
      id: '/auth/discord/logout'
      path: '/auth/discord/logout'
      fullPath: '/auth/discord/logout'
      preLoaderRoute: typeof AuthDiscordLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$guildId/': {
      id: '/dashboard/$guildId/'
      path: '/dashboard/$guildId'
      fullPath: '/dashboard/$guildId/'
      preLoaderRoute: typeof DashboardGuildIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$guildId/automations': {
      id: '/dashboard/$guildId/automations'
      path: '/dashboard/$guildId/automations'
      fullPath: '/dashboard/$guildId/automations'
      preLoaderRoute: typeof DashboardGuildIdAutomationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$guildId/custom-commands': {
      id: '/dashboard/$guildId/custom-commands'
      path: '/dashboard/$guildId/custom-commands'
      fullPath: '/dashboard/$guildId/custom-commands'
      preLoaderRoute: typeof DashboardGuildIdCustomCommandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$guildId/discord-apps': {
      id: '/dashboard/$guildId/discord-apps'
      path: '/dashboard/$guildId/discord-apps'
      fullPath: '/dashboard/$guildId/discord-apps'
      preLoaderRoute: typeof DashboardGuildIdDiscordAppsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$guildId/embeds': {
      id: '/dashboard/$guildId/embeds'
      path: '/dashboard/$guildId/embeds'
      fullPath: '/dashboard/$guildId/embeds'
      preLoaderRoute: typeof DashboardGuildIdEmbedsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$guildId/history': {
      id: '/dashboard/$guildId/history'
      path: '/dashboard/$guildId/history'
      fullPath: '/dashboard/$guildId/history'
      preLoaderRoute: typeof DashboardGuildIdHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$guildId/join-gate': {
      id: '/dashboard/$guildId/join-gate'
      path: '/dashboard/$guildId/join-gate'
      fullPath: '/dashboard/$guildId/join-gate'
      preLoaderRoute: typeof DashboardGuildIdJoinGateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$guildId/lastfm': {
      id: '/dashboard/$guildId/lastfm'
      path: '/dashboard/$guildId/lastfm'
      fullPath: '/dashboard/$guildId/lastfm'
      preLoaderRoute: typeof DashboardGuildIdLastfmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$guildId/leaderboard': {
      id: '/dashboard/$guildId/leaderboard'
      path: '/dashboard/$guildId/leaderboard'
      fullPath: '/dashboard/$guildId/leaderboard'
      preLoaderRoute: typeof DashboardGuildIdLeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$guildId/leveling': {
      id: '/dashboard/$guildId/leveling'
      path: '/dashboard/$guildId/leveling'
      fullPath: '/dashboard/$guildId/leveling'
      preLoaderRoute: typeof DashboardGuildIdLevelingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$guildId/logging': {
      id: '/dashboard/$guildId/logging'
      path: '/dashboard/$guildId/logging'
      fullPath: '/dashboard/$guildId/logging'
      preLoaderRoute: typeof DashboardGuildIdLoggingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$guildId/messages': {
      id: '/dashboard/$guildId/messages'
      path: '/dashboard/$guildId/messages'
      fullPath: '/dashboard/$guildId/messages'
      preLoaderRoute: typeof DashboardGuildIdMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$guildId/panels': {
      id: '/dashboard/$guildId/panels'
      path: '/dashboard/$guildId/panels'
      fullPath: '/dashboard/$guildId/panels'
      preLoaderRoute: typeof DashboardGuildIdPanelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$guildId/permissions': {
      id: '/dashboard/$guildId/permissions'
      path: '/dashboard/$guildId/permissions'
      fullPath: '/dashboard/$guildId/permissions'
      preLoaderRoute: typeof DashboardGuildIdPermissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$guildId/security': {
      id: '/dashboard/$guildId/security'
      path: '/dashboard/$guildId/security'
      fullPath: '/dashboard/$guildId/security'
      preLoaderRoute: typeof DashboardGuildIdSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$guildId/settings': {
      id: '/dashboard/$guildId/settings'
      path: '/dashboard/$guildId/settings'
      fullPath: '/dashboard/$guildId/settings'
      preLoaderRoute: typeof DashboardGuildIdSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$guildId/tickets': {
      id: '/dashboard/$guildId/tickets'
      path: '/dashboard/$guildId/tickets'
      fullPath: '/dashboard/$guildId/tickets'
      preLoaderRoute: typeof DashboardGuildIdTicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$guildId/verification': {
      id: '/dashboard/$guildId/verification'
      path: '/dashboard/$guildId/verification'
      fullPath: '/dashboard/$guildId/verification'
      preLoaderRoute: typeof DashboardGuildIdVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$guildId/voicemaster': {
      id: '/dashboard/$guildId/voicemaster'
      path: '/dashboard/$guildId/voicemaster'
      fullPath: '/dashboard/$guildId/voicemaster'
      preLoaderRoute: typeof DashboardGuildIdVoicemasterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$guildId/webhooks': {
      id: '/dashboard/$guildId/webhooks'
      path: '/dashboard/$guildId/webhooks'
      fullPath: '/dashboard/$guildId/webhooks'
      preLoaderRoute: typeof DashboardGuildIdWebhooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/analytics/snapshot': {
      id: '/api/public/analytics/snapshot'
      path: '/api/public/analytics/snapshot'
      fullPath: '/api/public/analytics/snapshot'
      preLoaderRoute: typeof ApiPublicAnalyticsSnapshotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/lastfm/account': {
      id: '/api/public/lastfm/account'
      path: '/api/public/lastfm/account'
      fullPath: '/api/public/lastfm/account'
      preLoaderRoute: typeof ApiPublicLastfmAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/security/config': {
      id: '/api/public/security/config'
      path: '/api/public/security/config'
      fullPath: '/api/public/security/config'
      preLoaderRoute: typeof ApiPublicSecurityConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stripe/webhook': {
      id: '/api/public/stripe/webhook'
      path: '/api/public/stripe/webhook'
      fullPath: '/api/public/stripe/webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/tickets/transcript': {
      id: '/api/public/tickets/transcript'
      path: '/api/public/tickets/transcript'
      fullPath: '/api/public/tickets/transcript'
      preLoaderRoute: typeof ApiPublicTicketsTranscriptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auth/discord/callback': {
      id: '/api/public/auth/discord/callback'
      path: '/api/public/auth/discord/callback'
      fullPath: '/api/public/auth/discord/callback'
      preLoaderRoute: typeof ApiPublicAuthDiscordCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auth/discord/login': {
      id: '/api/public/auth/discord/login'
      path: '/api/public/auth/discord/login'
      fullPath: '/api/public/auth/discord/login'
      preLoaderRoute: typeof ApiPublicAuthDiscordLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auth/discord/logout': {
      id: '/api/public/auth/discord/logout'
      path: '/api/public/auth/discord/logout'
      fullPath: '/api/public/auth/discord/logout'
      preLoaderRoute: typeof ApiPublicAuthDiscordLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthorizedRoute: AuthorizedRoute,
  CommandsRoute: CommandsRoute,
  DocumentationRoute: DocumentationRoute,
  EmbedsRoute: EmbedsRoute,
  FaqRoute: FaqRoute,
  HelpRoute: HelpRoute,
  PrivacyRoute: PrivacyRoute,
  RefundsRoute: RefundsRoute,
  TermsRoute: TermsRoute,
  DocsSlugRoute: DocsSlugRoute,
  DocsCommandsRoute: DocsCommandsRoute,
  DocsIntroductionRoute: DocsIntroductionRoute,
  KickCallbackRoute: KickCallbackRoute,
  LastfmCallbackRoute: LastfmCallbackRoute,
  TranscriptsTranscriptIdRoute: TranscriptsTranscriptIdRoute,
  TranscriptsIngestRoute: TranscriptsIngestRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DocsIndexRoute: DocsIndexRoute,
  AuthDiscordCallbackRoute: AuthDiscordCallbackRoute,
  AuthDiscordLoginRoute: AuthDiscordLoginRoute,
  AuthDiscordLogoutRoute: AuthDiscordLogoutRoute,
  DashboardGuildIdAutomationsRoute: DashboardGuildIdAutomationsRoute,
  DashboardGuildIdCustomCommandsRoute: DashboardGuildIdCustomCommandsRoute,
  DashboardGuildIdDiscordAppsRoute: DashboardGuildIdDiscordAppsRoute,
  DashboardGuildIdEmbedsRoute: DashboardGuildIdEmbedsRoute,
  DashboardGuildIdHistoryRoute: DashboardGuildIdHistoryRoute,
  DashboardGuildIdJoinGateRoute: DashboardGuildIdJoinGateRoute,
  DashboardGuildIdLastfmRoute: DashboardGuildIdLastfmRoute,
  DashboardGuildIdLeaderboardRoute: DashboardGuildIdLeaderboardRoute,
  DashboardGuildIdLevelingRoute: DashboardGuildIdLevelingRoute,
  DashboardGuildIdLoggingRoute: DashboardGuildIdLoggingRoute,
  DashboardGuildIdMessagesRoute: DashboardGuildIdMessagesRoute,
  DashboardGuildIdPanelsRoute: DashboardGuildIdPanelsRoute,
  DashboardGuildIdPermissionsRoute: DashboardGuildIdPermissionsRoute,
  DashboardGuildIdSecurityRoute: DashboardGuildIdSecurityRoute,
  DashboardGuildIdSettingsRoute: DashboardGuildIdSettingsRoute,
  DashboardGuildIdTicketsRoute: DashboardGuildIdTicketsRoute,
  DashboardGuildIdVerificationRoute: DashboardGuildIdVerificationRoute,
  DashboardGuildIdVoicemasterRoute: DashboardGuildIdVoicemasterRoute,
  DashboardGuildIdWebhooksRoute: DashboardGuildIdWebhooksRoute,
  DashboardGuildIdIndexRoute: DashboardGuildIdIndexRoute,
  ApiPublicAnalyticsSnapshotRoute: ApiPublicAnalyticsSnapshotRoute,
  ApiPublicLastfmAccountRoute: ApiPublicLastfmAccountRoute,
  ApiPublicSecurityConfigRoute: ApiPublicSecurityConfigRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
  ApiPublicTicketsTranscriptRoute: ApiPublicTicketsTranscriptRoute,
  ApiPublicAuthDiscordCallbackRoute: ApiPublicAuthDiscordCallbackRoute,
  ApiPublicAuthDiscordLoginRoute: ApiPublicAuthDiscordLoginRoute,
  ApiPublicAuthDiscordLogoutRoute: ApiPublicAuthDiscordLogoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
