/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DocsSlugRouteImport } from './routes/docs.$slug'
import { Route as DashboardGuildIdTicketsRouteImport } from './routes/dashboard.$guildId.tickets'
import { Route as DashboardGuildIdSecurityRouteImport } from './routes/dashboard.$guildId.security'
import { Route as AuthDiscordLogoutRouteImport } from './routes/auth.discord.logout'
import { Route as AuthDiscordLoginRouteImport } from './routes/auth.discord.login'
import { Route as AuthDiscordCallbackRouteImport } from './routes/auth.discord.callback'
import { Route as ApiPublicAuthDiscordLogoutRouteImport } from './routes/api/public/auth/discord/logout'
import { Route as ApiPublicAuthDiscordLoginRouteImport } from './routes/api/public/auth/discord/login'
import { Route as ApiPublicAuthDiscordCallbackRouteImport } from './routes/api/public/auth/discord/callback'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSlugRoute = DocsSlugRouteImport.update({
  id: '/docs/$slug',
  path: '/docs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardGuildIdTicketsRoute = DashboardGuildIdTicketsRouteImport.update({
  id: '/dashboard/$guildId/tickets',
  path: '/dashboard/$guildId/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardGuildIdSecurityRoute = DashboardGuildIdSecurityRouteImport.update({
  id: '/dashboard/$guildId/security',
  path: '/dashboard/$guildId/security',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDiscordLogoutRoute = AuthDiscordLogoutRouteImport.update({
  id: '/auth/discord/logout',
  path: '/auth/discord/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDiscordLoginRoute = AuthDiscordLoginRouteImport.update({
  id: '/auth/discord/login',
  path: '/auth/discord/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDiscordCallbackRoute = AuthDiscordCallbackRouteImport.update({
  id: '/auth/discord/callback',
  path: '/auth/discord/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAuthDiscordLogoutRoute = ApiPublicAuthDiscordLogoutRouteImport.update({
  id: '/api/public/auth/discord/logout',
  path: '/api/public/auth/discord/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAuthDiscordLoginRoute = ApiPublicAuthDiscordLoginRouteImport.update({
  id: '/api/public/auth/discord/login',
  path: '/api/public/auth/discord/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAuthDiscordCallbackRoute = ApiPublicAuthDiscordCallbackRouteImport.update({
  id: '/api/public/auth/discord/callback',
  path: '/api/public/auth/discord/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/dashboard/$guildId/security': typeof DashboardGuildIdSecurityRoute
  '/dashboard/$guildId/tickets': typeof DashboardGuildIdTicketsRoute
  '/auth/discord/callback': typeof AuthDiscordCallbackRoute
  '/auth/discord/login': typeof AuthDiscordLoginRoute
  '/auth/discord/logout': typeof AuthDiscordLogoutRoute
  '/api/public/auth/discord/callback': typeof ApiPublicAuthDiscordCallbackRoute
  '/api/public/auth/discord/login': typeof ApiPublicAuthDiscordLoginRoute
  '/api/public/auth/discord/logout': typeof ApiPublicAuthDiscordLogoutRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/dashboard': typeof DashboardIndexRoute
  '/docs': typeof DocsIndexRoute
  '/dashboard/$guildId/security': typeof DashboardGuildIdSecurityRoute
  '/dashboard/$guildId/tickets': typeof DashboardGuildIdTicketsRoute
  '/auth/discord/callback': typeof AuthDiscordCallbackRoute
  '/auth/discord/login': typeof AuthDiscordLoginRoute
  '/auth/discord/logout': typeof AuthDiscordLogoutRoute
  '/api/public/auth/discord/callback': typeof ApiPublicAuthDiscordCallbackRoute
  '/api/public/auth/discord/login': typeof ApiPublicAuthDiscordLoginRoute
  '/api/public/auth/discord/logout': typeof ApiPublicAuthDiscordLogoutRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/dashboard/$guildId/security': typeof DashboardGuildIdSecurityRoute
  '/dashboard/$guildId/tickets': typeof DashboardGuildIdTicketsRoute
  '/auth/discord/callback': typeof AuthDiscordCallbackRoute
  '/auth/discord/login': typeof AuthDiscordLoginRoute
  '/auth/discord/logout': typeof AuthDiscordLogoutRoute
  '/api/public/auth/discord/callback': typeof ApiPublicAuthDiscordCallbackRoute
  '/api/public/auth/discord/login': typeof ApiPublicAuthDiscordLoginRoute
  '/api/public/auth/discord/logout': typeof ApiPublicAuthDiscordLogoutRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy'
    | '/terms'
    | '/docs/$slug'
    | '/dashboard/'
    | '/docs/'
    | '/dashboard/$guildId/security'
    | '/dashboard/$guildId/tickets'
    | '/auth/discord/callback'
    | '/auth/discord/login'
    | '/auth/discord/logout'
    | '/api/public/auth/discord/callback'
    | '/api/public/auth/discord/login'
    | '/api/public/auth/discord/logout'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy'
    | '/terms'
    | '/docs/$slug'
    | '/dashboard'
    | '/docs'
    | '/dashboard/$guildId/security'
    | '/dashboard/$guildId/tickets'
    | '/auth/discord/callback'
    | '/auth/discord/login'
    | '/auth/discord/logout'
    | '/api/public/auth/discord/callback'
    | '/api/public/auth/discord/login'
    | '/api/public/auth/discord/logout'
  id:
    | '__root__'
    | '/'
    | '/privacy'
    | '/terms'
    | '/docs/$slug'
    | '/dashboard/'
    | '/docs/'
    | '/dashboard/$guildId/security'
    | '/dashboard/$guildId/tickets'
    | '/auth/discord/callback'
    | '/auth/discord/login'
    | '/auth/discord/logout'
    | '/api/public/auth/discord/callback'
    | '/api/public/auth/discord/login'
    | '/api/public/auth/discord/logout'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  DocsSlugRoute: typeof DocsSlugRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DocsIndexRoute: typeof DocsIndexRoute
  DashboardGuildIdSecurityRoute: typeof DashboardGuildIdSecurityRoute
  DashboardGuildIdTicketsRoute: typeof DashboardGuildIdTicketsRoute
  AuthDiscordCallbackRoute: typeof AuthDiscordCallbackRoute
  AuthDiscordLoginRoute: typeof AuthDiscordLoginRoute
  AuthDiscordLogoutRoute: typeof AuthDiscordLogoutRoute
  ApiPublicAuthDiscordCallbackRoute: typeof ApiPublicAuthDiscordCallbackRoute
  ApiPublicAuthDiscordLoginRoute: typeof ApiPublicAuthDiscordLoginRoute
  ApiPublicAuthDiscordLogoutRoute: typeof ApiPublicAuthDiscordLogoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$slug': {
      id: '/docs/$slug'
      path: '/docs/$slug'
      fullPath: '/docs/$slug'
      preLoaderRoute: typeof DocsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$guildId/tickets': {
      id: '/dashboard/$guildId/tickets'
      path: '/dashboard/$guildId/tickets'
      fullPath: '/dashboard/$guildId/tickets'
      preLoaderRoute: typeof DashboardGuildIdTicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$guildId/security': {
      id: '/dashboard/$guildId/security'
      path: '/dashboard/$guildId/security'
      fullPath: '/dashboard/$guildId/security'
      preLoaderRoute: typeof DashboardGuildIdSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/discord/logout': {
      id: '/auth/discord/logout'
      path: '/auth/discord/logout'
      fullPath: '/auth/discord/logout'
      preLoaderRoute: typeof AuthDiscordLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/discord/login': {
      id: '/auth/discord/login'
      path: '/auth/discord/login'
      fullPath: '/auth/discord/login'
      preLoaderRoute: typeof AuthDiscordLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/discord/callback': {
      id: '/auth/discord/callback'
      path: '/auth/discord/callback'
      fullPath: '/auth/discord/callback'
      preLoaderRoute: typeof AuthDiscordCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auth/discord/logout': {
      id: '/api/public/auth/discord/logout'
      path: '/api/public/auth/discord/logout'
      fullPath: '/api/public/auth/discord/logout'
      preLoaderRoute: typeof ApiPublicAuthDiscordLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auth/discord/login': {
      id: '/api/public/auth/discord/login'
      path: '/api/public/auth/discord/login'
      fullPath: '/api/public/auth/discord/login'
      preLoaderRoute: typeof ApiPublicAuthDiscordLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auth/discord/callback': {
      id: '/api/public/auth/discord/callback'
      path: '/api/public/auth/discord/callback'
      fullPath: '/api/public/auth/discord/callback'
      preLoaderRoute: typeof ApiPublicAuthDiscordCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  DocsSlugRoute: DocsSlugRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DocsIndexRoute: DocsIndexRoute,
  DashboardGuildIdSecurityRoute: DashboardGuildIdSecurityRoute,
  DashboardGuildIdTicketsRoute: DashboardGuildIdTicketsRoute,
  AuthDiscordCallbackRoute: AuthDiscordCallbackRoute,
  AuthDiscordLoginRoute: AuthDiscordLoginRoute,
  AuthDiscordLogoutRoute: AuthDiscordLogoutRoute,
  ApiPublicAuthDiscordCallbackRoute: ApiPublicAuthDiscordCallbackRoute,
  ApiPublicAuthDiscordLoginRoute: ApiPublicAuthDiscordLoginRoute,
  ApiPublicAuthDiscordLogoutRoute: ApiPublicAuthDiscordLogoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
